import Foundation

// Auto-generated filter models. Generated by scripts/build.ts – do not edit manually.

public struct GroupsFilter: Codable, Sendable {
	public var topLevelOnly: Bool? = nil
	public var ownedOnly: Bool? = nil
	public var search: String? = nil
	public var parentPath: String? = nil
	public var allAvailable: Bool? = nil
	public var markedForDeletionOn: String? = nil
	public var active: Bool? = nil
	public init(topLevelOnly: Bool? = nil, ownedOnly: Bool? = nil, search: String? = nil, parentPath: String? = nil, allAvailable: Bool? = nil, markedForDeletionOn: String? = nil, active: Bool? = nil)
	{
		self.topLevelOnly = topLevelOnly
		self.ownedOnly = ownedOnly
		self.search = search
		self.parentPath = parentPath
		self.allAvailable = allAvailable
		self.markedForDeletionOn = markedForDeletionOn
		self.active = active
	}
}

public struct CurrentUserIssuesFilter: Codable, Sendable {
	public var state: IssuableState? = nil
	public var search: String? = nil
	public var confidential: Bool? = nil
	public var subscribed: SubscriptionStatus? = nil
	public var types: IssueType? = nil
	public init(state: IssuableState? = nil, search: String? = nil, confidential: Bool? = nil, subscribed: SubscriptionStatus? = nil, types: IssueType? = nil) {
		self.state = state
		self.search = search
		self.confidential = confidential
		self.subscribed = subscribed
		self.types = types
	}
}

public struct GroupIssuesFilter: Codable, Sendable {
	public var state: IssuableState? = nil
	public var search: String? = nil
	public var confidential: Bool? = nil
	public var subscribed: SubscriptionStatus? = nil
	public var types: IssueType? = nil
	public init(state: IssuableState? = nil, search: String? = nil, confidential: Bool? = nil, subscribed: SubscriptionStatus? = nil, types: IssueType? = nil) {
		self.state = state
		self.search = search
		self.confidential = confidential
		self.subscribed = subscribed
		self.types = types
	}
}

public struct IssueStateFilter: Codable, Sendable {
	public var stateEvent: IssueStateEvent? = nil
	public init(stateEvent: IssueStateEvent? = nil) {
		self.stateEvent = stateEvent
	}
}

public struct ProjectIssuesFilter: Codable, Sendable {
	public var state: IssuableState? = nil
	public var search: String? = nil
	public var confidential: Bool? = nil
	public var subscribed: SubscriptionStatus? = nil
	public var types: IssueType? = nil
	public init(state: IssuableState? = nil, search: String? = nil, confidential: Bool? = nil, subscribed: SubscriptionStatus? = nil, types: IssueType? = nil) {
		self.state = state
		self.search = search
		self.confidential = confidential
		self.subscribed = subscribed
		self.types = types
	}
}

public struct UserIssuesFilter: Codable, Sendable {
	public var state: IssuableState? = nil
	public var search: String? = nil
	public var confidential: Bool? = nil
	public var subscribed: SubscriptionStatus? = nil
	public var types: IssueType? = nil
	public init(state: IssuableState? = nil, search: String? = nil, confidential: Bool? = nil, subscribed: SubscriptionStatus? = nil, types: IssueType? = nil) {
		self.state = state
		self.search = search
		self.confidential = confidential
		self.subscribed = subscribed
		self.types = types
	}
}

public struct GroupMilestonesFilter: Codable, Sendable {
	public var state: MilestoneStateEnum? = nil
	public var searchTitle: String? = nil
	public var includeAncestors: Bool? = nil
	public init(state: MilestoneStateEnum? = nil, searchTitle: String? = nil, includeAncestors: Bool? = nil) {
		self.state = state
		self.searchTitle = searchTitle
		self.includeAncestors = includeAncestors
	}
}

public struct ProjectMilestonesFilter: Codable, Sendable {
	public var state: MilestoneStateEnum? = nil
	public var searchTitle: String? = nil
	public var includeAncestors: Bool? = nil
	public init(state: MilestoneStateEnum? = nil, searchTitle: String? = nil, includeAncestors: Bool? = nil) {
		self.state = state
		self.searchTitle = searchTitle
		self.includeAncestors = includeAncestors
	}
}

public struct ProjectsFilter: Codable, Sendable {
	public var membership: Bool? = nil
	public var search: String? = nil
	public var personal: Bool? = nil
	public var sort: String? = nil
	public var namespacePath: String? = nil
	public var withIssuesEnabled: Bool? = nil
	public var withMergeRequestsEnabled: Bool? = nil
	public var archived: ProjectArchived? = nil
	public var minAccessLevel: AccessLevelEnum? = nil
	public var aimedForDeletion: Bool? = nil
	public var notAimedForDeletion: Bool? = nil
	public var markedForDeletionOn: String? = nil
	public var active: Bool? = nil
	public var visibility: VisibilityLevelsEnum? = nil
	public init(
		membership: Bool? = nil, search: String? = nil, personal: Bool? = nil, sort: String? = nil, namespacePath: String? = nil, withIssuesEnabled: Bool? = nil, withMergeRequestsEnabled: Bool? = nil,
		archived: ProjectArchived? = nil, minAccessLevel: AccessLevelEnum? = nil, aimedForDeletion: Bool? = nil, notAimedForDeletion: Bool? = nil, markedForDeletionOn: String? = nil,
		active: Bool? = nil, visibility: VisibilityLevelsEnum? = nil
	) {
		self.membership = membership
		self.search = search
		self.personal = personal
		self.sort = sort
		self.namespacePath = namespacePath
		self.withIssuesEnabled = withIssuesEnabled
		self.withMergeRequestsEnabled = withMergeRequestsEnabled
		self.archived = archived
		self.minAccessLevel = minAccessLevel
		self.aimedForDeletion = aimedForDeletion
		self.notAimedForDeletion = notAimedForDeletion
		self.markedForDeletionOn = markedForDeletionOn
		self.active = active
		self.visibility = visibility
	}
}

public struct RepoTreeFilter: Codable, Sendable {
	public var ref: String? = nil
	public var path: String? = nil
	public init(ref: String? = nil, path: String? = nil) {
		self.ref = ref
		self.path = path
	}
}

public struct UsersFilter: Codable, Sendable {
	public var search: String? = nil
	public var admins: Bool? = nil
	public var active: Bool? = nil
	public var humans: Bool? = nil
	public init(search: String? = nil, admins: Bool? = nil, active: Bool? = nil, humans: Bool? = nil) {
		self.search = search
		self.admins = admins
		self.active = active
		self.humans = humans
	}
}
