import Foundation

// Auto-generated convenience methods for GitLabServiceType.
// Generated by scripts/build.ts – do not edit manually.

#if !SKIP
extension GitLabServiceType {

	// MARK: - Queries

	public func fetchEpic(fullPath: String, iid: String, strategy: FetchStrategy = .cacheFirst) async throws -> Epic_Group {
		let q = EpicQuery(fullPath: fullPath, iid: iid)
		let response = try await fetch(q, strategy: strategy)
		guard let data = response.group else { throw GitLabError.noData }
		return data
	}

	public func fetchGroupEpics(fullPath: String, strategy: FetchStrategy = .cacheFirst) async throws -> GroupEpics_Group {
		let q = GroupEpicsQuery(fullPath: fullPath)
		let response = try await fetch(q, strategy: strategy)
		guard let data = response.group else { throw GitLabError.noData }
		return data
	}

	public func fetchGroupCustomEmoji(fullPath: String, strategy: FetchStrategy = .cacheFirst) async throws -> GroupCustomEmoji_Group {
		let q = GroupCustomEmojiQuery(fullPath: fullPath)
		let response = try await fetch(q, strategy: strategy)
		guard let data = response.group else { throw GitLabError.noData }
		return data
	}

	public func fetchGroup(fullPath: String, strategy: FetchStrategy = .cacheFirst) async throws -> Group_Group {
		let q = GroupQuery(fullPath: fullPath)
		let response = try await fetch(q, strategy: strategy)
		guard let data = response.group else { throw GitLabError.noData }
		return data
	}

	public func fetchGroups(filter: GroupsFilter = GroupsFilter(), strategy: FetchStrategy = .cacheFirst) async throws -> Groups_Groups {
		let q = GroupsQuery(filter: filter)
		let response = try await fetch(q, strategy: strategy)
		guard let data = response.groups else { throw GitLabError.noData }
		return data
	}

	public func fetchUserGroups(username: String, strategy: FetchStrategy = .cacheFirst) async throws -> UserGroups_User {
		let q = UserGroupsQuery(username: username)
		let response = try await fetch(q, strategy: strategy)
		guard let data = response.user else { throw GitLabError.noData }
		return data
	}

	public func fetchCurrentUserIssues(filter: CurrentUserIssuesFilter = CurrentUserIssuesFilter(), strategy: FetchStrategy = .cacheFirst) async throws -> CurrentUserIssues_CurrentUser {
		let q = CurrentUserIssuesQuery(filter: filter)
		let response = try await fetch(q, strategy: strategy)
		guard let data = response.currentUser else { throw GitLabError.noData }
		return data
	}

	public func fetchEpicIssues(fullPath: String, iid: String, strategy: FetchStrategy = .cacheFirst) async throws -> EpicIssues_Group {
		let q = EpicIssuesQuery(fullPath: fullPath, iid: iid)
		let response = try await fetch(q, strategy: strategy)
		guard let data = response.group else { throw GitLabError.noData }
		return data
	}

	public func fetchGroupIssues(fullPath: String, filter: GroupIssuesFilter = GroupIssuesFilter(), strategy: FetchStrategy = .cacheFirst) async throws -> GroupIssues_Group {
		let q = GroupIssuesQuery(fullPath: fullPath, filter: filter)
		let response = try await fetch(q, strategy: strategy)
		guard let data = response.group else { throw GitLabError.noData }
		return data
	}

	public func fetchIssue(fullPath: String, iid: String, strategy: FetchStrategy = .cacheFirst) async throws -> Issue_Project {
		let q = IssueQuery(fullPath: fullPath, iid: iid)
		let response = try await fetch(q, strategy: strategy)
		guard let data = response.project else { throw GitLabError.noData }
		return data
	}

	public func fetchIssueState(projectPath: String, iid: String, filter: IssueStateFilter = IssueStateFilter(), strategy: FetchStrategy = .cacheFirst) async throws -> IssueState_UpdateIssue {
		let q = IssueStateQuery(projectPath: projectPath, iid: iid, filter: filter)
		let response = try await fetch(q, strategy: strategy)
		guard let data = response.updateIssue else { throw GitLabError.noData }
		return data
	}

	public func fetchProjectIssues(fullPath: String, filter: ProjectIssuesFilter = ProjectIssuesFilter(), strategy: FetchStrategy = .cacheFirst) async throws -> ProjectIssues_Project {
		let q = ProjectIssuesQuery(fullPath: fullPath, filter: filter)
		let response = try await fetch(q, strategy: strategy)
		guard let data = response.project else { throw GitLabError.noData }
		return data
	}

	public func fetchUserIssues(username: String, filter: UserIssuesFilter = UserIssuesFilter(), strategy: FetchStrategy = .cacheFirst) async throws -> UserIssues_User {
		let q = UserIssuesQuery(username: username, filter: filter)
		let response = try await fetch(q, strategy: strategy)
		guard let data = response.user else { throw GitLabError.noData }
		return data
	}

	public func fetchGroupLabels(fullPath: String, strategy: FetchStrategy = .cacheFirst) async throws -> [MyLabel] {
		let q = GroupLabelsQuery(fullPath: fullPath)
		let response = try await fetch(q, strategy: strategy)
		return response.group?.labels?.nodes?.compactMap { $0 } ?? []
	}

	public func fetchProjectLabels(fullPath: String, strategy: FetchStrategy = .cacheFirst) async throws -> [MyLabel] {
		let q = ProjectLabelsQuery(fullPath: fullPath)
		let response = try await fetch(q, strategy: strategy)
		return response.project?.labels?.nodes?.compactMap { $0 } ?? []
	}

	public func fetchGroupMergeRequests(fullPath: String, strategy: FetchStrategy = .cacheFirst) async throws -> GroupMergeRequests_Group {
		let q = GroupMergeRequestsQuery(fullPath: fullPath)
		let response = try await fetch(q, strategy: strategy)
		guard let data = response.group else { throw GitLabError.noData }
		return data
	}

	public func fetchMergeRequest(fullPath: String, iid: String, strategy: FetchStrategy = .cacheFirst) async throws -> MergeRequest_Project {
		let q = MergeRequestQuery(fullPath: fullPath, iid: iid)
		let response = try await fetch(q, strategy: strategy)
		guard let data = response.project else { throw GitLabError.noData }
		return data
	}

	public func fetchProjectMergeRequests(fullPath: String, strategy: FetchStrategy = .cacheFirst) async throws -> ProjectMergeRequests_Project {
		let q = ProjectMergeRequestsQuery(fullPath: fullPath)
		let response = try await fetch(q, strategy: strategy)
		guard let data = response.project else { throw GitLabError.noData }
		return data
	}

	public func fetchUserAssignedMergeRequests(strategy: FetchStrategy = .cacheFirst) async throws -> UserAssignedMergeRequests_CurrentUser {
		let q = UserAssignedMergeRequestsQuery()
		let response = try await fetch(q, strategy: strategy)
		guard let data = response.currentUser else { throw GitLabError.noData }
		return data
	}

	public func fetchUserAuthoredMergeRequests(strategy: FetchStrategy = .cacheFirst) async throws -> UserAuthoredMergeRequests_CurrentUser {
		let q = UserAuthoredMergeRequestsQuery()
		let response = try await fetch(q, strategy: strategy)
		guard let data = response.currentUser else { throw GitLabError.noData }
		return data
	}

	public func fetchUserReviewRequestedMergeRequests(strategy: FetchStrategy = .cacheFirst) async throws -> UserReviewRequestedMergeRequests_CurrentUser {
		let q = UserReviewRequestedMergeRequestsQuery()
		let response = try await fetch(q, strategy: strategy)
		guard let data = response.currentUser else { throw GitLabError.noData }
		return data
	}

	public func fetchMergeRequestCommits(fullPath: String, iid: String, strategy: FetchStrategy = .cacheFirst) async throws -> MergeRequestCommits_Project {
		let q = MergeRequestCommitsQuery(fullPath: fullPath, iid: iid)
		let response = try await fetch(q, strategy: strategy)
		guard let data = response.project else { throw GitLabError.noData }
		return data
	}

	public func fetchMergeRequestDiffs(fullPath: String, iid: String, strategy: FetchStrategy = .cacheFirst) async throws -> MergeRequestDiffs_Project {
		let q = MergeRequestDiffsQuery(fullPath: fullPath, iid: iid)
		let response = try await fetch(q, strategy: strategy)
		guard let data = response.project else { throw GitLabError.noData }
		return data
	}

	public func fetchGroupMilestones(fullPath: String, filter: GroupMilestonesFilter = GroupMilestonesFilter(), strategy: FetchStrategy = .cacheFirst) async throws -> GroupMilestones_Group {
		let q = GroupMilestonesQuery(fullPath: fullPath, filter: filter)
		let response = try await fetch(q, strategy: strategy)
		guard let data = response.group else { throw GitLabError.noData }
		return data
	}

	public func fetchProjectMilestones(fullPath: String, filter: ProjectMilestonesFilter = ProjectMilestonesFilter(), strategy: FetchStrategy = .cacheFirst) async throws -> ProjectMilestones_Project {
		let q = ProjectMilestonesQuery(fullPath: fullPath, filter: filter)
		let response = try await fetch(q, strategy: strategy)
		guard let data = response.project else { throw GitLabError.noData }
		return data
	}

	public func fetchProjectPipelines(fullPath: String, strategy: FetchStrategy = .cacheFirst) async throws -> ProjectPipelines_Project {
		let q = ProjectPipelinesQuery(fullPath: fullPath)
		let response = try await fetch(q, strategy: strategy)
		guard let data = response.project else { throw GitLabError.noData }
		return data
	}

	public func fetchProjectReleasesQuery(fullPath: String, strategy: FetchStrategy = .cacheFirst) async throws -> ProjectReleasesQuery_Project {
		let q = ProjectReleasesQueryQuery(fullPath: fullPath)
		let response = try await fetch(q, strategy: strategy)
		guard let data = response.project else { throw GitLabError.noData }
		return data
	}

	public func fetchCurrentUserStarredProjects(strategy: FetchStrategy = .cacheFirst) async throws -> [SmallProject] {
		let q = CurrentUserStarredProjectsQuery()
		let response = try await fetch(q, strategy: strategy)
		return response.currentUser?.starredProjects?.nodes?.compactMap { $0 } ?? []
	}

	public func fetchProject(fullPath: String, strategy: FetchStrategy = .cacheFirst) async throws -> Project_Project {
		let q = ProjectQuery(fullPath: fullPath)
		let response = try await fetch(q, strategy: strategy)
		guard let data = response.project else { throw GitLabError.noData }
		return data
	}

	public func fetchProjects(filter: ProjectsFilter = ProjectsFilter(), strategy: FetchStrategy = .cacheFirst) async throws -> [SmallProject] {
		let q = ProjectsQuery(filter: filter)
		let response = try await fetch(q, strategy: strategy)
		return response.projects?.nodes?.compactMap { $0 } ?? []
	}

	public func fetchStarProject(projectId: String, starred: Bool, strategy: FetchStrategy = .cacheFirst) async throws -> StarProject_StarProject {
		let q = StarProjectQuery(projectId: projectId, starred: starred)
		let response = try await fetch(q, strategy: strategy)
		guard let data = response.starProject else { throw GitLabError.noData }
		return data
	}

	public func fetchUserStarredProjects(username: String, strategy: FetchStrategy = .cacheFirst) async throws -> [SmallProject] {
		let q = UserStarredProjectsQuery(username: username)
		let response = try await fetch(q, strategy: strategy)
		return response.user?.starredProjects?.nodes?.compactMap { $0 } ?? []
	}

	public func fetchRepoTree(fullPath: String, filter: RepoTreeFilter = RepoTreeFilter(), strategy: FetchStrategy = .cacheFirst) async throws -> RepoTree_Project {
		let q = RepoTreeQuery(fullPath: fullPath, filter: filter)
		let response = try await fetch(q, strategy: strategy)
		guard let data = response.project else { throw GitLabError.noData }
		return data
	}

	public func fetchCurrentUserSnippets(strategy: FetchStrategy = .cacheFirst) async throws -> CurrentUserSnippets_CurrentUser {
		let q = CurrentUserSnippetsQuery()
		let response = try await fetch(q, strategy: strategy)
		guard let data = response.currentUser else { throw GitLabError.noData }
		return data
	}

	public func fetchSnippet(id: String, strategy: FetchStrategy = .cacheFirst) async throws -> Snippet_Snippets {
		let q = SnippetQuery(id: id)
		let response = try await fetch(q, strategy: strategy)
		guard let data = response.snippets else { throw GitLabError.noData }
		return data
	}

	public func fetchUserSnippets(username: String, strategy: FetchStrategy = .cacheFirst) async throws -> UserSnippets_User {
		let q = UserSnippetsQuery(username: username)
		let response = try await fetch(q, strategy: strategy)
		guard let data = response.user else { throw GitLabError.noData }
		return data
	}

	public func fetchGroupTimelogs(fullPath: String, strategy: FetchStrategy = .cacheFirst) async throws -> GroupTimelogs_Group {
		let q = GroupTimelogsQuery(fullPath: fullPath)
		let response = try await fetch(q, strategy: strategy)
		guard let data = response.group else { throw GitLabError.noData }
		return data
	}

	public func fetchUserTimelogs(username: String, strategy: FetchStrategy = .cacheFirst) async throws -> UserTimelogs_User {
		let q = UserTimelogsQuery(username: username)
		let response = try await fetch(q, strategy: strategy)
		guard let data = response.user else { throw GitLabError.noData }
		return data
	}

	public func fetchCurrentUserTodos(strategy: FetchStrategy = .cacheFirst) async throws -> CurrentUserTodos_CurrentUser {
		let q = CurrentUserTodosQuery()
		let response = try await fetch(q, strategy: strategy)
		guard let data = response.currentUser else { throw GitLabError.noData }
		return data
	}

	public func fetchUserTodos(username: String, strategy: FetchStrategy = .cacheFirst) async throws -> UserTodos_User {
		let q = UserTodosQuery(username: username)
		let response = try await fetch(q, strategy: strategy)
		guard let data = response.user else { throw GitLabError.noData }
		return data
	}

	public func fetchCurrentUser(strategy: FetchStrategy = .cacheFirst) async throws -> CurrentUser_CurrentUser {
		let q = CurrentUserQuery()
		let response = try await fetch(q, strategy: strategy)
		guard let data = response.currentUser else { throw GitLabError.noData }
		return data
	}

	public func fetchGroupMembers(fullPath: String, strategy: FetchStrategy = .cacheFirst) async throws -> GroupMembers_Group {
		let q = GroupMembersQuery(fullPath: fullPath)
		let response = try await fetch(q, strategy: strategy)
		guard let data = response.group else { throw GitLabError.noData }
		return data
	}

	public func fetchProjectMembers(fullPath: String, strategy: FetchStrategy = .cacheFirst) async throws -> ProjectMembers_Project {
		let q = ProjectMembersQuery(fullPath: fullPath)
		let response = try await fetch(q, strategy: strategy)
		guard let data = response.project else { throw GitLabError.noData }
		return data
	}

	public func fetchUser(username: String, strategy: FetchStrategy = .cacheFirst) async throws -> User_User {
		let q = UserQuery(username: username)
		let response = try await fetch(q, strategy: strategy)
		guard let data = response.user else { throw GitLabError.noData }
		return data
	}

	public func fetchUsers(filter: UsersFilter = UsersFilter(), strategy: FetchStrategy = .cacheFirst) async throws -> [Author] {
		let q = UsersQuery(filter: filter)
		let response = try await fetch(q, strategy: strategy)
		return response.users?.nodes?.compactMap { $0 } ?? []
	}

}
#endif
