import Foundation

// Auto-generated query structs with nested Codable response types.
// Generated by scripts/build.ts – do not edit manually.

public struct EmptyVariables: Encodable, Sendable { public init() {} }

// MARK: - Epic

public struct EpicQuery: GitLabQuery {
	public let operationName = "Epic"
	public let queryString = """
		query Epic($fullPath: ID!, $iid: ID!) {
		  group(fullPath: $fullPath) {
		    id
		    avatarUrl
		    epic(iid: $iid) {
		      iid
		      title
		      description
		      reference(full: true)
		      state
		      dueDate
		      createdAt
		      webUrl
		
		      startDate
		      dueDate
		      color
		      textColor
		
		      upvotes
		      downvotes
		      userNotesCount
		
		      author {
		        avatarUrl
		        name
		        username
		      }
		
		      ancestors {
		        nodes {
		          iid
		        }
		      }
		
		      blockedByEpics {
		        nodes {
		          iid
		        }
		      }
		
		      children {
		        nodes {
		          iid
		        }
		      }
		
		      userPermissions {
		        updateEpic
		        createNote
		      }
		
		      labels {
		        nodes {
		          title
		          color
		          textColor
		        }
		      }
		
		      notes {
		        nodes {
		          id
		          author {
		            avatarUrl
		            name
		            username
		          }
		          maxAccessLevelOfAuthor
		          body
		          system
		          systemNoteIconName
		          createdAt
		          updatedAt
		        }
		      }
		    }
		  }
		}
		"""
	public let variablesJSON: Data
	public typealias Response = EpicResponse

	public init(fullPath: String, iid: String) {
		let dict: [String: Any] = ["fullPath": fullPath, "iid": iid]
		self.variablesJSON = (try? JSONSerialization.data(withJSONObject: dict)) ?? Data()
	}
}

// MARK: - GroupEpics

public struct GroupEpicsQuery: GitLabQuery {
	public let operationName = "GroupEpics"
	public let queryString = """
		query GroupEpics($fullPath: ID!) {
		  group(fullPath: $fullPath) {
		    epics(state: opened) {
		      nodes {
		        iid
		        title
		        reference(full: true)
		        state
		        upvotes
		        downvotes
		        userNotesCount
		        author {
		          avatarUrl
		          name
		          username
		        }
		        createdAt
		        webUrl
		      }
		    }
		  }
		}
		"""
	public let variablesJSON: Data
	public typealias Response = GroupEpicsResponse

	public init(fullPath: String) {
		let dict: [String: Any] = ["fullPath": fullPath]
		self.variablesJSON = (try? JSONSerialization.data(withJSONObject: dict)) ?? Data()
	}
}

// MARK: - GroupCustomEmoji

public struct GroupCustomEmojiQuery: GitLabQuery {
	public let operationName = "GroupCustomEmoji"
	public let queryString = """
		query GroupCustomEmoji($fullPath: ID!) {
		  group(fullPath: $fullPath) {
		    customEmoji {
		      nodes {
		        id
		        url
		        name
		        createdAt
		      }
		    }
		  }
		}
		"""
	public let variablesJSON: Data
	public typealias Response = GroupCustomEmojiResponse

	public init(fullPath: String) {
		let dict: [String: Any] = ["fullPath": fullPath]
		self.variablesJSON = (try? JSONSerialization.data(withJSONObject: dict)) ?? Data()
	}
}

// MARK: - Group

public struct GroupQuery: GitLabQuery {
	public let operationName = "Group"
	public let queryString = """
		query Group($fullPath: ID!) {
		  group(fullPath:$fullPath) {
		    id
		
		    avatarUrl
		    name
		    path
		    fullName
		    visibility
		    description
		
		    descendantGroupsCount
		    groupMembersCount
		    projectsCount
		
		    requestAccessEnabled
		    webUrl
		
		    maxAccessLevel {
		      stringValue
		    }
		
		    userPermissions {
		      createProjects
		    }
		
		    parent {
		      name
		      fullPath
		    }
		  }
		}
		"""
	public let variablesJSON: Data
	public typealias Response = GroupResponse

	public init(fullPath: String) {
		let dict: [String: Any] = ["fullPath": fullPath]
		self.variablesJSON = (try? JSONSerialization.data(withJSONObject: dict)) ?? Data()
	}
}

// MARK: - Groups

public struct GroupsQuery: GitLabQuery {
	public let operationName = "Groups"
	public let queryString = """
		query Groups($topLevelOnly: Boolean, $ownedOnly: Boolean, $search: String, $parentPath: ID, $allAvailable: Boolean, $markedForDeletionOn: Date, $active: Boolean) {
		  groups(
		    topLevelOnly: $topLevelOnly
		    ownedOnly: $ownedOnly
		    search: $search
		    parentPath: $parentPath
		    allAvailable: $allAvailable
		    markedForDeletionOn: $markedForDeletionOn
		    active: $active
		  ) {
		    nodes {
		      avatarUrl
		      name
		      fullPath
		      visibility
		      groupMembersCount
		      projectsCount
		      maxAccessLevel {
		        stringValue
		      }
		    }
		  }
		}
		"""
	public let variablesJSON: Data
	public typealias Response = GroupsResponse

	public init(variablesJSON: Data) { self.variablesJSON = variablesJSON }

	public init(filter: GroupsFilter = GroupsFilter()) {
		self.variablesJSON = (try? JSONEncoder().encode(filter)) ?? Data()
	}

}

// MARK: - UserGroups

public struct UserGroupsQuery: GitLabQuery {
	public let operationName = "UserGroups"
	public let queryString = """
		query UserGroups($username: String!) {
		  user(username: $username) {
		    groups {
		      nodes {
		        avatarUrl
		        name
		        fullPath
		        visibility
		        groupMembersCount
		        projectsCount
		        maxAccessLevel {
		          stringValue
		        }
		      }
		    }
		  }
		}
		"""
	public let variablesJSON: Data
	public typealias Response = UserGroupsResponse

	public init(username: String) {
		let dict: [String: Any] = ["username": username]
		self.variablesJSON = (try? JSONSerialization.data(withJSONObject: dict)) ?? Data()
	}
}

// MARK: - CurrentUserIssues

public struct CurrentUserIssuesQuery: GitLabQuery {
	public let operationName = "CurrentUserIssues"
	public let queryString = """
		query CurrentUserIssues($state: IssuableState, $search: String, $confidential: Boolean, $subscribed: SubscriptionStatus, $types: [IssueType!]) {
		  currentUser {
		    projectMemberships {
		      nodes {
		        project {
		          fullPath
		          issues(
		            state: $state
		            search: $search
		            confidential: $confidential
		            subscribed: $subscribed
		            types: $types
		          ) {
		            nodes {
		              iid
		              title
		              reference(full: true)
		              state
		              upvotes
		              downvotes
		              userNotesCount
		              author {
		                avatarUrl
		                name
		                username
		              }
		              createdAt
		              webUrl
		            }
		          }
		        }
		      }
		    }
		  }
		}
		"""
	public let variablesJSON: Data
	public typealias Response = CurrentUserIssuesResponse

	public init(variablesJSON: Data) { self.variablesJSON = variablesJSON }

	public init(filter: CurrentUserIssuesFilter = CurrentUserIssuesFilter()) {
		self.variablesJSON = (try? JSONEncoder().encode(filter)) ?? Data()
	}

}

// MARK: - EpicIssues

public struct EpicIssuesQuery: GitLabQuery {
	public let operationName = "EpicIssues"
	public let queryString = """
		query EpicIssues($fullPath: ID!, $iid: ID!) {
		  group(fullPath: $fullPath) {
		    epic(iid: $iid) {
		      issues {
		        nodes {
		          iid
		          title
		          reference(full: true)
		          state
		          upvotes
		          downvotes
		          userNotesCount
		          author {
		            avatarUrl
		            name
		            username
		          }
		          createdAt
		          webUrl
		        }
		      }
		    }
		  }
		}
		"""
	public let variablesJSON: Data
	public typealias Response = EpicIssuesResponse

	public init(fullPath: String, iid: String) {
		let dict: [String: Any] = ["fullPath": fullPath, "iid": iid]
		self.variablesJSON = (try? JSONSerialization.data(withJSONObject: dict)) ?? Data()
	}
}

// MARK: - GroupIssues

public struct GroupIssuesQuery: GitLabQuery {
	public let operationName = "GroupIssues"
	public let queryString = """
		query GroupIssues($fullPath: ID!, $state: IssuableState, $search: String, $confidential: Boolean, $subscribed: SubscriptionStatus, $types: [IssueType!]) {
		  group(fullPath: $fullPath) {
		    issues(
		      state: $state
		      search: $search
		      confidential: $confidential
		      subscribed: $subscribed
		      types: $types
		    ) {
		      nodes {
		        iid
		        title
		        reference(full: true)
		        state
		        upvotes
		        downvotes
		        userNotesCount
		        author {
		          avatarUrl
		          name
		          username
		        }
		        createdAt
		        webUrl
		      }
		    }
		  }
		}
		"""
	public let variablesJSON: Data
	public typealias Response = GroupIssuesResponse

	public init(variablesJSON: Data) { self.variablesJSON = variablesJSON }

	public init(fullPath: String, filter: GroupIssuesFilter = GroupIssuesFilter()) {
		var dict = ["fullPath": fullPath] as [String: Any]
		if let filterData = try? JSONEncoder().encode(filter),
		   let filterDict = try? JSONSerialization.jsonObject(with: filterData) as? [String: Any] {
			for (k, v) in filterDict { dict[k] = v }
		}
		self.variablesJSON = (try? JSONSerialization.data(withJSONObject: dict)) ?? Data()
	}

}

// MARK: - Issue

public struct IssueQuery: GitLabQuery {
	public let operationName = "Issue"
	public let queryString = """
		query Issue($fullPath: ID!, $iid: String!) {
		  project(fullPath: $fullPath) {
		    id
		    avatarUrl
		
		    issue(iid: $iid) {
		      iid
		      title
		      description
		      reference(full: true)
		      state
		      weight
		      dueDate
		      blockedByIssues {
		        nodes {
		          iid
		        }
		      }
		      createdAt
		      webUrl
		
		      upvotes
		      downvotes
		      userNotesCount
		      author {
		        avatarUrl
		        name
		        username
		      }
		
		      userPermissions {
		        updateIssue
		        createNote
		      }
		
		      assignees {
		        nodes {
		          avatarUrl
		          username
		        }
		      }
		
		      labels {
		        nodes {
		          title
		          color
		          textColor
		        }
		      }
		
		      milestone {
		        iid
		        title
		      }
		
		      humanTimeEstimate
		      humanTotalTimeSpent
		
		      notes {
		        nodes {
		          id
		          author {
		            avatarUrl
		            name
		            username
		          }
		          maxAccessLevelOfAuthor
		          body
		          system
		          systemNoteIconName
		          createdAt
		          updatedAt
		        }
		      }
		    }
		  }
		}
		"""
	public let variablesJSON: Data
	public typealias Response = IssueResponse

	public init(fullPath: String, iid: String) {
		let dict: [String: Any] = ["fullPath": fullPath, "iid": iid]
		self.variablesJSON = (try? JSONSerialization.data(withJSONObject: dict)) ?? Data()
	}
}

// MARK: - IssueState

public struct IssueStateQuery: GitLabQuery {
	public let operationName = "IssueState"
	public let queryString = """
		mutation IssueState($projectPath: ID!, $iid: String!, $stateEvent: IssueStateEvent) {
		  updateIssue(
		    input: {projectPath: $projectPath, iid: $iid, stateEvent: $stateEvent}
		  ) {
		    issue {
		      id
		      iid
		      title
		      state
		      webUrl
		    }
		    errors
		  }
		}
		"""
	public let variablesJSON: Data
	public typealias Response = IssueStateResponse

	public init(variablesJSON: Data) { self.variablesJSON = variablesJSON }

	public init(projectPath: String, iid: String, filter: IssueStateFilter = IssueStateFilter()) {
		var dict = ["projectPath": projectPath, "iid": iid] as [String: Any]
		if let filterData = try? JSONEncoder().encode(filter),
		   let filterDict = try? JSONSerialization.jsonObject(with: filterData) as? [String: Any] {
			for (k, v) in filterDict { dict[k] = v }
		}
		self.variablesJSON = (try? JSONSerialization.data(withJSONObject: dict)) ?? Data()
	}

}

// MARK: - ProjectIssues

public struct ProjectIssuesQuery: GitLabQuery {
	public let operationName = "ProjectIssues"
	public let queryString = """
		query ProjectIssues($fullPath: ID!, $state: IssuableState, $search: String, $confidential: Boolean, $subscribed: SubscriptionStatus, $types: [IssueType!]) {
		  project(fullPath: $fullPath) {
		    id
		    issuesEnabled
		    userPermissions {
		      createIssue
		    }
		    issues(
		      state: $state
		      search: $search
		      confidential: $confidential
		      subscribed: $subscribed
		      types: $types
		    ) {
		      nodes {
		        iid
		        title
		        reference(full: true)
		        state
		        upvotes
		        downvotes
		        userNotesCount
		        author {
		          avatarUrl
		          name
		          username
		        }
		        createdAt
		        webUrl
		      }
		    }
		  }
		}
		"""
	public let variablesJSON: Data
	public typealias Response = ProjectIssuesResponse

	public init(variablesJSON: Data) { self.variablesJSON = variablesJSON }

	public init(fullPath: String, filter: ProjectIssuesFilter = ProjectIssuesFilter()) {
		var dict = ["fullPath": fullPath] as [String: Any]
		if let filterData = try? JSONEncoder().encode(filter),
		   let filterDict = try? JSONSerialization.jsonObject(with: filterData) as? [String: Any] {
			for (k, v) in filterDict { dict[k] = v }
		}
		self.variablesJSON = (try? JSONSerialization.data(withJSONObject: dict)) ?? Data()
	}

}

// MARK: - UserIssues

public struct UserIssuesQuery: GitLabQuery {
	public let operationName = "UserIssues"
	public let queryString = """
		query UserIssues($username: String!, $state: IssuableState, $search: String, $confidential: Boolean, $subscribed: SubscriptionStatus, $types: [IssueType!]) {
		  user(username: $username) {
		    projectMemberships {
		      nodes {
		        project {
		          fullPath
		          issues(
		            state: $state
		            search: $search
		            confidential: $confidential
		            subscribed: $subscribed
		            types: $types
		            assigneeUsernames: [$username]
		            authorUsername: $username
		          ) {
		            nodes {
		              iid
		              title
		              reference(full: true)
		              state
		              upvotes
		              downvotes
		              userNotesCount
		              author {
		                avatarUrl
		                name
		                username
		              }
		              createdAt
		              webUrl
		            }
		          }
		        }
		      }
		    }
		  }
		}
		"""
	public let variablesJSON: Data
	public typealias Response = UserIssuesResponse

	public init(variablesJSON: Data) { self.variablesJSON = variablesJSON }

	public init(username: String, filter: UserIssuesFilter = UserIssuesFilter()) {
		var dict = ["username": username] as [String: Any]
		if let filterData = try? JSONEncoder().encode(filter),
		   let filterDict = try? JSONSerialization.jsonObject(with: filterData) as? [String: Any] {
			for (k, v) in filterDict { dict[k] = v }
		}
		self.variablesJSON = (try? JSONSerialization.data(withJSONObject: dict)) ?? Data()
	}

}

// MARK: - GroupLabels

public struct GroupLabelsQuery: GitLabQuery {
	public let operationName = "GroupLabels"
	public let queryString = """
		query GroupLabels($fullPath: ID!) {
		  group(fullPath: $fullPath) {
		    labels {
		      nodes {
		        id
		        title
		        description
		        color
		        textColor
		      }
		    }
		  }
		}
		"""
	public let variablesJSON: Data
	public typealias Response = GroupLabelsResponse

	public init(fullPath: String) {
		let dict: [String: Any] = ["fullPath": fullPath]
		self.variablesJSON = (try? JSONSerialization.data(withJSONObject: dict)) ?? Data()
	}
}

// MARK: - ProjectLabels

public struct ProjectLabelsQuery: GitLabQuery {
	public let operationName = "ProjectLabels"
	public let queryString = """
		query ProjectLabels($fullPath: ID!) {
		  project(fullPath: $fullPath) {
		    labels {
		      nodes {
		        id
		        title
		        description
		        color
		        textColor
		      }
		    }
		  }
		}
		"""
	public let variablesJSON: Data
	public typealias Response = ProjectLabelsResponse

	public init(fullPath: String) {
		let dict: [String: Any] = ["fullPath": fullPath]
		self.variablesJSON = (try? JSONSerialization.data(withJSONObject: dict)) ?? Data()
	}
}

// MARK: - GroupMergeRequests

public struct GroupMergeRequestsQuery: GitLabQuery {
	public let operationName = "GroupMergeRequests"
	public let queryString = """
		query GroupMergeRequests($fullPath: ID!) {
		  group(fullPath: $fullPath) {
		    mergeRequests(state: opened) {
		      nodes {
		        iid
		        title
		        reference(full: true)
		        state
		        upvotes
		        downvotes
		        userNotesCount
		        author {
		          avatarUrl
		          name
		          username
		        }
		        createdAt
		        webUrl
		      }
		    }
		  }
		}
		"""
	public let variablesJSON: Data
	public typealias Response = GroupMergeRequestsResponse

	public init(fullPath: String) {
		let dict: [String: Any] = ["fullPath": fullPath]
		self.variablesJSON = (try? JSONSerialization.data(withJSONObject: dict)) ?? Data()
	}
}

// MARK: - MergeRequest

public struct MergeRequestQuery: GitLabQuery {
	public let operationName = "MergeRequest"
	public let queryString = """
		query MergeRequest($fullPath: ID!, $iid: String!) {
		  project(fullPath: $fullPath) {
		  id
		  avatarUrl
		
		    mergeRequest(iid: $iid) {
		      iid
		      title
		      description
		      reference(full: true)
		      state
		      sourceBranch
		      targetBranch
		      sourceProject {
		        fullPath
		      }
		      diffStatsSummary {
		        additions
		        deletions
		        fileCount
		      }
		      upvotes
		      downvotes
		      userNotesCount
		      author {
		        avatarUrl
		        name
		        username
		      }
		      userPermissions {
		        canApprove
		        canMerge
		        updateMergeRequest
		        createNote
		      }
		      createdAt
		      webUrl
		
		      approved
		      mergeStatusEnum
		      conflicts
		      detailedMergeStatus
		
		      assignees {
		        nodes {
		          avatarUrl
		          username
		        }
		      }
		
		      reviewers {
		        nodes {
		          avatarUrl
		          username
		        }
		      }
		
		      labels {
		        nodes {
		          title
		          color
		          textColor
		        }
		      }
		
		      milestone {
		        iid
		        title
		      }
		
		      humanTimeEstimate
		      humanTotalTimeSpent
		
		      notes {
		        nodes {
		          id
		          author {
		            avatarUrl
		            name
		            username
		          }
		          maxAccessLevelOfAuthor
		          body
		          system
		          systemNoteIconName
		          createdAt
		          updatedAt
		        }
		      }
		    }
		  }
		}
		"""
	public let variablesJSON: Data
	public typealias Response = MergeRequestResponse

	public init(fullPath: String, iid: String) {
		let dict: [String: Any] = ["fullPath": fullPath, "iid": iid]
		self.variablesJSON = (try? JSONSerialization.data(withJSONObject: dict)) ?? Data()
	}
}

// MARK: - ProjectMergeRequests

public struct ProjectMergeRequestsQuery: GitLabQuery {
	public let operationName = "ProjectMergeRequests"
	public let queryString = """
		query ProjectMergeRequests($fullPath: ID!) {
		  project(fullPath: $fullPath) {
		    mergeRequestsEnabled
		
		    mergeRequests(state: opened) {
		      nodes {
		        iid
		        title
		        reference(full: true)
		        state
		        upvotes
		        downvotes
		        userNotesCount
		        author {
		          avatarUrl
		          name
		          username
		        }
		        createdAt
		        webUrl
		      }
		    }
		  }
		}
		"""
	public let variablesJSON: Data
	public typealias Response = ProjectMergeRequestsResponse

	public init(fullPath: String) {
		let dict: [String: Any] = ["fullPath": fullPath]
		self.variablesJSON = (try? JSONSerialization.data(withJSONObject: dict)) ?? Data()
	}
}

// MARK: - UserAssignedMergeRequests

public struct UserAssignedMergeRequestsQuery: GitLabQuery {
	public let operationName = "UserAssignedMergeRequests"
	public let queryString = """
		query UserAssignedMergeRequests {
		  currentUser {
		    assignedMergeRequests(state: opened) {
		      nodes {
		        project {
		          fullPath
		        }
		        iid
		        title
		        reference(full: true)
		        state
		        upvotes
		        downvotes
		        userNotesCount
		        author {
		          avatarUrl
		          name
		          username
		        }
		        createdAt
		        webUrl
		      }
		    }
		  }
		}
		"""
	public let variablesJSON: Data
	public typealias Response = UserAssignedMergeRequestsResponse

	public init() { self.variablesJSON = Data() }
}

// MARK: - UserAuthoredMergeRequests

public struct UserAuthoredMergeRequestsQuery: GitLabQuery {
	public let operationName = "UserAuthoredMergeRequests"
	public let queryString = """
		query UserAuthoredMergeRequests {
		  currentUser {
		    authoredMergeRequests(state: opened) {
		      nodes {
		        project {
		          fullPath
		        }
		        iid
		        title
		        reference(full: true)
		        state
		        upvotes
		        downvotes
		        userNotesCount
		        author {
		          avatarUrl
		          name
		          username
		        }
		        createdAt
		        webUrl
		      }
		    }
		  }
		}
		"""
	public let variablesJSON: Data
	public typealias Response = UserAuthoredMergeRequestsResponse

	public init() { self.variablesJSON = Data() }
}

// MARK: - UserReviewRequestedMergeRequests

public struct UserReviewRequestedMergeRequestsQuery: GitLabQuery {
	public let operationName = "UserReviewRequestedMergeRequests"
	public let queryString = """
		query UserReviewRequestedMergeRequests {
		  currentUser {
		    reviewRequestedMergeRequests(state: opened) {
		      count
		      nodes {
		        project {
		          fullPath
		        }
		        iid
		        title
		        reference(full: true)
		        state
		        upvotes
		        downvotes
		        userNotesCount
		        author {
		          avatarUrl
		          name
		          username
		        }
		        createdAt
		        webUrl
		      }
		    }
		  }
		}
		"""
	public let variablesJSON: Data
	public typealias Response = UserReviewRequestedMergeRequestsResponse

	public init() { self.variablesJSON = Data() }
}

// MARK: - MergeRequestCommits

public struct MergeRequestCommitsQuery: GitLabQuery {
	public let operationName = "MergeRequestCommits"
	public let queryString = """
		query MergeRequestCommits($fullPath: ID!, $iid: String!) {
		  project(fullPath: $fullPath) {
		    id
		    mergeRequest(iid: $iid) {
		      commits {
		        nodes {
		          id
		          title
		          shortId
		          authorName
		          authoredDate
		          webUrl
		          signature {
		            verificationStatus
		          }
		          pipelines {
		            nodes {
		              status
		            }
		          }
		        }
		      }
		    }
		  }
		}
		"""
	public let variablesJSON: Data
	public typealias Response = MergeRequestCommitsResponse

	public init(fullPath: String, iid: String) {
		let dict: [String: Any] = ["fullPath": fullPath, "iid": iid]
		self.variablesJSON = (try? JSONSerialization.data(withJSONObject: dict)) ?? Data()
	}
}

// MARK: - MergeRequestDiffs

public struct MergeRequestDiffsQuery: GitLabQuery {
	public let operationName = "MergeRequestDiffs"
	public let queryString = """
		query MergeRequestDiffs($fullPath: ID!, $iid: String!) {
		  project(fullPath: $fullPath) {
		    mergeRequest(iid: $iid) {
		      diffStats {
		        path
		        additions
		        deletions
		      }
		    }
		  }
		}
		"""
	public let variablesJSON: Data
	public typealias Response = MergeRequestDiffsResponse

	public init(fullPath: String, iid: String) {
		let dict: [String: Any] = ["fullPath": fullPath, "iid": iid]
		self.variablesJSON = (try? JSONSerialization.data(withJSONObject: dict)) ?? Data()
	}
}

// MARK: - GroupMilestones

public struct GroupMilestonesQuery: GitLabQuery {
	public let operationName = "GroupMilestones"
	public let queryString = """
		query GroupMilestones($fullPath: ID!, $state: MilestoneStateEnum, $searchTitle: String, $includeAncestors: Boolean) {
		  group(fullPath: $fullPath) {
		    milestones(
		      state: $state
		      searchTitle: $searchTitle
		      includeAncestors: $includeAncestors
		    ) {
		      nodes {
		        id
		        iid
		        state
		        title
		        description
		        expired
		        startDate
		        dueDate
		        stats {
		          closedIssuesCount
		          totalIssuesCount
		        }
		        webPath
		      }
		    }
		  }
		}
		"""
	public let variablesJSON: Data
	public typealias Response = GroupMilestonesResponse

	public init(variablesJSON: Data) { self.variablesJSON = variablesJSON }

	public init(fullPath: String, filter: GroupMilestonesFilter = GroupMilestonesFilter()) {
		var dict = ["fullPath": fullPath] as [String: Any]
		if let filterData = try? JSONEncoder().encode(filter),
		   let filterDict = try? JSONSerialization.jsonObject(with: filterData) as? [String: Any] {
			for (k, v) in filterDict { dict[k] = v }
		}
		self.variablesJSON = (try? JSONSerialization.data(withJSONObject: dict)) ?? Data()
	}

}

// MARK: - ProjectMilestones

public struct ProjectMilestonesQuery: GitLabQuery {
	public let operationName = "ProjectMilestones"
	public let queryString = """
		query ProjectMilestones($fullPath: ID!, $state: MilestoneStateEnum, $searchTitle: String, $includeAncestors: Boolean) {
		  project(fullPath: $fullPath) {
		    milestones(
		      state: $state
		      searchTitle: $searchTitle
		      includeAncestors: $includeAncestors
		    ) {
		      nodes {
		        id
		        iid
		        state
		        title
		        description
		        expired
		        startDate
		        dueDate
		        stats {
		          closedIssuesCount
		          totalIssuesCount
		        }
		        webPath
		      }
		    }
		  }
		}
		"""
	public let variablesJSON: Data
	public typealias Response = ProjectMilestonesResponse

	public init(variablesJSON: Data) { self.variablesJSON = variablesJSON }

	public init(fullPath: String, filter: ProjectMilestonesFilter = ProjectMilestonesFilter()) {
		var dict = ["fullPath": fullPath] as [String: Any]
		if let filterData = try? JSONEncoder().encode(filter),
		   let filterDict = try? JSONSerialization.jsonObject(with: filterData) as? [String: Any] {
			for (k, v) in filterDict { dict[k] = v }
		}
		self.variablesJSON = (try? JSONSerialization.data(withJSONObject: dict)) ?? Data()
	}

}

// MARK: - ProjectPipelines

public struct ProjectPipelinesQuery: GitLabQuery {
	public let operationName = "ProjectPipelines"
	public let queryString = """
		query ProjectPipelines($fullPath: ID!) {
		  project(fullPath: $fullPath) {
		    pipelines {
		      nodes {
		        id
		        iid
		        user {
		          avatarUrl
		          name
		          username
		        }
		        ref
		        commit {
		          shortId
		        }
		        source
		        status
		        cancelable
		        createdAt
		      }
		    }
		  }
		}
		"""
	public let variablesJSON: Data
	public typealias Response = ProjectPipelinesResponse

	public init(fullPath: String) {
		let dict: [String: Any] = ["fullPath": fullPath]
		self.variablesJSON = (try? JSONSerialization.data(withJSONObject: dict)) ?? Data()
	}
}

// MARK: - ProjectReleasesQuery

public struct ProjectReleasesQueryQuery: GitLabQuery {
	public let operationName = "ProjectReleasesQuery"
	public let queryString = """
		query ProjectReleasesQuery($fullPath: ID!) {
		  project(fullPath: $fullPath) {
		    releases {
		      nodes {
		        id
		        name
		        description
		        tagName
		        releasedAt
		
		        author {
		          avatarUrl
		          name
		          username
		        }
		
		        commit {
		          shortId
		        }
		
		        milestones {
		          nodes {
		            id
		            title
		          }
		        }
		
		        assets {
		          count
		          links {
		            nodes {
		              id
		              name
		              url
		            }
		          }
		          sources {
		            nodes {
		              url
		              format
		            }
		          }
		        }
		      }
		    }
		  }
		}
		"""
	public let variablesJSON: Data
	public typealias Response = ProjectReleasesQueryResponse

	public init(fullPath: String) {
		let dict: [String: Any] = ["fullPath": fullPath]
		self.variablesJSON = (try? JSONSerialization.data(withJSONObject: dict)) ?? Data()
	}
}

// MARK: - CurrentUserStarredProjects

public struct CurrentUserStarredProjectsQuery: GitLabQuery {
	public let operationName = "CurrentUserStarredProjects"
	public let queryString = """
		query CurrentUserStarredProjects {
		  currentUser {
		    starredProjects {
		      nodes {
		        avatarUrl
		        nameWithNamespace
		        visibility
		        fullPath
		      }
		    }
		  }
		}
		"""
	public let variablesJSON: Data
	public typealias Response = CurrentUserStarredProjectsResponse

	public init() { self.variablesJSON = Data() }
}

// MARK: - Project

public struct ProjectQuery: GitLabQuery {
	public let operationName = "Project"
	public let queryString = """
		query Project($fullPath: ID!) {
		  project(fullPath: $fullPath) {
		    id
		    avatarUrl
		    name
		    visibility
		    description
		    topics
		    starCount
		    forksCount
		    issuesEnabled
		    openIssuesCount
		    mergeRequestsEnabled
		    jobsEnabled
		    openMergeRequestsCount
		    webUrl
		    httpUrlToRepo
		    sshUrlToRepo
		    createdAt
		    namespace {
		      id
		      name
		      fullPath
		    }
		    repository {
		      rootRef
		      readme: blobs(paths: ["README.md", "README", "README.txt"], first: 1) {
		        nodes {
		          rawTextBlob
		        }
		      }
		      license: blobs(paths: ["LICENSE", "LICENSE.txt", "LICENSE.md", "COPYING"], first: 1) {
		        nodes {
		          rawTextBlob
		        }
		      }
		      contributing: blobs(paths: ["CONTRIBUTING", "CONTRIBUTING.txt", "CONTRIBUTING.md"], first: 1) {
		        nodes {
		          rawTextBlob
		        }
		      }
		      tree {
		        lastCommit {
		          id
		          title
		          shortId
		          authorName
		          authoredDate
		          webUrl
		          signature {
		            verificationStatus
		          }
		          pipelines {
		            nodes {
		              status
		            }
		          }
		        }
		      }
		    }
		    languages {
		      name
		      share
		      color
		    }
		    userPermissions {
		      createIssue
		      forkProject
		      requestAccess
		    }
		  }
		}
		"""
	public let variablesJSON: Data
	public typealias Response = ProjectResponse

	public init(fullPath: String) {
		let dict: [String: Any] = ["fullPath": fullPath]
		self.variablesJSON = (try? JSONSerialization.data(withJSONObject: dict)) ?? Data()
	}
}

// MARK: - Projects

public struct ProjectsQuery: GitLabQuery {
	public let operationName = "Projects"
	public let queryString = """
		query Projects($membership: Boolean, $search: String, $personal: Boolean, $sort: String, $namespacePath: ID, $withIssuesEnabled: Boolean, $withMergeRequestsEnabled: Boolean, $archived: ProjectArchived, $minAccessLevel: AccessLevelEnum, $aimedForDeletion: Boolean, $notAimedForDeletion: Boolean, $markedForDeletionOn: Date, $active: Boolean, $visibility: VisibilityLevelsEnum) {
		  projects(
		    membership: $membership
		    search: $search
		    personal: $personal
		    sort: $sort
		    namespacePath: $namespacePath
		    withIssuesEnabled: $withIssuesEnabled
		    withMergeRequestsEnabled: $withMergeRequestsEnabled
		    archived: $archived
		    minAccessLevel: $minAccessLevel
		    aimedForDeletion: $aimedForDeletion
		    notAimedForDeletion: $notAimedForDeletion
		    markedForDeletionOn: $markedForDeletionOn
		    active: $active
		    visibilityLevel: $visibility
		  ) {
		    nodes {
		      avatarUrl
		      nameWithNamespace
		      visibility
		      fullPath
		    }
		  }
		}
		"""
	public let variablesJSON: Data
	public typealias Response = ProjectsResponse

	public init(variablesJSON: Data) { self.variablesJSON = variablesJSON }

	public init(filter: ProjectsFilter = ProjectsFilter()) {
		self.variablesJSON = (try? JSONEncoder().encode(filter)) ?? Data()
	}

}

// MARK: - StarProject

public struct StarProjectQuery: GitLabQuery {
	public let operationName = "StarProject"
	public let queryString = """
		mutation StarProject($projectId: ProjectID!, $starred: Boolean!) {
			starProject(input: { projectId: $projectId, starred: $starred }) {
				count
			}
		}
		"""
	public let variablesJSON: Data
	public typealias Response = StarProjectResponse

	public init(projectId: String, starred: Bool) {
		let dict: [String: Any] = ["projectId": projectId, "starred": starred]
		self.variablesJSON = (try? JSONSerialization.data(withJSONObject: dict)) ?? Data()
	}
}

// MARK: - UserStarredProjects

public struct UserStarredProjectsQuery: GitLabQuery {
	public let operationName = "UserStarredProjects"
	public let queryString = """
		query UserStarredProjects($username: String!) {
		  user(username:$username) {
		    starredProjects {
		      nodes {
		        avatarUrl
		        nameWithNamespace
		        visibility
		        fullPath
		      }
		    }
		  }
		}
		"""
	public let variablesJSON: Data
	public typealias Response = UserStarredProjectsResponse

	public init(username: String) {
		let dict: [String: Any] = ["username": username]
		self.variablesJSON = (try? JSONSerialization.data(withJSONObject: dict)) ?? Data()
	}
}

// MARK: - RepoTree

public struct RepoTreeQuery: GitLabQuery {
	public let operationName = "RepoTree"
	public let queryString = """
		query RepoTree($fullPath: ID!, $ref: String, $path: String) {
		  project(fullPath: $fullPath) {
		    repository {
		      rootRef
		
		      tree(ref: $ref, path: $path) {
		        blobs {
		          nodes {
		            name
		            path
		          }
		        }
		        trees {
		          nodes {
		            name
		            path
		          }
		        }
		      }
		    }
		  }
		}
		"""
	public let variablesJSON: Data
	public typealias Response = RepoTreeResponse

	public init(variablesJSON: Data) { self.variablesJSON = variablesJSON }

	public init(fullPath: String, filter: RepoTreeFilter = RepoTreeFilter()) {
		var dict = ["fullPath": fullPath] as [String: Any]
		if let filterData = try? JSONEncoder().encode(filter),
		   let filterDict = try? JSONSerialization.jsonObject(with: filterData) as? [String: Any] {
			for (k, v) in filterDict { dict[k] = v }
		}
		self.variablesJSON = (try? JSONSerialization.data(withJSONObject: dict)) ?? Data()
	}

}

// MARK: - CurrentUserSnippets

public struct CurrentUserSnippetsQuery: GitLabQuery {
	public let operationName = "CurrentUserSnippets"
	public let queryString = """
		query CurrentUserSnippets {
		  currentUser {
		    snippets {
		      nodes {
		        id
		        title
		        visibilityLevel
		        author {
		          avatarUrl
		          name
		          username
		        }
		        createdAt
		        webUrl
		      }
		    }
		  }
		}
		"""
	public let variablesJSON: Data
	public typealias Response = CurrentUserSnippetsResponse

	public init() { self.variablesJSON = Data() }
}

// MARK: - Snippet

public struct SnippetQuery: GitLabQuery {
	public let operationName = "Snippet"
	public let queryString = """
		query Snippet($id: SnippetID!) {
		  snippets(ids: [$id]) {
		    nodes {
		      id
		      title
		      description
		      visibilityLevel
		      userPermissions {
		        createNote
		      }
		      author {
		        avatarUrl
		        username
		        name
		      }
		      blobs {
		        nodes {
		          size
		          name
		          rawPlainData
		        }
		      }
		      notes {
		        nodes {
		          id
		          author {
		            avatarUrl
		            name
		            username
		          }
		          maxAccessLevelOfAuthor
		          body
		          system
		          systemNoteIconName
		          createdAt
		          updatedAt
		        }
		      }
		      createdAt
		      sshUrlToRepo
		      httpUrlToRepo
		      webUrl
		    }
		  }
		}
		"""
	public let variablesJSON: Data
	public typealias Response = SnippetResponse

	public init(id: String) {
		let dict: [String: Any] = ["id": id]
		self.variablesJSON = (try? JSONSerialization.data(withJSONObject: dict)) ?? Data()
	}
}

// MARK: - UserSnippets

public struct UserSnippetsQuery: GitLabQuery {
	public let operationName = "UserSnippets"
	public let queryString = """
		query UserSnippets($username: String!) {
		  user(username:$username) {
		    snippets {
		      nodes {
		        id
		        title
		        visibilityLevel
		        author {
		          avatarUrl
		          name
		          username
		        }
		        createdAt
		        webUrl
		      }
		    }
		  }
		}
		"""
	public let variablesJSON: Data
	public typealias Response = UserSnippetsResponse

	public init(username: String) {
		let dict: [String: Any] = ["username": username]
		self.variablesJSON = (try? JSONSerialization.data(withJSONObject: dict)) ?? Data()
	}
}

// MARK: - GroupTimelogs

public struct GroupTimelogsQuery: GitLabQuery {
	public let operationName = "GroupTimelogs"
	public let queryString = """
		query GroupTimelogs($fullPath: ID!) {
		  group(fullPath: $fullPath) {
		    timelogs(sort: SPENT_AT_DESC) {
		      nodes {
		        id
		        user {
		          avatarUrl
		          name
		          username
		        }
		        spentAt
		        summary
		        timeSpent
		        project {
		          fullPath
		          nameWithNamespace
		        }
		        issue {
		          iid
		        }
		        mergeRequest {
		          iid
		        }
		      }
		    }
		  }
		}
		"""
	public let variablesJSON: Data
	public typealias Response = GroupTimelogsResponse

	public init(fullPath: String) {
		let dict: [String: Any] = ["fullPath": fullPath]
		self.variablesJSON = (try? JSONSerialization.data(withJSONObject: dict)) ?? Data()
	}
}

// MARK: - UserTimelogs

public struct UserTimelogsQuery: GitLabQuery {
	public let operationName = "UserTimelogs"
	public let queryString = """
		query UserTimelogs($username: String!) {
		  user(username: $username) {
		    timelogs(sort: SPENT_AT_DESC) {
		      nodes {
		        id
		        user {
		          avatarUrl
		          name
		          username
		        }
		        spentAt
		        summary
		        timeSpent
		        project {
		          fullPath
		          nameWithNamespace
		        }
		        issue {
		          iid
		        }
		        mergeRequest {
		          iid
		        }
		      }
		    }
		  }
		}
		"""
	public let variablesJSON: Data
	public typealias Response = UserTimelogsResponse

	public init(username: String) {
		let dict: [String: Any] = ["username": username]
		self.variablesJSON = (try? JSONSerialization.data(withJSONObject: dict)) ?? Data()
	}
}

// MARK: - CurrentUserTodos

public struct CurrentUserTodosQuery: GitLabQuery {
	public let operationName = "CurrentUserTodos"
	public let queryString = """
		query CurrentUserTodos {
		  currentUser {
		    todos {
		      nodes {
		        id
		        body
		        group {
		          id
		        }
		        state
		        action
		        author {
		          avatarUrl
		          name
		          username
		        }
		        targetEntity {
		          webUrl
		        }
		        project {
		          avatarUrl
		          fullPath
		          nameWithNamespace
		          visibility
		        }
		        createdAt
		        targetType
		      }
		    }
		  }
		}
		"""
	public let variablesJSON: Data
	public typealias Response = CurrentUserTodosResponse

	public init() { self.variablesJSON = Data() }
}

// MARK: - UserTodos

public struct UserTodosQuery: GitLabQuery {
	public let operationName = "UserTodos"
	public let queryString = """
		query UserTodos($username: String!) {
		  user(username: $username) {
		    todos {
		      nodes {
		        id
		        body
		        group {
		          id
		        }
		        state
		        action
		        author {
		          avatarUrl
		          name
		          username
		        }
		        targetEntity {
		          webUrl
		        }
		        project {
		          avatarUrl
		          fullPath
		          nameWithNamespace
		          visibility
		        }
		        createdAt
		        targetType
		      }
		    }
		  }
		}
		"""
	public let variablesJSON: Data
	public typealias Response = UserTodosResponse

	public init(username: String) {
		let dict: [String: Any] = ["username": username]
		self.variablesJSON = (try? JSONSerialization.data(withJSONObject: dict)) ?? Data()
	}
}

// MARK: - CurrentUser

public struct CurrentUserQuery: GitLabQuery {
	public let operationName = "CurrentUser"
	public let queryString = """
		query CurrentUser {
		  currentUser {
		    id
		    avatarUrl
		    name
		    username
		    bot
		    pronouns
		    state
		    status {
		      emoji
		      message
		    }
		
		    bio
		    location
		    jobTitle
		    organization
		    createdAt
		
		    # Contact
		    discord
		    twitter
		    linkedin
		    publicEmail
		
		    groupCount
		
		    webUrl
		  }
		}
		"""
	public let variablesJSON: Data
	public typealias Response = CurrentUserResponse

	public init() { self.variablesJSON = Data() }
}

// MARK: - GroupMembers

public struct GroupMembersQuery: GitLabQuery {
	public let operationName = "GroupMembers"
	public let queryString = """
		query GroupMembers($fullPath: ID!) {
		  group(fullPath: $fullPath) {
		    groupMembers {
		      nodes {
		        id
		        createdBy {
		          avatarUrl
		          name
		          username
		        }
		        createdAt
		        expiresAt
		        accessLevel {
		          stringValue
		        }
		        user {
		          avatarUrl
		          name
		          username
		        }
		      }
		    }
		  }
		}
		"""
	public let variablesJSON: Data
	public typealias Response = GroupMembersResponse

	public init(fullPath: String) {
		let dict: [String: Any] = ["fullPath": fullPath]
		self.variablesJSON = (try? JSONSerialization.data(withJSONObject: dict)) ?? Data()
	}
}

// MARK: - ProjectMembers

public struct ProjectMembersQuery: GitLabQuery {
	public let operationName = "ProjectMembers"
	public let queryString = """
		query ProjectMembers($fullPath: ID!) {
		  project(fullPath:$fullPath) {
		    projectMembers {
		      nodes {
		        id
		        createdBy {
		          avatarUrl
		          name
		          username
		        }
		        createdAt
		        expiresAt
		        accessLevel {
		          stringValue
		        }
		        user {
		          avatarUrl
		          name
		          username
		        }
		      }
		    }
		  }
		}
		"""
	public let variablesJSON: Data
	public typealias Response = ProjectMembersResponse

	public init(fullPath: String) {
		let dict: [String: Any] = ["fullPath": fullPath]
		self.variablesJSON = (try? JSONSerialization.data(withJSONObject: dict)) ?? Data()
	}
}

// MARK: - User

public struct UserQuery: GitLabQuery {
	public let operationName = "User"
	public let queryString = """
		query User($username: String!) {
		  user(username: $username) {
		    id
		    avatarUrl
		    name
		    username
		    bot
		    pronouns
		    state
		    status {
		      emoji
		      message
		    }
		    bio
		    location
		    jobTitle
		    organization
		    createdAt
		    discord
		    twitter
		    linkedin
		    publicEmail
		    groupCount
		    webUrl
		  }
		}
		"""
	public let variablesJSON: Data
	public typealias Response = UserResponse

	public init(username: String) {
		let dict: [String: Any] = ["username": username]
		self.variablesJSON = (try? JSONSerialization.data(withJSONObject: dict)) ?? Data()
	}
}

// MARK: - Users

public struct UsersQuery: GitLabQuery {
	public let operationName = "Users"
	public let queryString = """
		query Users($search: String, $admins: Boolean, $active: Boolean, $humans: Boolean) {
		  users(search: $search, admins: $admins, active: $active, humans: $humans) {
		    nodes {
		      avatarUrl
		      name
		      username
		    }
		  }
		}
		"""
	public let variablesJSON: Data
	public typealias Response = UsersResponse

	public init(variablesJSON: Data) { self.variablesJSON = variablesJSON }

	public init(filter: UsersFilter = UsersFilter()) {
		self.variablesJSON = (try? JSONEncoder().encode(filter)) ?? Data()
	}

}


// MARK: - Response types

public struct EpicResponse: Decodable, Sendable {
	public let group: Epic_Group?
}

public struct Epic_Group: Decodable, Sendable {
	public let id: String?
	public let avatarUrl: String?
	public let epic: Epic_Group_Epic?
}

public struct Epic_Group_Epic_Author: Decodable, Sendable {
	public let avatarUrl: String?
	public let name: String?
	public let username: String?
}

public struct Epic_Group_Epic_Ancestors_Nodes: Decodable, Sendable {
	public let iid: String?
}

public struct Epic_Group_Epic_Ancestors: Decodable, Sendable {
	public let nodes: [Epic_Group_Epic_Ancestors_Nodes]?
}

public struct Epic_Group_Epic_BlockedByEpics_Nodes: Decodable, Sendable {
	public let iid: String?
}

public struct Epic_Group_Epic_BlockedByEpics: Decodable, Sendable {
	public let nodes: [Epic_Group_Epic_BlockedByEpics_Nodes]?
}

public struct Epic_Group_Epic_Children_Nodes: Decodable, Sendable {
	public let iid: String?
}

public struct Epic_Group_Epic_Children: Decodable, Sendable {
	public let nodes: [Epic_Group_Epic_Children_Nodes]?
}

public struct Epic_Group_Epic_UserPermissions: Decodable, Sendable {
	public let updateEpic: String?
	public let createNote: String?
}

public struct Epic_Group_Epic_Labels_Nodes: Decodable, Sendable {
	public let title: String?
	public let color: String?
	public let textColor: String?
}

public struct Epic_Group_Epic_Labels: Decodable, Sendable {
	public let nodes: [Epic_Group_Epic_Labels_Nodes]?
}

public struct Epic_Group_Epic_Notes_Nodes_Author: Decodable, Sendable {
	public let avatarUrl: String?
	public let name: String?
	public let username: String?
}

public struct Epic_Group_Epic_Notes_Nodes: Decodable, Sendable {
	public let id: String?
	public let author: Epic_Group_Epic_Notes_Nodes_Author?
	public let maxAccessLevelOfAuthor: String?
	public let body: String?
	public let system: String?
	public let systemNoteIconName: String?
	public let createdAt: String?
	public let updatedAt: String?
}

public struct Epic_Group_Epic_Notes: Decodable, Sendable {
	public let nodes: [Epic_Group_Epic_Notes_Nodes]?
}

public struct Epic_Group_Epic: Decodable, Sendable {
	public let iid: String?
	public let title: String?
	public let description: String?
	public let reference: String?
	public let state: String?
	public let dueDate: String?
	public let createdAt: String?
	public let webUrl: String?
	public let startDate: String?
	public let color: String?
	public let textColor: String?
	public let upvotes: String?
	public let downvotes: String?
	public let userNotesCount: String?
	public let author: Epic_Group_Epic_Author?
	public let ancestors: Epic_Group_Epic_Ancestors?
	public let blockedByEpics: Epic_Group_Epic_BlockedByEpics?
	public let children: Epic_Group_Epic_Children?
	public let userPermissions: Epic_Group_Epic_UserPermissions?
	public let labels: Epic_Group_Epic_Labels?
	public let notes: Epic_Group_Epic_Notes?
}

public struct GroupEpicsResponse: Decodable, Sendable {
	public let group: GroupEpics_Group?
}

public struct GroupEpics_Group: Decodable, Sendable {
	public let epics: GroupEpics_Group_Epics?
}

public struct GroupEpics_Group_Epics_Nodes_Author: Decodable, Sendable {
	public let avatarUrl: String?
	public let name: String?
	public let username: String?
}

public struct GroupEpics_Group_Epics_Nodes: Decodable, Sendable {
	public let iid: String?
	public let title: String?
	public let reference: String?
	public let state: String?
	public let upvotes: String?
	public let downvotes: String?
	public let userNotesCount: String?
	public let author: GroupEpics_Group_Epics_Nodes_Author?
	public let createdAt: String?
	public let webUrl: String?
}

public struct GroupEpics_Group_Epics: Decodable, Sendable {
	public let nodes: [GroupEpics_Group_Epics_Nodes]?
}

public struct GroupCustomEmojiResponse: Decodable, Sendable {
	public let group: GroupCustomEmoji_Group?
}

public struct GroupCustomEmoji_Group: Decodable, Sendable {
	public let customEmoji: GroupCustomEmoji_Group_CustomEmoji?
}

public struct GroupCustomEmoji_Group_CustomEmoji_Nodes: Decodable, Sendable {
	public let id: String?
	public let url: String?
	public let name: String?
	public let createdAt: String?
}

public struct GroupCustomEmoji_Group_CustomEmoji: Decodable, Sendable {
	public let nodes: [GroupCustomEmoji_Group_CustomEmoji_Nodes]?
}

public struct GroupResponse: Decodable, Sendable {
	public let group: Group_Group?
}

public struct Group_Group: Decodable, Sendable {
	public let id: String?
	public let avatarUrl: String?
	public let name: String?
	public let path: String?
	public let fullName: String?
	public let visibility: String?
	public let description: String?
	public let descendantGroupsCount: String?
	public let groupMembersCount: String?
	public let projectsCount: String?
	public let requestAccessEnabled: String?
	public let webUrl: String?
	public let maxAccessLevel: Group_Group_MaxAccessLevel?
	public let userPermissions: Group_Group_UserPermissions?
	public let parent: Group_Group_Parent?
}

public struct Group_Group_MaxAccessLevel: Decodable, Sendable {
	public let stringValue: String?
}

public struct Group_Group_UserPermissions: Decodable, Sendable {
	public let createProjects: String?
}

public struct Group_Group_Parent: Decodable, Sendable {
	public let name: String?
	public let fullPath: String?
}

public struct GroupsResponse: Decodable, Sendable {
	public let groups: Groups_Groups?
}

public struct Groups_Groups: Decodable, Sendable {
	public let nodes: [GroupStruct]?
}

public struct UserGroupsResponse: Decodable, Sendable {
	public let user: UserGroups_User?
}

public struct UserGroups_User: Decodable, Sendable {
	public let groups: UserGroups_Groups?
}

public struct UserGroups_Groups: Decodable, Sendable {
	public let nodes: [GroupStruct]?
}

public struct CurrentUserIssuesResponse: Decodable, Sendable {
	public let currentUser: CurrentUserIssues_CurrentUser?
}

public struct CurrentUserIssues_CurrentUser: Decodable, Sendable {
	public let projectMemberships: CurrentUserIssues_CurrentUser_ProjectMemberships?
}

public struct CurrentUserIssues_CurrentUser_ProjectMemberships_Nodes_Project_Issues_Nodes_Author: Decodable, Sendable {
	public let avatarUrl: String?
	public let name: String?
	public let username: String?
}

public struct CurrentUserIssues_CurrentUser_ProjectMemberships_Nodes_Project_Issues_Nodes: Decodable, Sendable {
	public let iid: String?
	public let title: String?
	public let reference: String?
	public let state: String?
	public let upvotes: String?
	public let downvotes: String?
	public let userNotesCount: String?
	public let author: CurrentUserIssues_CurrentUser_ProjectMemberships_Nodes_Project_Issues_Nodes_Author?
	public let createdAt: String?
	public let webUrl: String?
}

public struct CurrentUserIssues_CurrentUser_ProjectMemberships_Nodes_Project_Issues: Decodable, Sendable {
	public let nodes: [CurrentUserIssues_CurrentUser_ProjectMemberships_Nodes_Project_Issues_Nodes]?
}

public struct CurrentUserIssues_CurrentUser_ProjectMemberships_Nodes_Project: Decodable, Sendable {
	public let fullPath: String?
	public let issues: CurrentUserIssues_CurrentUser_ProjectMemberships_Nodes_Project_Issues?
}

public struct CurrentUserIssues_CurrentUser_ProjectMemberships_Nodes: Decodable, Sendable {
	public let project: CurrentUserIssues_CurrentUser_ProjectMemberships_Nodes_Project?
}

public struct CurrentUserIssues_CurrentUser_ProjectMemberships: Decodable, Sendable {
	public let nodes: [CurrentUserIssues_CurrentUser_ProjectMemberships_Nodes]?
}

public struct EpicIssuesResponse: Decodable, Sendable {
	public let group: EpicIssues_Group?
}

public struct EpicIssues_Group: Decodable, Sendable {
	public let epic: EpicIssues_Group_Epic?
}

public struct EpicIssues_Group_Epic_Issues_Nodes_Author: Decodable, Sendable {
	public let avatarUrl: String?
	public let name: String?
	public let username: String?
}

public struct EpicIssues_Group_Epic_Issues_Nodes: Decodable, Sendable {
	public let iid: String?
	public let title: String?
	public let reference: String?
	public let state: String?
	public let upvotes: String?
	public let downvotes: String?
	public let userNotesCount: String?
	public let author: EpicIssues_Group_Epic_Issues_Nodes_Author?
	public let createdAt: String?
	public let webUrl: String?
}

public struct EpicIssues_Group_Epic_Issues: Decodable, Sendable {
	public let nodes: [EpicIssues_Group_Epic_Issues_Nodes]?
}

public struct EpicIssues_Group_Epic: Decodable, Sendable {
	public let issues: EpicIssues_Group_Epic_Issues?
}

public struct GroupIssuesResponse: Decodable, Sendable {
	public let group: GroupIssues_Group?
}

public struct GroupIssues_Group: Decodable, Sendable {
	public let issues: GroupIssues_Issues?
}

public struct GroupIssues_Issues: Decodable, Sendable {
	public let nodes: [SmallIssueStruct]?
}

public struct IssueResponse: Decodable, Sendable {
	public let project: Issue_Project?
}

public struct Issue_Project: Decodable, Sendable {
	public let id: String?
	public let avatarUrl: String?
	public let issue: Issue_Project_Issue?
}

public struct Issue_Project_Issue_BlockedByIssues_Nodes: Decodable, Sendable {
	public let iid: String?
}

public struct Issue_Project_Issue_BlockedByIssues: Decodable, Sendable {
	public let nodes: [Issue_Project_Issue_BlockedByIssues_Nodes]?
}

public struct Issue_Project_Issue_Author: Decodable, Sendable {
	public let avatarUrl: String?
	public let name: String?
	public let username: String?
}

public struct Issue_Project_Issue_UserPermissions: Decodable, Sendable {
	public let updateIssue: String?
	public let createNote: String?
}

public struct Issue_Project_Issue_Assignees_Nodes: Decodable, Sendable {
	public let avatarUrl: String?
	public let username: String?
}

public struct Issue_Project_Issue_Assignees: Decodable, Sendable {
	public let nodes: [Issue_Project_Issue_Assignees_Nodes]?
}

public struct Issue_Project_Issue_Labels_Nodes: Decodable, Sendable {
	public let title: String?
	public let color: String?
	public let textColor: String?
}

public struct Issue_Project_Issue_Labels: Decodable, Sendable {
	public let nodes: [Issue_Project_Issue_Labels_Nodes]?
}

public struct Issue_Project_Issue_Milestone: Decodable, Sendable {
	public let iid: String?
	public let title: String?
}

public struct Issue_Project_Issue_Notes_Nodes_Author: Decodable, Sendable {
	public let avatarUrl: String?
	public let name: String?
	public let username: String?
}

public struct Issue_Project_Issue_Notes_Nodes: Decodable, Sendable {
	public let id: String?
	public let author: Issue_Project_Issue_Notes_Nodes_Author?
	public let maxAccessLevelOfAuthor: String?
	public let body: String?
	public let system: String?
	public let systemNoteIconName: String?
	public let createdAt: String?
	public let updatedAt: String?
}

public struct Issue_Project_Issue_Notes: Decodable, Sendable {
	public let nodes: [Issue_Project_Issue_Notes_Nodes]?
}

public struct Issue_Project_Issue: Decodable, Sendable {
	public let iid: String?
	public let title: String?
	public let description: String?
	public let reference: String?
	public let state: String?
	public let weight: String?
	public let dueDate: String?
	public let blockedByIssues: Issue_Project_Issue_BlockedByIssues?
	public let createdAt: String?
	public let webUrl: String?
	public let upvotes: String?
	public let downvotes: String?
	public let userNotesCount: String?
	public let author: Issue_Project_Issue_Author?
	public let userPermissions: Issue_Project_Issue_UserPermissions?
	public let assignees: Issue_Project_Issue_Assignees?
	public let labels: Issue_Project_Issue_Labels?
	public let milestone: Issue_Project_Issue_Milestone?
	public let humanTimeEstimate: String?
	public let humanTotalTimeSpent: String?
	public let notes: Issue_Project_Issue_Notes?
}

public struct IssueStateResponse: Decodable, Sendable {
	public let updateIssue: IssueState_UpdateIssue?
}

public struct IssueState_UpdateIssue: Decodable, Sendable {
	public let issue: IssueState_UpdateIssue_Issue?
	public let errors: String?
}

public struct IssueState_UpdateIssue_Issue: Decodable, Sendable {
	public let id: String?
	public let iid: String?
	public let title: String?
	public let state: String?
	public let webUrl: String?
}

public struct ProjectIssuesResponse: Decodable, Sendable {
	public let project: ProjectIssues_Project?
}

public struct ProjectIssues_Project: Decodable, Sendable {
	public let issues: ProjectIssues_Issues?
}

public struct ProjectIssues_Issues: Decodable, Sendable {
	public let nodes: [SmallIssueStruct]?
}

public struct UserIssuesResponse: Decodable, Sendable {
	public let user: UserIssues_User?
}

public struct UserIssues_User: Decodable, Sendable {
	public let projectMemberships: UserIssues_User_ProjectMemberships?
}

public struct UserIssues_User_ProjectMemberships_Nodes_Project_Issues_Nodes_Author: Decodable, Sendable {
	public let avatarUrl: String?
	public let name: String?
	public let username: String?
}

public struct UserIssues_User_ProjectMemberships_Nodes_Project_Issues_Nodes: Decodable, Sendable {
	public let iid: String?
	public let title: String?
	public let reference: String?
	public let state: String?
	public let upvotes: String?
	public let downvotes: String?
	public let userNotesCount: String?
	public let author: UserIssues_User_ProjectMemberships_Nodes_Project_Issues_Nodes_Author?
	public let createdAt: String?
	public let webUrl: String?
}

public struct UserIssues_User_ProjectMemberships_Nodes_Project_Issues: Decodable, Sendable {
	public let nodes: [UserIssues_User_ProjectMemberships_Nodes_Project_Issues_Nodes]?
}

public struct UserIssues_User_ProjectMemberships_Nodes_Project: Decodable, Sendable {
	public let fullPath: String?
	public let issues: UserIssues_User_ProjectMemberships_Nodes_Project_Issues?
}

public struct UserIssues_User_ProjectMemberships_Nodes: Decodable, Sendable {
	public let project: UserIssues_User_ProjectMemberships_Nodes_Project?
}

public struct UserIssues_User_ProjectMemberships: Decodable, Sendable {
	public let nodes: [UserIssues_User_ProjectMemberships_Nodes]?
}

public struct GroupLabelsResponse: Decodable, Sendable {
	public let group: GroupLabels_Group?
}

public struct GroupLabels_Group: Decodable, Sendable {
	public let labels: GroupLabels_Labels?
}

public struct GroupLabels_Labels: Decodable, Sendable {
	public let nodes: [MyLabelStruct]?
}

public struct ProjectLabelsResponse: Decodable, Sendable {
	public let project: ProjectLabels_Project?
}

public struct ProjectLabels_Project: Decodable, Sendable {
	public let labels: ProjectLabels_Labels?
}

public struct ProjectLabels_Labels: Decodable, Sendable {
	public let nodes: [MyLabelStruct]?
}

public struct GroupMergeRequestsResponse: Decodable, Sendable {
	public let group: GroupMergeRequests_Group?
}

public struct GroupMergeRequests_Group: Decodable, Sendable {
	public let mergeRequests: GroupMergeRequests_MergeRequests?
}

public struct GroupMergeRequests_MergeRequests: Decodable, Sendable {
	public let nodes: [SmallMergeRequestStruct]?
}

public struct MergeRequestResponse: Decodable, Sendable {
	public let project: MergeRequest_Project?
}

public struct MergeRequest_Project: Decodable, Sendable {
	public let id: String?
	public let avatarUrl: String?
	public let mergeRequest: MergeRequest_Project_MergeRequest?
}

public struct MergeRequest_Project_MergeRequest_SourceProject: Decodable, Sendable {
	public let fullPath: String?
}

public struct MergeRequest_Project_MergeRequest_DiffStatsSummary: Decodable, Sendable {
	public let additions: String?
	public let deletions: String?
	public let fileCount: String?
}

public struct MergeRequest_Project_MergeRequest_Author: Decodable, Sendable {
	public let avatarUrl: String?
	public let name: String?
	public let username: String?
}

public struct MergeRequest_Project_MergeRequest_UserPermissions: Decodable, Sendable {
	public let canApprove: String?
	public let canMerge: String?
	public let updateMergeRequest: String?
	public let createNote: String?
}

public struct MergeRequest_Project_MergeRequest_Assignees_Nodes: Decodable, Sendable {
	public let avatarUrl: String?
	public let username: String?
}

public struct MergeRequest_Project_MergeRequest_Assignees: Decodable, Sendable {
	public let nodes: [MergeRequest_Project_MergeRequest_Assignees_Nodes]?
}

public struct MergeRequest_Project_MergeRequest_Reviewers_Nodes: Decodable, Sendable {
	public let avatarUrl: String?
	public let username: String?
}

public struct MergeRequest_Project_MergeRequest_Reviewers: Decodable, Sendable {
	public let nodes: [MergeRequest_Project_MergeRequest_Reviewers_Nodes]?
}

public struct MergeRequest_Project_MergeRequest_Labels_Nodes: Decodable, Sendable {
	public let title: String?
	public let color: String?
	public let textColor: String?
}

public struct MergeRequest_Project_MergeRequest_Labels: Decodable, Sendable {
	public let nodes: [MergeRequest_Project_MergeRequest_Labels_Nodes]?
}

public struct MergeRequest_Project_MergeRequest_Milestone: Decodable, Sendable {
	public let iid: String?
	public let title: String?
}

public struct MergeRequest_Project_MergeRequest_Notes_Nodes_Author: Decodable, Sendable {
	public let avatarUrl: String?
	public let name: String?
	public let username: String?
}

public struct MergeRequest_Project_MergeRequest_Notes_Nodes: Decodable, Sendable {
	public let id: String?
	public let author: MergeRequest_Project_MergeRequest_Notes_Nodes_Author?
	public let maxAccessLevelOfAuthor: String?
	public let body: String?
	public let system: String?
	public let systemNoteIconName: String?
	public let createdAt: String?
	public let updatedAt: String?
}

public struct MergeRequest_Project_MergeRequest_Notes: Decodable, Sendable {
	public let nodes: [MergeRequest_Project_MergeRequest_Notes_Nodes]?
}

public struct MergeRequest_Project_MergeRequest: Decodable, Sendable {
	public let iid: String?
	public let title: String?
	public let description: String?
	public let reference: String?
	public let state: String?
	public let sourceBranch: String?
	public let targetBranch: String?
	public let sourceProject: MergeRequest_Project_MergeRequest_SourceProject?
	public let diffStatsSummary: MergeRequest_Project_MergeRequest_DiffStatsSummary?
	public let upvotes: String?
	public let downvotes: String?
	public let userNotesCount: String?
	public let author: MergeRequest_Project_MergeRequest_Author?
	public let userPermissions: MergeRequest_Project_MergeRequest_UserPermissions?
	public let createdAt: String?
	public let webUrl: String?
	public let approved: String?
	public let mergeStatusEnum: String?
	public let conflicts: String?
	public let detailedMergeStatus: String?
	public let assignees: MergeRequest_Project_MergeRequest_Assignees?
	public let reviewers: MergeRequest_Project_MergeRequest_Reviewers?
	public let labels: MergeRequest_Project_MergeRequest_Labels?
	public let milestone: MergeRequest_Project_MergeRequest_Milestone?
	public let humanTimeEstimate: String?
	public let humanTotalTimeSpent: String?
	public let notes: MergeRequest_Project_MergeRequest_Notes?
}

public struct ProjectMergeRequestsResponse: Decodable, Sendable {
	public let project: ProjectMergeRequests_Project?
}

public struct ProjectMergeRequests_Project: Decodable, Sendable {
	public let mergeRequests: ProjectMergeRequests_MergeRequests?
}

public struct ProjectMergeRequests_MergeRequests: Decodable, Sendable {
	public let nodes: [SmallMergeRequestStruct]?
}

public struct UserAssignedMergeRequestsResponse: Decodable, Sendable {
	public let currentUser: UserAssignedMergeRequests_CurrentUser?
}

public struct UserAssignedMergeRequests_CurrentUser: Decodable, Sendable {
	public let assignedMergeRequests: UserAssignedMergeRequests_AssignedMergeRequests?
}

public struct UserAssignedMergeRequests_AssignedMergeRequests: Decodable, Sendable {
	public let nodes: [UserSmallMergeRequestStruct]?
}

public struct UserAuthoredMergeRequestsResponse: Decodable, Sendable {
	public let currentUser: UserAuthoredMergeRequests_CurrentUser?
}

public struct UserAuthoredMergeRequests_CurrentUser: Decodable, Sendable {
	public let authoredMergeRequests: UserAuthoredMergeRequests_AuthoredMergeRequests?
}

public struct UserAuthoredMergeRequests_AuthoredMergeRequests: Decodable, Sendable {
	public let nodes: [UserSmallMergeRequestStruct]?
}

public struct UserReviewRequestedMergeRequestsResponse: Decodable, Sendable {
	public let currentUser: UserReviewRequestedMergeRequests_CurrentUser?
}

public struct UserReviewRequestedMergeRequests_CurrentUser: Decodable, Sendable {
	public let reviewRequestedMergeRequests: UserReviewRequestedMergeRequests_ReviewRequestedMergeRequests?
}

public struct UserReviewRequestedMergeRequests_ReviewRequestedMergeRequests: Decodable, Sendable {
	public let nodes: [UserSmallMergeRequestStruct]?
}

public struct MergeRequestCommitsResponse: Decodable, Sendable {
	public let project: MergeRequestCommits_Project?
}

public struct MergeRequestCommits_Project: Decodable, Sendable {
	public let id: String?
	public let mergeRequest: MergeRequestCommits_Project_MergeRequest?
}

public struct MergeRequestCommits_Project_MergeRequest_Commits_Nodes_Signature: Decodable, Sendable {
	public let verificationStatus: String?
}

public struct MergeRequestCommits_Project_MergeRequest_Commits_Nodes_Pipelines_Nodes: Decodable, Sendable {
	public let status: String?
}

public struct MergeRequestCommits_Project_MergeRequest_Commits_Nodes_Pipelines: Decodable, Sendable {
	public let nodes: MergeRequestCommits_Project_MergeRequest_Commits_Nodes_Pipelines_Nodes?
}

public struct MergeRequestCommits_Project_MergeRequest_Commits_Nodes: Decodable, Sendable {
	public let id: String?
	public let title: String?
	public let shortId: String?
	public let authorName: String?
	public let authoredDate: String?
	public let webUrl: String?
	public let signature: MergeRequestCommits_Project_MergeRequest_Commits_Nodes_Signature?
	public let pipelines: MergeRequestCommits_Project_MergeRequest_Commits_Nodes_Pipelines?
}

public struct MergeRequestCommits_Project_MergeRequest_Commits: Decodable, Sendable {
	public let nodes: [MergeRequestCommits_Project_MergeRequest_Commits_Nodes]?
}

public struct MergeRequestCommits_Project_MergeRequest: Decodable, Sendable {
	public let commits: MergeRequestCommits_Project_MergeRequest_Commits?
}

public struct MergeRequestDiffsResponse: Decodable, Sendable {
	public let project: MergeRequestDiffs_Project?
}

public struct MergeRequestDiffs_Project: Decodable, Sendable {
	public let mergeRequest: MergeRequestDiffs_Project_MergeRequest?
}

public struct MergeRequestDiffs_Project_MergeRequest_DiffStats: Decodable, Sendable {
	public let path: String?
	public let additions: String?
	public let deletions: String?
}

public struct MergeRequestDiffs_Project_MergeRequest: Decodable, Sendable {
	public let diffStats: MergeRequestDiffs_Project_MergeRequest_DiffStats?
}

public struct GroupMilestonesResponse: Decodable, Sendable {
	public let group: GroupMilestones_Group?
}

public struct GroupMilestones_Group: Decodable, Sendable {
	public let milestones: GroupMilestones_Milestones?
}

public struct GroupMilestones_Milestones: Decodable, Sendable {
	public let nodes: [MilestoneStruct]?
}

public struct ProjectMilestonesResponse: Decodable, Sendable {
	public let project: ProjectMilestones_Project?
}

public struct ProjectMilestones_Project: Decodable, Sendable {
	public let milestones: ProjectMilestones_Milestones?
}

public struct ProjectMilestones_Milestones: Decodable, Sendable {
	public let nodes: [MilestoneStruct]?
}

public struct ProjectPipelinesResponse: Decodable, Sendable {
	public let project: ProjectPipelines_Project?
}

public struct ProjectPipelines_Project: Decodable, Sendable {
	public let pipelines: ProjectPipelines_Project_Pipelines?
}

public struct ProjectPipelines_Project_Pipelines_Nodes_User: Decodable, Sendable {
	public let avatarUrl: String?
	public let name: String?
	public let username: String?
}

public struct ProjectPipelines_Project_Pipelines_Nodes_Commit: Decodable, Sendable {
	public let shortId: String?
}

public struct ProjectPipelines_Project_Pipelines_Nodes: Decodable, Sendable {
	public let id: String?
	public let iid: String?
	public let user: ProjectPipelines_Project_Pipelines_Nodes_User?
	public let ref: String?
	public let commit: ProjectPipelines_Project_Pipelines_Nodes_Commit?
	public let source: String?
	public let status: String?
	public let cancelable: String?
	public let createdAt: String?
}

public struct ProjectPipelines_Project_Pipelines: Decodable, Sendable {
	public let nodes: [ProjectPipelines_Project_Pipelines_Nodes]?
}

public struct ProjectReleasesQueryResponse: Decodable, Sendable {
	public let project: ProjectReleasesQuery_Project?
}

public struct ProjectReleasesQuery_Project: Decodable, Sendable {
	public let releases: ProjectReleasesQuery_Releases?
}

public struct ProjectReleasesQuery_Releases: Decodable, Sendable {
	public let nodes: [ReleaseStruct]?
}

public struct CurrentUserStarredProjectsResponse: Decodable, Sendable {
	public let currentUser: CurrentUserStarredProjects_CurrentUser?
}

public struct CurrentUserStarredProjects_CurrentUser: Decodable, Sendable {
	public let starredProjects: CurrentUserStarredProjects_StarredProjects?
}

public struct CurrentUserStarredProjects_StarredProjects: Decodable, Sendable {
	public let nodes: [SmallProjectStruct]?
}

public struct ProjectResponse: Decodable, Sendable {
	public let project: Project_Project?
}

public struct Project_Project: Decodable, Sendable {
	public let id: String?
	public let avatarUrl: String?
	public let name: String?
	public let visibility: String?
	public let description: String?
	public let topics: String?
	public let starCount: String?
	public let forksCount: String?
	public let issuesEnabled: String?
	public let openIssuesCount: String?
	public let mergeRequestsEnabled: String?
	public let jobsEnabled: String?
	public let openMergeRequestsCount: String?
	public let webUrl: String?
	public let httpUrlToRepo: String?
	public let sshUrlToRepo: String?
	public let createdAt: String?
	public let namespace: Project_Project_Namespace?
	public let repository: Project_Project_Repository?
	public let languages: Project_Project_Languages?
	public let userPermissions: Project_Project_UserPermissions?
}

public struct Project_Project_Namespace: Decodable, Sendable {
	public let id: String?
	public let name: String?
	public let fullPath: String?
}

public struct Project_Project_Repository_Readme_Nodes: Decodable, Sendable {
	public let rawTextBlob: String?
}

public struct Project_Project_Repository_Readme: Decodable, Sendable {
	public let nodes: [Project_Project_Repository_Readme_Nodes]?
}

public struct Project_Project_Repository_License_Nodes: Decodable, Sendable {
	public let rawTextBlob: String?
}

public struct Project_Project_Repository_License: Decodable, Sendable {
	public let nodes: [Project_Project_Repository_License_Nodes]?
}

public struct Project_Project_Repository_Contributing_Nodes: Decodable, Sendable {
	public let rawTextBlob: String?
}

public struct Project_Project_Repository_Contributing: Decodable, Sendable {
	public let nodes: [Project_Project_Repository_Contributing_Nodes]?
}

public struct Project_Project_Repository_Tree_LastCommit_Signature: Decodable, Sendable {
	public let verificationStatus: String?
}

public struct Project_Project_Repository_Tree_LastCommit_Pipelines_Nodes: Decodable, Sendable {
	public let status: String?
}

public struct Project_Project_Repository_Tree_LastCommit_Pipelines: Decodable, Sendable {
	public let nodes: [Project_Project_Repository_Tree_LastCommit_Pipelines_Nodes]?
}

public struct Project_Project_Repository_Tree_LastCommit: Decodable, Sendable {
	public let id: String?
	public let title: String?
	public let shortId: String?
	public let authorName: String?
	public let authoredDate: String?
	public let webUrl: String?
	public let signature: Project_Project_Repository_Tree_LastCommit_Signature?
	public let pipelines: Project_Project_Repository_Tree_LastCommit_Pipelines?
}

public struct Project_Project_Repository_Tree: Decodable, Sendable {
	public let lastCommit: Project_Project_Repository_Tree_LastCommit?
}

public struct Project_Project_Repository: Decodable, Sendable {
	public let rootRef: String?
	public let readme: Project_Project_Repository_Readme?
	public let license: Project_Project_Repository_License?
	public let contributing: Project_Project_Repository_Contributing?
	public let tree: Project_Project_Repository_Tree?
}

public struct Project_Project_Languages: Decodable, Sendable {
	public let name: String?
	public let share: String?
	public let color: String?
}

public struct Project_Project_UserPermissions: Decodable, Sendable {
	public let createIssue: String?
	public let forkProject: String?
	public let requestAccess: String?
}

public struct ProjectsResponse: Decodable, Sendable {
	public let projects: Projects_Projects?
}

public struct Projects_Projects: Decodable, Sendable {
	public let nodes: [SmallProjectStruct]?
}

public struct StarProjectResponse: Decodable, Sendable {
	public let starProject: StarProject_StarProject?
}

public struct StarProject_StarProject: Decodable, Sendable {
	public let count: String?
}

public struct UserStarredProjectsResponse: Decodable, Sendable {
	public let user: UserStarredProjects_User?
}

public struct UserStarredProjects_User: Decodable, Sendable {
	public let starredProjects: UserStarredProjects_StarredProjects?
}

public struct UserStarredProjects_StarredProjects: Decodable, Sendable {
	public let nodes: [SmallProjectStruct]?
}

public struct RepoTreeResponse: Decodable, Sendable {
	public let project: RepoTree_Project?
}

public struct RepoTree_Project: Decodable, Sendable {
	public let repository: RepoTree_Project_Repository?
}

public struct RepoTree_Project_Repository_Tree_Blobs_Nodes: Decodable, Sendable {
	public let name: String?
	public let path: String?
}

public struct RepoTree_Project_Repository_Tree_Blobs: Decodable, Sendable {
	public let nodes: [RepoTree_Project_Repository_Tree_Blobs_Nodes]?
}

public struct RepoTree_Project_Repository_Tree_Trees_Nodes: Decodable, Sendable {
	public let name: String?
	public let path: String?
}

public struct RepoTree_Project_Repository_Tree_Trees: Decodable, Sendable {
	public let nodes: [RepoTree_Project_Repository_Tree_Trees_Nodes]?
}

public struct RepoTree_Project_Repository_Tree: Decodable, Sendable {
	public let blobs: RepoTree_Project_Repository_Tree_Blobs?
	public let trees: RepoTree_Project_Repository_Tree_Trees?
}

public struct RepoTree_Project_Repository: Decodable, Sendable {
	public let rootRef: String?
	public let tree: RepoTree_Project_Repository_Tree?
}

public struct CurrentUserSnippetsResponse: Decodable, Sendable {
	public let currentUser: CurrentUserSnippets_CurrentUser?
}

public struct CurrentUserSnippets_CurrentUser: Decodable, Sendable {
	public let snippets: CurrentUserSnippets_Snippets?
}

public struct CurrentUserSnippets_Snippets: Decodable, Sendable {
	public let nodes: [SnippetStruct]?
}

public struct SnippetResponse: Decodable, Sendable {
	public let snippets: Snippet_Snippets?
}

public struct Snippet_Snippets: Decodable, Sendable {
	public let nodes: [SnippetStruct]?
}

public struct UserSnippetsResponse: Decodable, Sendable {
	public let user: UserSnippets_User?
}

public struct UserSnippets_User: Decodable, Sendable {
	public let snippets: UserSnippets_Snippets?
}

public struct UserSnippets_Snippets: Decodable, Sendable {
	public let nodes: [SnippetStruct]?
}

public struct GroupTimelogsResponse: Decodable, Sendable {
	public let group: GroupTimelogs_Group?
}

public struct GroupTimelogs_Group: Decodable, Sendable {
	public let timelogs: GroupTimelogs_Timelogs?
}

public struct GroupTimelogs_Timelogs: Decodable, Sendable {
	public let nodes: [TimelogStruct]?
}

public struct UserTimelogsResponse: Decodable, Sendable {
	public let user: UserTimelogs_User?
}

public struct UserTimelogs_User: Decodable, Sendable {
	public let timelogs: UserTimelogs_Timelogs?
}

public struct UserTimelogs_Timelogs: Decodable, Sendable {
	public let nodes: [TimelogStruct]?
}

public struct CurrentUserTodosResponse: Decodable, Sendable {
	public let currentUser: CurrentUserTodos_CurrentUser?
}

public struct CurrentUserTodos_CurrentUser: Decodable, Sendable {
	public let todos: CurrentUserTodos_Todos?
}

public struct CurrentUserTodos_Todos: Decodable, Sendable {
	public let nodes: [TodoStruct]?
}

public struct UserTodosResponse: Decodable, Sendable {
	public let user: UserTodos_User?
}

public struct UserTodos_User: Decodable, Sendable {
	public let todos: UserTodos_Todos?
}

public struct UserTodos_Todos: Decodable, Sendable {
	public let nodes: [TodoStruct]?
}

public struct CurrentUserResponse: Decodable, Sendable {
	public let currentUser: CurrentUser_CurrentUser?
}

public struct CurrentUser_CurrentUser: Decodable, Sendable {
	public let id: String?
	public let avatarUrl: String?
	public let name: String?
	public let username: String?
	public let bot: String?
	public let pronouns: String?
	public let state: String?
	public let status: CurrentUser_CurrentUser_Status?
	public let bio: String?
	public let location: String?
	public let jobTitle: String?
	public let organization: String?
	public let createdAt: String?
}

public struct CurrentUser_CurrentUser_Status: Decodable, Sendable {
	public let emoji: String?
	public let message: String?
}

public struct GroupMembersResponse: Decodable, Sendable {
	public let group: GroupMembers_Group?
}

public struct GroupMembers_Group: Decodable, Sendable {
	public let groupMembers: GroupMembers_Group_GroupMembers?
}

public struct GroupMembers_Group_GroupMembers_Nodes_CreatedBy: Decodable, Sendable {
	public let avatarUrl: String?
	public let name: String?
	public let username: String?
}

public struct GroupMembers_Group_GroupMembers_Nodes_AccessLevel: Decodable, Sendable {
	public let stringValue: String?
}

public struct GroupMembers_Group_GroupMembers_Nodes_User: Decodable, Sendable {
	public let avatarUrl: String?
	public let name: String?
	public let username: String?
}

public struct GroupMembers_Group_GroupMembers_Nodes: Decodable, Sendable {
	public let id: String?
	public let createdBy: GroupMembers_Group_GroupMembers_Nodes_CreatedBy?
	public let createdAt: String?
	public let expiresAt: String?
	public let accessLevel: GroupMembers_Group_GroupMembers_Nodes_AccessLevel?
	public let user: GroupMembers_Group_GroupMembers_Nodes_User?
}

public struct GroupMembers_Group_GroupMembers: Decodable, Sendable {
	public let nodes: [GroupMembers_Group_GroupMembers_Nodes]?
}

public struct ProjectMembersResponse: Decodable, Sendable {
	public let project: ProjectMembers_Project?
}

public struct ProjectMembers_Project: Decodable, Sendable {
	public let projectMembers: ProjectMembers_Project_ProjectMembers?
}

public struct ProjectMembers_Project_ProjectMembers_Nodes_CreatedBy: Decodable, Sendable {
	public let avatarUrl: String?
	public let name: String?
	public let username: String?
}

public struct ProjectMembers_Project_ProjectMembers_Nodes_AccessLevel: Decodable, Sendable {
	public let stringValue: String?
}

public struct ProjectMembers_Project_ProjectMembers_Nodes_User: Decodable, Sendable {
	public let avatarUrl: String?
	public let name: String?
	public let username: String?
}

public struct ProjectMembers_Project_ProjectMembers_Nodes: Decodable, Sendable {
	public let id: String?
	public let createdBy: ProjectMembers_Project_ProjectMembers_Nodes_CreatedBy?
	public let createdAt: String?
	public let expiresAt: String?
	public let accessLevel: ProjectMembers_Project_ProjectMembers_Nodes_AccessLevel?
	public let user: ProjectMembers_Project_ProjectMembers_Nodes_User?
}

public struct ProjectMembers_Project_ProjectMembers: Decodable, Sendable {
	public let nodes: [ProjectMembers_Project_ProjectMembers_Nodes]?
}

public struct UserResponse: Decodable, Sendable {
	public let user: User_User?
}

public struct User_User: Decodable, Sendable {
	public let id: String?
	public let avatarUrl: String?
	public let name: String?
	public let username: String?
	public let bot: String?
	public let pronouns: String?
	public let state: String?
	public let status: User_User_Status?
	public let bio: String?
	public let location: String?
	public let jobTitle: String?
	public let organization: String?
	public let createdAt: String?
	public let discord: String?
	public let twitter: String?
	public let linkedin: String?
	public let publicEmail: String?
	public let groupCount: String?
	public let webUrl: String?
}

public struct User_User_Status: Decodable, Sendable {
	public let emoji: String?
	public let message: String?
}

public struct UsersResponse: Decodable, Sendable {
	public let users: Users_Users?
}

public struct Users_Users: Decodable, Sendable {
	public let nodes: [MyAuthor]?
}

