query UserTodos($username: String!) {
  user(username: $username) {
    todos {
      nodes {
        id
        body
        group {
          id
        }
        state
        action
        author {
          avatarUrl
          name
          username
        }
        targetEntity {
          webUrl
        }
        project {
          avatarUrl
          fullPath
          nameWithNamespace
          visibility
          archived
        }
        createdAt
        targetType
      }
    }
  }
}
