/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/9.5.0/samples
 */
plugins {
	`java-library`
	kotlin("jvm") version "2.3.21"
	id("com.apollographql.apollo") version "4.4.3"
}

repositories {
	mavenCentral()
}

dependencies {
	api("com.apollographql.apollo:apollo-runtime:4.4.3")
}

apollo {
	service("service") {
		packageName.set("de.schindlerfelix.gitlab.api")
	}
}
