query ProjectMilestones($fullPath: ID!, $state: MilestoneStateEnum, $searchTitle: String, $includeAncestors: Boolean) {
  project(fullPath: $fullPath) {
    milestones(
      state: $state
      searchTitle: $searchTitle
      includeAncestors: $includeAncestors
    ) {
      nodes {
        id
        iid
        state
        title
        description
        expired
        startDate
        dueDate
        stats {
          closedIssuesCount
          totalIssuesCount
        }
        webPath
      }
    }
  }
}
