// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension Objects {
  /// Autogenerated return type of UpdateIssue.
  static let UpdateIssuePayload = ApolloAPI.Object(
    typename: "UpdateIssuePayload",
    implementedInterfaces: [],
    keyFields: nil
  )
}