query UserIssues($username: String!) {
  user(username: $username) {
    projectMemberships {
      nodes {
        project {
          fullPath
          issues(state: opened, assigneeUsernames: [$username], authorUsername: $username) {
            nodes {
              iid
              title
              reference(full: true)
              state
              upvotes
              downvotes
              userNotesCount
              author {
                avatarUrl
                name
                username
              }
              createdAt
              webUrl
            }
          }
        }
      }
    }
  }
}
