query UserIssues($username: String!, $state: IssuableState, $search: String, $confidential: Boolean, $subscribed: SubscriptionStatus, $types: [IssueType!]) {
  user(username: $username) {
    projectMemberships {
      nodes {
        project {
          fullPath
          issues(
            state: $state
            search: $search
            confidential: $confidential
            subscribed: $subscribed
            types: $types
            assigneeUsernames: [$username]
            authorUsername: $username
          ) {
            nodes {
              iid
              title
              reference(full: true)
              state
              upvotes
              downvotes
              userNotesCount
              author {
                avatarUrl
                name
                username
              }
              createdAt
              webUrl
            }
          }
        }
      }
    }
  }
}
