// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

extension Objects {
	/// Autogenerated return type of UpdateIssue.
	public nonisolated static let UpdateIssuePayload = ApolloAPI.Object(
		typename: "UpdateIssuePayload",
		implementedInterfaces: [],
		keyFields: nil
	)
}
