query Snippet($id: SnippetID!) {
  snippets(ids: [$id]) {
    nodes {
      id
      title
      description
      visibilityLevel
      userPermissions {
        createNote
      }
      author {
        avatarUrl
        username
        name
      }
      blobs {
        nodes {
          size
          name
          rawPlainData
        }
      }
      notes {
        nodes {
          id
          author {
            avatarUrl
            name
            username
          }
          maxAccessLevelOfAuthor
          body
          system
          systemNoteIconName
          createdAt
          updatedAt
        }
      }
      createdAt
      sshUrlToRepo
      httpUrlToRepo
      webUrl
    }
  }
}
