//
//  EmojiCodes.swift
//  GitLab
//
//  Created by Felix Schindler on 02.11.21.
//

import Foundation

let EMOJI_HASH: Dictionary<String, String> = [
	":+1:"                                : "\u{1F44D}",
	":-1:"                                : "\u{1F44E}",
	":100:"                               : "\u{1F4AF}",
	":1234:"                              : "\u{1F522}",
	":8ball:"                             : "\u{1F3B1}",
	":a:"                                 : "\u{1F170}",
	":ab:"                                : "\u{1F18E}",
	":abc:"                               : "\u{1F524}",
	":abcd:"                              : "\u{1F521}",
	":accept:"                            : "\u{1F251}",
	":aerial_tramway:"                    : "\u{1F6A1}",
	":airplane:"                          : "\u{02708}",
	":alarm_clock:"                       : "\u{023F0}",
	":alien:"                             : "\u{1F47D}",
	":ambulance:"                         : "\u{1F691}",
	":anchor:"                            : "\u{02693}",
	":angel:"                             : "\u{1F47C}",
	":anger:"                             : "\u{1F4A2}",
	":angry:"                             : "\u{1F620}",
	":anguished:"                         : "\u{1F627}",
	":ant:"                               : "\u{1F41C}",
	":apple:"                             : "\u{1F34E}",
	":aquarius:"                          : "\u{02652}",
	":aries:"                             : "\u{02648}",
	":arrow_backward:"                    : "\u{025C0}",
	":arrow_double_down:"                 : "\u{023EC}",
	":arrow_double_up:"                   : "\u{023EB}",
	":arrow_down:"                        : "\u{02B07}",
	":arrow_down_small:"                  : "\u{1F53D}",
	":arrow_forward:"                     : "\u{025B6}",
	":arrow_heading_down:"                : "\u{02935}",
	":arrow_heading_up:"                  : "\u{02934}",
	":arrow_left:"                        : "\u{02B05}",
	":arrow_lower_left:"                  : "\u{02199}",
	":arrow_lower_right:"                 : "\u{02198}",
	":arrow_right:"                       : "\u{027A1}",
	":arrow_right_hook:"                  : "\u{021AA}",
	":arrow_up:"                          : "\u{02B06}",
	":arrow_up_down:"                     : "\u{02195}",
	":arrow_up_small:"                    : "\u{1F53C}",
	":arrow_upper_left:"                  : "\u{02196}",
	":arrow_upper_right:"                 : "\u{02197}",
	":arrows_clockwise:"                  : "\u{1F503}",
	":arrows_counterclockwise:"           : "\u{1F504}",
	":art:"                               : "\u{1F3A8}",
	":articulated_lorry:"                 : "\u{1F69B}",
	":astonished:"                        : "\u{1F632}",
	":athletic_shoe:"                     : "\u{1F45F}",
	":atm:"                               : "\u{1F3E7}",
	":b:"                                 : "\u{1F171}",
	":baby:"                              : "\u{1F476}",
	":baby_bottle:"                       : "\u{1F37C}",
	":baby_chick:"                        : "\u{1F424}",
	":baby_symbol:"                       : "\u{1F6BC}",
	":back:"                              : "\u{1F519}",
	":baggage_claim:"                     : "\u{1F6C4}",
	":balloon:"                           : "\u{1F388}",
	":ballot_box_with_check:"             : "\u{02611}",
	":bamboo:"                            : "\u{1F38D}",
	":banana:"                            : "\u{1F34C}",
	":bangbang:"                          : "\u{0203C}",
	":bank:"                              : "\u{1F3E6}",
	":bar_chart:"                         : "\u{1F4CA}",
	":barber:"                            : "\u{1F488}",
	":baseball:"                          : "\u{026BE}",
	":basketball:"                        : "\u{1F3C0}",
	":bath:"                              : "\u{1F6C0}",
	":bathtub:"                           : "\u{1F6C1}",
	":battery:"                           : "\u{1F50B}",
	":bear:"                              : "\u{1F43B}",
	":bee:"                               : "\u{1F41D}",
	":beer:"                              : "\u{1F37A}",
	":beers:"                             : "\u{1F37B}",
	":beetle:"                            : "\u{1F41E}",
	":beginner:"                          : "\u{1F530}",
	":bell:"                              : "\u{1F514}",
	":bento:"                             : "\u{1F371}",
	":bicyclist:"                         : "\u{1F6B4}",
	":bike:"                              : "\u{1F6B2}",
	":bikini:"                            : "\u{1F459}",
	":bird:"                              : "\u{1F426}",
	":birthday:"                          : "\u{1F382}",
	":black_circle:"                      : "\u{026AB}",
	":black_joker:"                       : "\u{1F0CF}",
	":black_large_square:"                : "\u{02B1B}",
	":black_medium_small_square:"         : "\u{025FE}",
	":black_medium_square:"               : "\u{025FC}",
	":black_nib:"                         : "\u{02712}",
	":black_small_square:"                : "\u{025AA}",
	":black_square_button:"               : "\u{1F532}",
	":blossom:"                           : "\u{1F33C}",
	":blowfish:"                          : "\u{1F421}",
	":blue_book:"                         : "\u{1F4D8}",
	":blue_car:"                          : "\u{1F699}",
	":blue_heart:"                        : "\u{1F499}",
	":blush:"                             : "\u{1F60A}",
	":boar:"                              : "\u{1F417}",
	":boat:"                              : "\u{026F5}",
	":bomb:"                              : "\u{1F4A3}",
	":book:"                              : "\u{1F4D6}",
	":bookmark:"                          : "\u{1F516}",
	":bookmark_tabs:"                     : "\u{1F4D1}",
	":books:"                             : "\u{1F4DA}",
	":boom:"                              : "\u{1F4A5}",
	":boot:"                              : "\u{1F462}",
	":bouquet:"                           : "\u{1F490}",
	":bow:"                               : "\u{1F647}",
	":bowling:"                           : "\u{1F3B3}",
	":boxing_glove:"                      : "\u{1F94A}",
	":boy:"                               : "\u{1F466}",
	":bread:"                             : "\u{1F35E}",
	":bride_with_veil:"                   : "\u{1F470}",
	":bridge_at_night:"                   : "\u{1F309}",
	":briefcase:"                         : "\u{1F4BC}",
	":broken_heart:"                      : "\u{1F494}",
	":bug:"                               : "\u{1F41B}",
	":bulb:"                              : "\u{1F4A1}",
	":bullettrain_front:"                 : "\u{1F685}",
	":bullettrain_side:"                  : "\u{1F684}",
	":bus:"                               : "\u{1F68C}",
	":busstop:"                           : "\u{1F68F}",
	":bust_in_silhouette:"                : "\u{1F464}",
	":busts_in_silhouette:"               : "\u{1F465}",
	":cactus:"                            : "\u{1F335}",
	":cake:"                              : "\u{1F370}",
	":calendar:"                          : "\u{1F4C6}",
	":calling:"                           : "\u{1F4F2}",
	":camel:"                             : "\u{1F42B}",
	":camera:"                            : "\u{1F4F7}",
	":cancer:"                            : "\u{0264B}",
	":candy:"                             : "\u{1F36C}",
	":capital_abcd:"                      : "\u{1F520}",
	":capricorn:"                         : "\u{02651}",
	":car:"                               : "\u{1F697}",
	":card_index:"                        : "\u{1F4C7}",
	":carousel_horse:"                    : "\u{1F3A0}",
	":cat:"                               : "\u{1F431}",
	":cat2:"                              : "\u{1F408}",
	":cd:"                                : "\u{1F4BF}",
	":chart:"                             : "\u{1F4B9}",
	":chart_with_downwards_trend:"        : "\u{1F4C9}",
	":chart_with_upwards_trend:"          : "\u{1F4C8}",
	":checkered_flag:"                    : "\u{1F3C1}",
	":cherries:"                          : "\u{1F352}",
	":cherry_blossom:"                    : "\u{1F338}",
	":chestnut:"                          : "\u{1F330}",
	":chicken:"                           : "\u{1F414}",
	":children_crossing:"                 : "\u{1F6B8}",
	":chocolate_bar:"                     : "\u{1F36B}",
	":christmas_tree:"                    : "\u{1F384}",
	":church:"                            : "\u{026EA}",
	":cinema:"                            : "\u{1F3A6}",
	":circus_tent:"                       : "\u{1F3AA}",
	":city_sunrise:"                      : "\u{1F307}",
	":city_sunset:"                       : "\u{1F306}",
	":cl:"                                : "\u{1F191}",
	":clap:"                              : "\u{1F44F}",
	":clapper:"                           : "\u{1F3AC}",
	":clipboard:"                         : "\u{1F4CB}",
	":clock1:"                            : "\u{1F550}",
	":clock10:"                           : "\u{1F559}",
	":clock1030:"                         : "\u{1F565}",
	":clock11:"                           : "\u{1F55A}",
	":clock1130:"                         : "\u{1F566}",
	":clock12:"                           : "\u{1F55B}",
	":clock1230:"                         : "\u{1F567}",
	":clock130:"                          : "\u{1F55C}",
	":clock2:"                            : "\u{1F551}",
	":clock230:"                          : "\u{1F55D}",
	":clock3:"                            : "\u{1F552}",
	":clock330:"                          : "\u{1F55E}",
	":clock4:"                            : "\u{1F553}",
	":clock430:"                          : "\u{1F55F}",
	":clock5:"                            : "\u{1F554}",
	":clock530:"                          : "\u{1F560}",
	":clock6:"                            : "\u{1F555}",
	":clock630:"                          : "\u{1F561}",
	":clock7:"                            : "\u{1F556}",
	":clock730:"                          : "\u{1F562}",
	":clock8:"                            : "\u{1F557}",
	":clock830:"                          : "\u{1F563}",
	":clock9:"                            : "\u{1F558}",
	":clock930:"                          : "\u{1F564}",
	":closed_book:"                       : "\u{1F4D5}",
	":closed_lock_with_key:"              : "\u{1F510}",
	":closed_umbrella:"                   : "\u{1F302}",
	":cloud:"                             : "\u{02601}",
	":clubs:"                             : "\u{02663}",
	":cocktail:"                          : "\u{1F378}",
	":coffee:"                            : "\u{02615}",
	":cold_sweat:"                        : "\u{1F630}",
	":collision:"                         : "\u{1F4A5}",
	":computer:"                          : "\u{1F4BB}",
	":confetti_ball:"                     : "\u{1F38A}",
	":confounded:"                        : "\u{1F616}",
	":confused:"                          : "\u{1F615}",
	":congratulations:"                   : "\u{03297}",
	":construction:"                      : "\u{1F6A7}",
	":construction_worker:"               : "\u{1F477}",
	":convenience_store:"                 : "\u{1F3EA}",
	":cookie:"                            : "\u{1F36A}",
	":cool:"                              : "\u{1F192}",
	":cop:"                               : "\u{1F46E}",
	":copyright:"                         : "\u{A9}",
	":corn:"                              : "\u{1F33D}",
	":couple:"                            : "\u{1F46B}",
	":couple_with_heart:"                 : "\u{1F491}",
	":couplekiss:"                        : "\u{1F48F}",
	":cow:"                               : "\u{1F42E}",
	":cow2:"                              : "\u{1F404}",
	":credit_card:"                       : "\u{1F4B3}",
	":crescent_moon:"                     : "\u{1F319}",
	":crocodile:"                         : "\u{1F40A}",
	":crossed_flags:"                     : "\u{1F38C}",
	":crown:"                             : "\u{1F451}",
	":cry:"                               : "\u{1F622}",
	":crying_cat_face:"                   : "\u{1F63F}",
	":crystal_ball:"                      : "\u{1F52E}",
	":cupid:"                             : "\u{1F498}",
	":curly_loop:"                        : "\u{027B0}",
	":currency_exchange:"                 : "\u{1F4B1}",
	":curry:"                             : "\u{1F35B}",
	":custard:"                           : "\u{1F36E}",
	":customs:"                           : "\u{1F6C3}",
	":cyclone:"                           : "\u{1F300}",
	":dancer:"                            : "\u{1F483}",
	":dancers:"                           : "\u{1F46F}",
	":dango:"                             : "\u{1F361}",
	":dart:"                              : "\u{1F3AF}",
	":dash:"                              : "\u{1F4A8}",
	":date:"                              : "\u{1F4C5}",
	":deciduous_tree:"                    : "\u{1F333}",
	":department_store:"                  : "\u{1F3EC}",
	":diamond_shape_with_a_dot_inside:"   : "\u{1F4A0}",
	":diamonds:"                          : "\u{02666}",
	":disappointed:"                      : "\u{1F61E}",
	":disappointed_relieved:"             : "\u{1F625}",
	":dizzy:"                             : "\u{1F4AB}",
	":dizzy_face:"                        : "\u{1F635}",
	":do_not_litter:"                     : "\u{1F6AF}",
	":dog:"                               : "\u{1F436}",
	":dog2:"                              : "\u{1F415}",
	":dollar:"                            : "\u{1F4B5}",
	":dolls:"                             : "\u{1F38E}",
	":dolphin:"                           : "\u{1F42C}",
	":door:"                              : "\u{1F6AA}",
	":doughnut:"                          : "\u{1F369}",
	":dragon:"                            : "\u{1F409}",
	":dragon_face:"                       : "\u{1F432}",
	":dress:"                             : "\u{1F457}",
	":dromedary_camel:"                   : "\u{1F42A}",
	":droplet:"                           : "\u{1F4A7}",
	":dvd:"                               : "\u{1F4C0}",
	":e-mail:"                            : "\u{1F4E7}",
	":ear:"                               : "\u{1F442}",
	":ear_of_rice:"                       : "\u{1F33E}",
	":earth_africa:"                      : "\u{1F30D}",
	":earth_americas:"                    : "\u{1F30E}",
	":earth_asia:"                        : "\u{1F30F}",
	":egg:"                               : "\u{1F373}",
	":eggplant:"                          : "\u{1F346}",
	":eight_pointed_black_star:"          : "\u{02734}",
	":eight_spoked_asterisk:"             : "\u{02733}",
	":electric_plug:"                     : "\u{1F50C}",
	":elephant:"                          : "\u{1F418}",
	":email:"                             : "\u{02709}",
	":end:"                               : "\u{1F51A}",
	":envelope:"                          : "\u{02709}",
	":envelope_with_arrow:"               : "\u{1F4E9}",
	":euro:"                              : "\u{1F4B6}",
	":european_castle:"                   : "\u{1F3F0}",
	":european_post_office:"              : "\u{1F3E4}",
	":evergreen_tree:"                    : "\u{1F332}",
	":exclamation:"                       : "\u{02757}",
	":expressionless:"                    : "\u{1F611}",
	":eyeglasses:"                        : "\u{1F453}",
	":eyes:"                              : "\u{1F440}",
	":facepunch:"                         : "\u{1F44A}",
	":factory:"                           : "\u{1F3ED}",
	":fallen_leaf:"                       : "\u{1F342}",
	":family:"                            : "\u{1F46A}",
	":fast_forward:"                      : "\u{023E9}",
	":fax:"                               : "\u{1F4E0}",
	":fearful:"                           : "\u{1F628}",
	":feet:"                              : "\u{1F43E}",
	":ferris_wheel:"                      : "\u{1F3A1}",
	":file_folder:"                       : "\u{1F4C1}",
	":fire:"                              : "\u{1F525}",
	":fire_engine:"                       : "\u{1F692}",
	":fireworks:"                         : "\u{1F386}",
	":first_quarter_moon:"                : "\u{1F313}",
	":first_quarter_moon_with_face:"      : "\u{1F31B}",
	":fish:"                              : "\u{1F41F}",
	":fish_cake:"                         : "\u{1F365}",
	":fishing_pole_and_fish:"             : "\u{1F3A3}",
	":fist:"                              : "\u{0270A}",
	":flags:"                             : "\u{1F38F}",
	":flashlight:"                        : "\u{1F526}",
	":flipper:"                           : "\u{1F42C}",
	":floppy_disk:"                       : "\u{1F4BE}",
	":flower_playing_cards:"              : "\u{1F3B4}",
	":flushed:"                           : "\u{1F633}",
	":foggy:"                             : "\u{1F301}",
	":football:"                          : "\u{1F3C8}",
	":footprints:"                        : "\u{1F463}",
	":fork_and_knife:"                    : "\u{1F374}",
	":fountain:"                          : "\u{026F2}",
	":four_leaf_clover:"                  : "\u{1F340}",
	":free:"                              : "\u{1F193}",
	":fried_shrimp:"                      : "\u{1F364}",
	":fries:"                             : "\u{1F35F}",
	":frog:"                              : "\u{1F438}",
	":frowning:"                          : "\u{1F626}",
	":fuelpump:"                          : "\u{026FD}",
	":full_moon:"                         : "\u{1F315}",
	":full_moon_with_face:"               : "\u{1F31D}",
	":game_die:"                          : "\u{1F3B2}",
	":gem:"                               : "\u{1F48E}",
	":gemini:"                            : "\u{0264A}",
	":ghost:"                             : "\u{1F47B}",
	":gift:"                              : "\u{1F381}",
	":gift_heart:"                        : "\u{1F49D}",
	":girl:"                              : "\u{1F467}",
	":globe_with_meridians:"              : "\u{1F310}",
	":goat:"                              : "\u{1F410}",
	":golf:"                              : "\u{026F3}",
	":grapes:"                            : "\u{1F347}",
	":green_apple:"                       : "\u{1F34F}",
	":green_book:"                        : "\u{1F4D7}",
	":green_heart:"                       : "\u{1F49A}",
	":grey_exclamation:"                  : "\u{02755}",
	":grey_question:"                     : "\u{02754}",
	":grimacing:"                         : "\u{1F62C}",
	":grin:"                              : "\u{1F601}",
	":grinning:"                          : "\u{1F600}",
	":guardsman:"                         : "\u{1F482}",
	":guitar:"                            : "\u{1F3B8}",
	":gun:"                               : "\u{1F52B}",
	":haircut:"                           : "\u{1F487}",
	":hamburger:"                         : "\u{1F354}",
	":hammer:"                            : "\u{1F528}",
	":hamster:"                           : "\u{1F439}",
	":hand:"                              : "\u{0270B}",
	":handbag:"                           : "\u{1F45C}",
	":hankey:"                            : "\u{1F4A9}",
	":hatched_chick:"                     : "\u{1F425}",
	":hatching_chick:"                    : "\u{1F423}",
	":headphones:"                        : "\u{1F3A7}",
	":hear_no_evil:"                      : "\u{1F649}",
	":heart:"                             : "\u{02764}",
	":heart_decoration:"                  : "\u{1F49F}",
	":heart_eyes:"                        : "\u{1F60D}",
	":heart_eyes_cat:"                    : "\u{1F63B}",
	":heartbeat:"                         : "\u{1F493}",
	":heartpulse:"                        : "\u{1F497}",
	":hearts:"                            : "\u{02665}",
	":heavy_check_mark:"                  : "\u{02714}",
	":heavy_division_sign:"               : "\u{02797}",
	":heavy_dollar_sign:"                 : "\u{1F4B2}",
	":heavy_exclamation_mark:"            : "\u{02757}",
	":heavy_minus_sign:"                  : "\u{02796}",
	":heavy_multiplication_x:"            : "\u{02716}",
	":heavy_plus_sign:"                   : "\u{02795}",
	":helicopter:"                        : "\u{1F681}",
	":herb:"                              : "\u{1F33F}",
	":hibiscus:"                          : "\u{1F33A}",
	":high_brightness:"                   : "\u{1F506}",
	":high_heel:"                         : "\u{1F460}",
	":hocho:"                             : "\u{1F52A}",
	":honey_pot:"                         : "\u{1F36F}",
	":honeybee:"                          : "\u{1F41D}",
	":horse:"                             : "\u{1F434}",
	":horse_racing:"                      : "\u{1F3C7}",
	":hospital:"                          : "\u{1F3E5}",
	":hotel:"                             : "\u{1F3E8}",
	":hotsprings:"                        : "\u{02668}",
	":hourglass:"                         : "\u{0231B}",
	":hourglass_flowing_sand:"            : "\u{023F3}",
	":house:"                             : "\u{1F3E0}",
	":house_with_garden:"                 : "\u{1F3E1}",
	":hushed:"                            : "\u{1F62F}",
	":ice_cream:"                         : "\u{1F368}",
	":icecream:"                          : "\u{1F366}",
	":id:"                                : "\u{1F194}",
	":ideograph_advantage:"               : "\u{1F250}",
	":imp:"                               : "\u{1F47F}",
	":inbox_tray:"                        : "\u{1F4E5}",
	":incoming_envelope:"                 : "\u{1F4E8}",
	":information_desk_person:"           : "\u{1F481}",
	":information_source:"                : "\u{02139}",
	":innocent:"                          : "\u{1F607}",
	":interrobang:"                       : "\u{02049}",
	":iphone:"                            : "\u{1F4F1}",
	":izakaya_lantern:"                   : "\u{1F3EE}",
	":jack_o_lantern:"                    : "\u{1F383}",
	":japan:"                             : "\u{1F5FE}",
	":japanese_castle:"                   : "\u{1F3EF}",
	":japanese_goblin:"                   : "\u{1F47A}",
	":japanese_ogre:"                     : "\u{1F479}",
	":jeans:"                             : "\u{1F456}",
	":joy:"                               : "\u{1F602}",
	":joy_cat:"                           : "\u{1F639}",
	":key:"                               : "\u{1F511}",
	":keycap_ten:"                        : "\u{1F51F}",
	":kimono:"                            : "\u{1F458}",
	":kiss:"                              : "\u{1F48B}",
	":kissing:"                           : "\u{1F617}",
	":kissing_cat:"                       : "\u{1F63D}",
	":kissing_closed_eyes:"               : "\u{1F61A}",
	":kissing_heart:"                     : "\u{1F618}",
	":kissing_smiling_eyes:"              : "\u{1F619}",
	":koala:"                             : "\u{1F428}",
	":koko:"                              : "\u{1F201}",
	":lantern:"                           : "\u{1F3EE}",
	":large_blue_circle:"                 : "\u{1F535}",
	":large_blue_diamond:"                : "\u{1F537}",
	":large_orange_diamond:"              : "\u{1F536}",
	":last_quarter_moon:"                 : "\u{1F317}",
	":last_quarter_moon_with_face:"       : "\u{1F31C}",
	":laughing:"                          : "\u{1F606}",
	":leaves:"                            : "\u{1F343}",
	":ledger:"                            : "\u{1F4D2}",
	":left_luggage:"                      : "\u{1F6C5}",
	":left_right_arrow:"                  : "\u{02194}",
	":leftwards_arrow_with_hook:"         : "\u{021A9}",
	":lemon:"                             : "\u{1F34B}",
	":leo:"                               : "\u{0264C}",
	":leopard:"                           : "\u{1F406}",
	":libra:"                             : "\u{0264E}",
	":light_rail:"                        : "\u{1F688}",
	":link:"                              : "\u{1F517}",
	":lips:"                              : "\u{1F444}",
	":lipstick:"                          : "\u{1F484}",
	":lock:"                              : "\u{1F512}",
	":lock_with_ink_pen:"                 : "\u{1F50F}",
	":lollipop:"                          : "\u{1F36D}",
	":loop:"                              : "\u{027BF}",
	":loudspeaker:"                       : "\u{1F4E2}",
	":love_hotel:"                        : "\u{1F3E9}",
	":love_letter:"                       : "\u{1F48C}",
	":low_brightness:"                    : "\u{1F505}",
	":m:"                                 : "\u{024C2}",
	":mag:"                               : "\u{1F50D}",
	":mag_right:"                         : "\u{1F50E}",
	":mahjong:"                           : "\u{1F004}",
	":mailbox:"                           : "\u{1F4EB}",
	":mailbox_closed:"                    : "\u{1F4EA}",
	":mailbox_with_mail:"                 : "\u{1F4EC}",
	":mailbox_with_no_mail:"              : "\u{1F4ED}",
	":man:"                               : "\u{1F468}",
	":man_with_gua_pi_mao:"               : "\u{1F472}",
	":man_with_turban:"                   : "\u{1F473}",
	":mans_shoe:"                         : "\u{1F45E}",
	":maple_leaf:"                        : "\u{1F341}",
	":mask:"                              : "\u{1F637}",
	":massage:"                           : "\u{1F486}",
	":meat_on_bone:"                      : "\u{1F356}",
	":mega:"                              : "\u{1F4E3}",
	":melon:"                             : "\u{1F348}",
	":memo:"                              : "\u{1F4DD}",
	":mens:"                              : "\u{1F6B9}",
	":metro:"                             : "\u{1F687}",
	":microphone:"                        : "\u{1F3A4}",
	":microscope:"                        : "\u{1F52C}",
	":milky_way:"                         : "\u{1F30C}",
	":minibus:"                           : "\u{1F690}",
	":minidisc:"                          : "\u{1F4BD}",
	":mobile_phone_off:"                  : "\u{1F4F4}",
	":money_with_wings:"                  : "\u{1F4B8}",
	":moneybag:"                          : "\u{1F4B0}",
	":monkey:"                            : "\u{1F412}",
	":monkey_face:"                       : "\u{1F435}",
	":monorail:"                          : "\u{1F69D}",
	":moon:"                              : "\u{1F314}",
	":mortar_board:"                      : "\u{1F393}",
	":mount_fuji:"                        : "\u{1F5FB}",
	":mountain_bicyclist:"                : "\u{1F6B5}",
	":mountain_cableway:"                 : "\u{1F6A0}",
	":mountain_railway:"                  : "\u{1F69E}",
	":mouse:"                             : "\u{1F42D}",
	":mouse2:"                            : "\u{1F401}",
	":movie_camera:"                      : "\u{1F3A5}",
	":moyai:"                             : "\u{1F5FF}",
	":muscle:"                            : "\u{1F4AA}",
	":mushroom:"                          : "\u{1F344}",
	":musical_keyboard:"                  : "\u{1F3B9}",
	":musical_note:"                      : "\u{1F3B5}",
	":musical_score:"                     : "\u{1F3BC}",
	":mute:"                              : "\u{1F507}",
	":nail_care:"                         : "\u{1F485}",
	":name_badge:"                        : "\u{1F4DB}",
	":necktie:"                           : "\u{1F454}",
	":negative_squared_cross_mark:"       : "\u{0274E}",
	":neutral_face:"                      : "\u{1F610}",
	":new:"                               : "\u{1F195}",
	":new_moon:"                          : "\u{1F311}",
	":new_moon_with_face:"                : "\u{1F31A}",
	":newspaper:"                         : "\u{1F4F0}",
	":ng:"                                : "\u{1F196}",
	":no_bell:"                           : "\u{1F515}",
	":no_bicycles:"                       : "\u{1F6B3}",
	":no_entry:"                          : "\u{026D4}",
	":no_entry_sign:"                     : "\u{1F6AB}",
	":no_good:"                           : "\u{1F645}",
	":no_mobile_phones:"                  : "\u{1F4F5}",
	":no_mouth:"                          : "\u{1F636}",
	":no_pedestrians:"                    : "\u{1F6B7}",
	":no_smoking:"                        : "\u{1F6AD}",
	":non-potable_water:"                 : "\u{1F6B1}",
	":nose:"                              : "\u{1F443}",
	":notebook:"                          : "\u{1F4D3}",
	":notebook_with_decorative_cover:"    : "\u{1F4D4}",
	":notes:"                             : "\u{1F3B6}",
	":nut_and_bolt:"                      : "\u{1F529}",
	":o:"                                 : "\u{02B55}",
	":o2:"                                : "\u{1F17E}",
	":ocean:"                             : "\u{1F30A}",
	":octopus:"                           : "\u{1F419}",
	":oden:"                              : "\u{1F362}",
	":office:"                            : "\u{1F3E2}",
	":ok:"                                : "\u{1F197}",
	":ok_hand:"                           : "\u{1F44C}",
	":ok_woman:"                          : "\u{1F646}",
	":older_man:"                         : "\u{1F474}",
	":older_woman:"                       : "\u{1F475}",
	":on:"                                : "\u{1F51B}",
	":oncoming_automobile:"               : "\u{1F698}",
	":oncoming_bus:"                      : "\u{1F68D}",
	":oncoming_police_car:"               : "\u{1F694}",
	":oncoming_taxi:"                     : "\u{1F696}",
	":open_book:"                         : "\u{1F4D6}",
	":open_file_folder:"                  : "\u{1F4C2}",
	":open_hands:"                        : "\u{1F450}",
	":open_mouth:"                        : "\u{1F62E}",
	":ophiuchus:"                         : "\u{026CE}",
	":orange_book:"                       : "\u{1F4D9}",
	":outbox_tray:"                       : "\u{1F4E4}",
	":ox:"                                : "\u{1F402}",
	":package:"                           : "\u{1F4E6}",
	":page_facing_up:"                    : "\u{1F4C4}",
	":page_with_curl:"                    : "\u{1F4C3}",
	":pager:"                             : "\u{1F4DF}",
	":palm_tree:"                         : "\u{1F334}",
	":panda_face:"                        : "\u{1F43C}",
	":paperclip:"                         : "\u{1F4CE}",
	":parking:"                           : "\u{1F17F}",
	":part_alternation_mark:"             : "\u{0303D}",
	":partly_sunny:"                      : "\u{026C5}",
	":passport_control:"                  : "\u{1F6C2}",
	":paw_prints:"                        : "\u{1F43E}",
	":peach:"                             : "\u{1F351}",
	":pear:"                              : "\u{1F350}",
	":pencil:"                            : "\u{1F4DD}",
	":pencil2:"                           : "\u{0270F}",
	":penguin:"                           : "\u{1F427}",
	":pensive:"                           : "\u{1F614}",
	":performing_arts:"                   : "\u{1F3AD}",
	":persevere:"                         : "\u{1F623}",
	":person_frowning:"                   : "\u{1F64D}",
	":person_with_blond_hair:"            : "\u{1F471}",
	":person_with_pouting_face:"          : "\u{1F64E}",
	":phone:"                             : "\u{0260E}",
	":pig:"                               : "\u{1F437}",
	":pig2:"                              : "\u{1F416}",
	":pig_nose:"                          : "\u{1F43D}",
	":pill:"                              : "\u{1F48A}",
	":pineapple:"                         : "\u{1F34D}",
	":pisces:"                            : "\u{02653}",
	":pizza:"                             : "\u{1F355}",
	":point_down:"                        : "\u{1F447}",
	":point_left:"                        : "\u{1F448}",
	":point_right:"                       : "\u{1F449}",
	":point_up:"                          : "\u{0261D}",
	":point_up_2:"                        : "\u{1F446}",
	":police_car:"                        : "\u{1F693}",
	":poodle:"                            : "\u{1F429}",
	":poop:"                              : "\u{1F4A9}",
	":post_office:"                       : "\u{1F3E3}",
	":postal_horn:"                       : "\u{1F4EF}",
	":postbox:"                           : "\u{1F4EE}",
	":potable_water:"                     : "\u{1F6B0}",
	":pouch:"                             : "\u{1F45D}",
	":poultry_leg:"                       : "\u{1F357}",
	":pound:"                             : "\u{1F4B7}",
	":pouting_cat:"                       : "\u{1F63E}",
	":pray:"                              : "\u{1F64F}",
	":princess:"                          : "\u{1F478}",
	":punch:"                             : "\u{1F44A}",
	":purple_heart:"                      : "\u{1F49C}",
	":purse:"                             : "\u{1F45B}",
	":pushpin:"                           : "\u{1F4CC}",
	":put_litter_in_its_place:"           : "\u{1F6AE}",
	":question:"                          : "\u{02753}",
	":rabbit:"                            : "\u{1F430}",
	":rabbit2:"                           : "\u{1F407}",
	":racehorse:"                         : "\u{1F40E}",
	":radio:"                             : "\u{1F4FB}",
	":radio_button:"                      : "\u{1F518}",
	":rage:"                              : "\u{1F621}",
	":railway_car:"                       : "\u{1F683}",
	":rainbow:"                           : "\u{1F308}",
	":raised_hand:"                       : "\u{0270B}",
	":raised_hands:"                      : "\u{1F64C}",
	":raising_hand:"                      : "\u{1F64B}",
	":ram:"                               : "\u{1F40F}",
	":ramen:"                             : "\u{1F35C}",
	":rat:"                               : "\u{1F400}",
	":recycle:"                           : "\u{0267B}",
	":red_car:"                           : "\u{1F697}",
	":red_circle:"                        : "\u{1F534}",
	":registered:"                        : "\u{AE}",
	":relaxed:"                           : "\u{0263A}",
	":relieved:"                          : "\u{1F60C}",
	":repeat:"                            : "\u{1F501}",
	":repeat_one:"                        : "\u{1F502}",
	":restroom:"                          : "\u{1F6BB}",
	":revolving_hearts:"                  : "\u{1F49E}",
	":rewind:"                            : "\u{023EA}",
	":ribbon:"                            : "\u{1F380}",
	":rice:"                              : "\u{1F35A}",
	":rice_ball:"                         : "\u{1F359}",
	":rice_cracker:"                      : "\u{1F358}",
	":rice_scene:"                        : "\u{1F391}",
	":ring:"                              : "\u{1F48D}",
	":rocket:"                            : "\u{1F680}",
	":roller_coaster:"                    : "\u{1F3A2}",
	":rooster:"                           : "\u{1F413}",
	":rose:"                              : "\u{1F339}",
	":rotating_light:"                    : "\u{1F6A8}",
	":round_pushpin:"                     : "\u{1F4CD}",
	":rowboat:"                           : "\u{1F6A3}",
	":rugby_football:"                    : "\u{1F3C9}",
	":runner:"                            : "\u{1F3C3}",
	":running:"                           : "\u{1F3C3}",
	":running_shirt_with_sash:"           : "\u{1F3BD}",
	":sa:"                                : "\u{1F202}",
	":sagittarius:"                       : "\u{02650}",
	":sailboat:"                          : "\u{026F5}",
	":sake:"                              : "\u{1F376}",
	":sandal:"                            : "\u{1F461}",
	":santa:"                             : "\u{1F385}",
	":satellite:"                         : "\u{1F4E1}",
	":satisfied:"                         : "\u{1F606}",
	":saxophone:"                         : "\u{1F3B7}",
	":school:"                            : "\u{1F3EB}",
	":school_satchel:"                    : "\u{1F392}",
	":scissors:"                          : "\u{02702}",
	":scorpius:"                          : "\u{0264F}",
	":scream:"                            : "\u{1F631}",
	":scream_cat:"                        : "\u{1F640}",
	":scroll:"                            : "\u{1F4DC}",
	":seat:"                              : "\u{1F4BA}",
	":secret:"                            : "\u{03299}",
	":see_no_evil:"                       : "\u{1F648}",
	":seedling:"                          : "\u{1F331}",
	":shaved_ice:"                        : "\u{1F367}",
	":sheep:"                             : "\u{1F411}",
	":shell:"                             : "\u{1F41A}",
	":ship:"                              : "\u{1F6A2}",
	":shirt:"                             : "\u{1F455}",
	":shit:"                              : "\u{1F4A9}",
	":shoe:"                              : "\u{1F45E}",
	":shower:"                            : "\u{1F6BF}",
	":signal_strength:"                   : "\u{1F4F6}",
	":six_pointed_star:"                  : "\u{1F52F}",
	":ski:"                               : "\u{1F3BF}",
	":skull:"                             : "\u{1F480}",
	":sleeping:"                          : "\u{1F634}",
	":sleepy:"                            : "\u{1F62A}",
	":slot_machine:"                      : "\u{1F3B0}",
	":small_blue_diamond:"                : "\u{1F539}",
	":small_orange_diamond:"              : "\u{1F538}",
	":small_red_triangle:"                : "\u{1F53A}",
	":small_red_triangle_down:"           : "\u{1F53B}",
	":smile:"                             : "\u{1F604}",
	":smile_cat:"                         : "\u{1F638}",
	":smiley:"                            : "\u{1F603}",
	":smiley_cat:"                        : "\u{1F63A}",
	":smiling_imp:"                       : "\u{1F608}",
	":smirk:"                             : "\u{1F60F}",
	":smirk_cat:"                         : "\u{1F63C}",
	":smoking:"                           : "\u{1F6AC}",
	":snail:"                             : "\u{1F40C}",
	":snake:"                             : "\u{1F40D}",
	":snowboarder:"                       : "\u{1F3C2}",
	":snowflake:"                         : "\u{02744}",
	":snowman:"                           : "\u{026C4}",
	":sob:"                               : "\u{1F62D}",
	":soccer:"                            : "\u{026BD}",
	":soon:"                              : "\u{1F51C}",
	":sos:"                               : "\u{1F198}",
	":sound:"                             : "\u{1F509}",
	":space_invader:"                     : "\u{1F47E}",
	":spades:"                            : "\u{02660}",
	":spaghetti:"                         : "\u{1F35D}",
	":sparkle:"                           : "\u{02747}",
	":sparkler:"                          : "\u{1F387}",
	":sparkles:"                          : "\u{02728}",
	":sparkling_heart:"                   : "\u{1F496}",
	":speak_no_evil:"                     : "\u{1F64A}",
	":speaker:"                           : "\u{1F50A}",
	":speech_balloon:"                    : "\u{1F4AC}",
	":speedboat:"                         : "\u{1F6A4}",
	":star:"                              : "\u{02B50}",
	":star2:"                             : "\u{1F31F}",
	":stars:"                             : "\u{1F303}",
	":station:"                           : "\u{1F689}",
	":statue_of_liberty:"                 : "\u{1F5FD}",
	":steam_locomotive:"                  : "\u{1F682}",
	":stew:"                              : "\u{1F372}",
	":straight_ruler:"                    : "\u{1F4CF}",
	":strawberry:"                        : "\u{1F353}",
	":stuck_out_tongue:"                  : "\u{1F61B}",
	":stuck_out_tongue_closed_eyes:"      : "\u{1F61D}",
	":stuck_out_tongue_winking_eye:"      : "\u{1F61C}",
	":sun_with_face:"                     : "\u{1F31E}",
	":sunflower:"                         : "\u{1F33B}",
	":sunglasses:"                        : "\u{1F60E}",
	":sunny:"                             : "\u{02600}",
	":sunrise:"                           : "\u{1F305}",
	":sunrise_over_mountains:"            : "\u{1F304}",
	":surfer:"                            : "\u{1F3C4}",
	":sushi:"                             : "\u{1F363}",
	":suspension_railway:"                : "\u{1F69F}",
	":sweat:"                             : "\u{1F613}",
	":sweat_drops:"                       : "\u{1F4A6}",
	":sweat_smile:"                       : "\u{1F605}",
	":sweet_potato:"                      : "\u{1F360}",
	":swimmer:"                           : "\u{1F3CA}",
	":symbols:"                           : "\u{1F523}",
	":syringe:"                           : "\u{1F489}",
	":tada:"                              : "\u{1F389}",
	":tanabata_tree:"                     : "\u{1F38B}",
	":tangerine:"                         : "\u{1F34A}",
	":taurus:"                            : "\u{02649}",
	":taxi:"                              : "\u{1F695}",
	":tea:"                               : "\u{1F375}",
	":telephone:"                         : "\u{0260E}",
	":telephone_receiver:"                : "\u{1F4DE}",
	":telescope:"                         : "\u{1F52D}",
	":tennis:"                            : "\u{1F3BE}",
	":tent:"                              : "\u{026FA}",
	":thought_balloon:"                   : "\u{1F4AD}",
	":thumbsdown:"                        : "\u{1F44E}",
	":thumbsup:"                          : "\u{1F44D}",
	":ticket:"                            : "\u{1F3AB}",
	":tiger:"                             : "\u{1F42F}",
	":tiger2:"                            : "\u{1F405}",
	":tired_face:"                        : "\u{1F62B}",
	":tm:"                                : "\u{02122}",
	":toilet:"                            : "\u{1F6BD}",
	":tokyo_tower:"                       : "\u{1F5FC}",
	":tomato:"                            : "\u{1F345}",
	":tongue:"                            : "\u{1F445}",
	":top:"                               : "\u{1F51D}",
	":tophat:"                            : "\u{1F3A9}",
	":tractor:"                           : "\u{1F69C}",
	":traffic_light:"                     : "\u{1F6A5}",
	":train:"                             : "\u{1F683}",
	":train2:"                            : "\u{1F686}",
	":tram:"                              : "\u{1F68A}",
	":triangular_flag_on_post:"           : "\u{1F6A9}",
	":triangular_ruler:"                  : "\u{1F4D0}",
	":trident:"                           : "\u{1F531}",
	":triumph:"                           : "\u{1F624}",
	":trolleybus:"                        : "\u{1F68E}",
	":trophy:"                            : "\u{1F3C6}",
	":tropical_drink:"                    : "\u{1F379}",
	":tropical_fish:"                     : "\u{1F420}",
	":truck:"                             : "\u{1F69A}",
	":trumpet:"                           : "\u{1F3BA}",
	":tshirt:"                            : "\u{1F455}",
	":tulip:"                             : "\u{1F337}",
	":turtle:"                            : "\u{1F422}",
	":tv:"                                : "\u{1F4FA}",
	":twisted_rightwards_arrows:"         : "\u{1F500}",
	":two_hearts:"                        : "\u{1F495}",
	":two_men_holding_hands:"             : "\u{1F46C}",
	":two_women_holding_hands:"           : "\u{1F46D}",
	":u5272:"                             : "\u{1F239}",
	":u5408:"                             : "\u{1F234}",
	":u55b6:"                             : "\u{1F23A}",
	":u6307:"                             : "\u{1F22F}",
	":u6708:"                             : "\u{1F237}",
	":u6709:"                             : "\u{1F236}",
	":u6e80:"                             : "\u{1F235}",
	":u7121:"                             : "\u{1F21A}",
	":u7533:"                             : "\u{1F238}",
	":u7981:"                             : "\u{1F232}",
	":u7a7a:"                             : "\u{1F233}",
	":umbrella:"                          : "\u{02614}",
	":unamused:"                          : "\u{1F612}",
	":underage:"                          : "\u{1F51E}",
	":unlock:"                            : "\u{1F513}",
	":up:"                                : "\u{1F199}",
	":v:"                                 : "\u{0270C}",
	":vertical_traffic_light:"            : "\u{1F6A6}",
	":vhs:"                               : "\u{1F4FC}",
	":vibration_mode:"                    : "\u{1F4F3}",
	":video_camera:"                      : "\u{1F4F9}",
	":video_game:"                        : "\u{1F3AE}",
	":violin:"                            : "\u{1F3BB}",
	":virgo:"                             : "\u{0264D}",
	":volcano:"                           : "\u{1F30B}",
	":vs:"                                : "\u{1F19A}",
	":walking:"                           : "\u{1F6B6}",
	":waning_crescent_moon:"              : "\u{1F318}",
	":waning_gibbous_moon:"               : "\u{1F316}",
	":warning:"                           : "\u{026A0}",
	":watch:"                             : "\u{0231A}",
	":water_buffalo:"                     : "\u{1F403}",
	":watermelon:"                        : "\u{1F349}",
	":wave:"                              : "\u{1F44B}",
	":wavy_dash:"                         : "\u{03030}",
	":waxing_crescent_moon:"              : "\u{1F312}",
	":waxing_gibbous_moon:"               : "\u{1F314}",
	":wc:"                                : "\u{1F6BE}",
	":weary:"                             : "\u{1F629}",
	":wedding:"                           : "\u{1F492}",
	":whale:"                             : "\u{1F433}",
	":whale2:"                            : "\u{1F40B}",
	":wheelchair:"                        : "\u{0267F}",
	":white_check_mark:"                  : "\u{02705}",
	":white_circle:"                      : "\u{026AA}",
	":white_flower:"                      : "\u{1F4AE}",
	":white_large_square:"                : "\u{02B1C}",
	":white_medium_small_square:"         : "\u{025FD}",
	":white_medium_square:"               : "\u{025FB}",
	":white_small_square:"                : "\u{025AB}",
	":white_square_button:"               : "\u{1F533}",
	":wind_chime:"                        : "\u{1F390}",
	":wine_glass:"                        : "\u{1F377}",
	":wink:"                              : "\u{1F609}",
	":wolf:"                              : "\u{1F43A}",
	":woman:"                             : "\u{1F469}",
	":womans_clothes:"                    : "\u{1F45A}",
	":womans_hat:"                        : "\u{1F452}",
	":womens:"                            : "\u{1F6BA}",
	":worried:"                           : "\u{1F61F}",
	":wrench:"                            : "\u{1F527}",
	":x:"                                 : "\u{0274C}",
	":yellow_heart:"                      : "\u{1F49B}",
	":yen:"                               : "\u{1F4B4}",
	":yum:"                               : "\u{1F60B}",
	":zap:"                               : "\u{026A1}",
	":zzz:"                               : "\u{1F4A4}",
	":grinning_face:": "😀",
	":grinning_face_with_big_eyes:": "😃",
	":grinning_face_with_smiling_eyes:": "😄",
	":beaming_face_with_smiling_eyes:": "😁",
	":grinning_squinting_face:": "😆",
	":grinning_face_with_sweat:": "😅",
	":rolling_on_the_floor_laughing:": "🤣",
	":face_with_tears_of_joy:": "😂",
	":slightly_smiling_face:": "🙂",
	":upside_down_face:": "🙃",
	":melting_face:": "🫠",
	":winking_face:": "😉",
	":smiling_face_with_smiling_eyes:": "😊",
	":smiling_face_with_halo:": "😇",
	":smiling_face_with_hearts:": "🥰",
	":smiling_face_with_heart_eyes:": "😍",
	":star_struck:": "🤩",
	":face_blowing_a_kiss:": "😘",
	":kissing_face:": "😗",
	":smiling_face:": "☺️",
	":kissing_face_with_closed_eyes:": "😚",
	":kissing_face_with_smiling_eyes:": "😙",
	":smiling_face_with_tear:": "🥲",
	":face_savoring_food:": "😋",
	":face_with_tongue:": "😛",
	":winking_face_with_tongue:": "😜",
	":zany_face:": "🤪",
	":squinting_face_with_tongue:": "😝",
	":money_mouth_face:": "🤑",
	":smiling_face_with_open_hands:": "🤗",
	":face_with_hand_over_mouth:": "🤭",
	":face_with_open_eyes_and_hand_over_mouth:": "🫢",
	":face_with_peeking_eye:": "🫣",
	":shushing_face:": "🤫",
	":thinking_face:": "🤔",
	":saluting_face:": "🫡",
	":zipper_mouth_face:": "🤐",
	":face_with_raised_eyebrow:": "🤨",
	":neutral_face:": "😐",
	":expressionless_face:": "😑",
	":face_without_mouth:": "😶",
	":dotted_line_face:": "🫥",
	":face_in_clouds:": "😶‍🌫️",
	":smirking_face:": "😏",
	":unamused_face:": "😒",
	":face_with_rolling_eyes:": "🙄",
	":grimacing_face:": "😬",
	":face_exhaling:": "😮‍💨",
	":lying_face:": "🤥",
	":shaking_face:": "🫨",
	":relieved_face:": "😌",
	":pensive_face:": "😔",
	":sleepy_face:": "😪",
	":drooling_face:": "🤤",
	":sleeping_face:": "😴",
	":face_with_medical_mask:": "😷",
	":face_with_thermometer:": "🤒",
	":face_with_head_bandage:": "🤕",
	":nauseated_face:": "🤢",
	":face_vomiting:": "🤮",
	":sneezing_face:": "🤧",
	":hot_face:": "🥵",
	":cold_face:": "🥶",
	":woozy_face:": "🥴",
	":face_with_crossed_out_eyes:": "😵",
	":face_with_spiral_eyes:": "😵‍💫",
	":exploding_head:": "🤯",
	":cowboy_hat_face:": "🤠",
	":partying_face:": "🥳",
	":disguised_face:": "🥸",
	":smiling_face_with_sunglasses:": "😎",
	":nerd_face:": "🤓",
	":face_with_monocle:": "🧐",
	":confused_face:": "😕",
	":face_with_diagonal_mouth:": "🫤",
	":worried_face:": "😟",
	":slightly_frowning_face:": "🙁",
	":frowning_face:": "☹️",
	":face_with_open_mouth:": "😮",
	":hushed_face:": "😯",
	":astonished_face:": "😲",
	":flushed_face:": "😳",
	":pleading_face:": "🥺",
	":face_holding_back_tears:": "🥹",
	":frowning_face_with_open_mouth:": "😦",
	":anguished_face:": "😧",
	":fearful_face:": "😨",
	":anxious_face_with_sweat:": "😰",
	":sad_but_relieved_face:": "😥",
	":crying_face:": "😢",
	":loudly_crying_face:": "😭",
	":face_screaming_in_fear:": "😱",
	":confounded_face:": "😖",
	":persevering_face:": "😣",
	":disappointed_face:": "😞",
	":downcast_face_with_sweat:": "😓",
	":weary_face:": "😩",
	":tired_face:": "😫",
	":yawning_face:": "🥱",
	":face_with_steam_from_nose:": "😤",
	":enraged_face:": "😡",
	":angry_face:": "😠",
	":face_with_symbols_on_mouth:": "🤬",
	":smiling_face_with_horns:": "😈",
	":angry_face_with_horns:": "👿",
	":skull:": "💀",
	":skull_and_crossbones:": "☠️",
	":pile_of_poo:": "💩",
	":clown_face:": "🤡",
	":ogre:": "👹",
	":goblin:": "👺",
	":ghost:": "👻",
	":alien:": "👽",
	":alien_monster:": "👾",
	":robot:": "🤖",
	":grinning_cat:": "😺",
	":grinning_cat_with_smiling_eyes:": "😸",
	":cat_with_tears_of_joy:": "😹",
	":smiling_cat_with_heart_eyes:": "😻",
	":cat_with_wry_smile:": "😼",
	":kissing_cat:": "😽",
	":weary_cat:": "🙀",
	":crying_cat:": "😿",
	":pouting_cat:": "😾",
	":see_no_evil_monkey:": "🙈",
	":hear_no_evil_monkey:": "🙉",
	":speak_no_evil_monkey:": "🙊",
	":love_letter:": "💌",
	":heart_with_arrow:": "💘",
	":heart_with_ribbon:": "💝",
	":sparkling_heart:": "💖",
	":growing_heart:": "💗",
	":beating_heart:": "💓",
	":revolving_hearts:": "💞",
	":two_hearts:": "💕",
	":heart_decoration:": "💟",
	":heart_exclamation:": "❣️",
	":broken_heart:": "💔",
	":heart_on_fire:": "❤️‍🔥",
	":mending_heart:": "❤️‍🩹",
	":red_heart:": "❤️",
	":pink_heart:": "🩷",
	":orange_heart:": "🧡",
	":yellow_heart:": "💛",
	":green_heart:": "💚",
	":blue_heart:": "💙",
	":light_blue_heart:": "🩵",
	":purple_heart:": "💜",
	":brown_heart:": "🤎",
	":black_heart:": "🖤",
	":grey_heart:": "🩶",
	":white_heart:": "🤍",
	":kiss_mark:": "💋",
	":hundred_points:": "💯",
	":anger_symbol:": "💢",
	":collision:": "💥",
	":dizzy:": "💫",
	":sweat_droplets:": "💦",
	":dashing_away:": "💨",
	":hole:": "🕳️",
	":speech_balloon:": "💬",
	":eye_in_speech_bubble:": "👁️‍🗨️",
	":left_speech_bubble:": "🗨️",
	":right_anger_bubble:": "🗯️",
	":thought_balloon:": "💭",
	":zzz:": "💤",
	":waving_hand:": "👋",
	":raised_back_of_hand:": "🤚",
	":hand_with_fingers_splayed:": "🖐️",
	":raised_hand:": "✋",
	":vulcan_salute:": "🖖",
	":rightwards_hand:": "🫱",
	":leftwards_hand:": "🫲",
	":palm_down_hand:": "🫳",
	":palm_up_hand:": "🫴",
	":leftwards_pushing_hand:": "🫷",
	":rightwards_pushing_hand:": "🫸",
	":ok_hand:": "👌",
	":pinched_fingers:": "🤌",
	":pinching_hand:": "🤏",
	":victory_hand:": "✌️",
	":crossed_fingers:": "🤞",
	":hand_with_index_finger_and_thumb_crossed:": "🫰",
	":love_you_gesture:": "🤟",
	":sign_of_the_horns:": "🤘",
	":call_me_hand:": "🤙",
	":backhand_index_pointing_left:": "👈",
	":backhand_index_pointing_right:": "👉",
	":backhand_index_pointing_up:": "👆",
	":middle_finger:": "🖕",
	":backhand_index_pointing_down:": "👇",
	":index_pointing_up:": "☝️",
	":index_pointing_at_the_viewer:": "🫵",
	":thumbs_up:": "👍",
	":thumbs_down:": "👎",
	":raised_fist:": "✊",
	":oncoming_fist:": "👊",
	":left_facing_fist:": "🤛",
	":right_facing_fist:": "🤜",
	":clapping_hands:": "👏",
	":raising_hands:": "🙌",
	":heart_hands:": "🫶",
	":open_hands:": "👐",
	":palms_up_together:": "🤲",
	":handshake:": "🤝",
	":folded_hands:": "🙏",
	":writing_hand:": "✍️",
	":nail_polish:": "💅",
	":selfie:": "🤳",
	":flexed_biceps:": "💪",
	":mechanical_arm:": "🦾",
	":mechanical_leg:": "🦿",
	":leg:": "🦵",
	":foot:": "🦶",
	":ear:": "👂",
	":ear_with_hearing_aid:": "🦻",
	":nose:": "👃",
	":brain:": "🧠",
	":anatomical_heart:": "🫀",
	":lungs:": "🫁",
	":tooth:": "🦷",
	":bone:": "🦴",
	":eyes:": "👀",
	":eye:": "👁️",
	":tongue:": "👅",
	":mouth:": "👄",
	":biting_lip:": "🫦",
	":baby:": "👶",
	":child:": "🧒",
	":boy:": "👦",
	":girl:": "👧",
	":person:": "🧑",
	":person_blond_hair:": "👱",
	":man:": "👨",
	":person_beard:": "🧔",
	":man_beard:": "🧔‍♂️",
	":woman_beard:": "🧔‍♀️",
	":man_red_hair:": "👨‍🦰",
	":man_curly_hair:": "👨‍🦱",
	":man_white_hair:": "👨‍🦳",
	":man_bald:": "👨‍🦲",
	":woman:": "👩",
	":woman_red_hair:": "👩‍🦰",
	":person_red_hair:": "🧑‍🦰",
	":woman_curly_hair:": "👩‍🦱",
	":person_curly_hair:": "🧑‍🦱",
	":woman_white_hair:": "👩‍🦳",
	":person_white_hair:": "🧑‍🦳",
	":woman_bald:": "👩‍🦲",
	":person_bald:": "🧑‍🦲",
	":woman_blond_hair:": "👱‍♀️",
	":man_blond_hair:": "👱‍♂️",
	":older_person:": "🧓",
	":old_man:": "👴",
	":old_woman:": "👵",
	":person_frowning:": "🙍",
	":man_frowning:": "🙍‍♂️",
	":woman_frowning:": "🙍‍♀️",
	":person_pouting:": "🙎",
	":man_pouting:": "🙎‍♂️",
	":woman_pouting:": "🙎‍♀️",
	":person_gesturing_no:": "🙅",
	":man_gesturing_no:": "🙅‍♂️",
	":woman_gesturing_no:": "🙅‍♀️",
	":person_gesturing_ok:": "🙆",
	":man_gesturing_ok:": "🙆‍♂️",
	":woman_gesturing_ok:": "🙆‍♀️",
	":person_tipping_hand:": "💁",
	":man_tipping_hand:": "💁‍♂️",
	":woman_tipping_hand:": "💁‍♀️",
	":person_raising_hand:": "🙋",
	":man_raising_hand:": "🙋‍♂️",
	":woman_raising_hand:": "🙋‍♀️",
	":deaf_person:": "🧏",
	":deaf_man:": "🧏‍♂️",
	":deaf_woman:": "🧏‍♀️",
	":person_bowing:": "🙇",
	":man_bowing:": "🙇‍♂️",
	":woman_bowing:": "🙇‍♀️",
	":person_facepalming:": "🤦",
	":man_facepalming:": "🤦‍♂️",
	":woman_facepalming:": "🤦‍♀️",
	":person_shrugging:": "🤷",
	":man_shrugging:": "🤷‍♂️",
	":woman_shrugging:": "🤷‍♀️",
	":health_worker:": "🧑‍⚕️",
	":man_health_worker:": "👨‍⚕️",
	":woman_health_worker:": "👩‍⚕️",
	":student:": "🧑‍🎓",
	":man_student:": "👨‍🎓",
	":woman_student:": "👩‍🎓",
	":teacher:": "🧑‍🏫",
	":man_teacher:": "👨‍🏫",
	":woman_teacher:": "👩‍🏫",
	":judge:": "🧑‍⚖️",
	":man_judge:": "👨‍⚖️",
	":woman_judge:": "👩‍⚖️",
	":farmer:": "🧑‍🌾",
	":man_farmer:": "👨‍🌾",
	":woman_farmer:": "👩‍🌾",
	":cook:": "🧑‍🍳",
	":man_cook:": "👨‍🍳",
	":woman_cook:": "👩‍🍳",
	":mechanic:": "🧑‍🔧",
	":man_mechanic:": "👨‍🔧",
	":woman_mechanic:": "👩‍🔧",
	":factory_worker:": "🧑‍🏭",
	":man_factory_worker:": "👨‍🏭",
	":woman_factory_worker:": "👩‍🏭",
	":office_worker:": "🧑‍💼",
	":man_office_worker:": "👨‍💼",
	":woman_office_worker:": "👩‍💼",
	":scientist:": "🧑‍🔬",
	":man_scientist:": "👨‍🔬",
	":woman_scientist:": "👩‍🔬",
	":technologist:": "🧑‍💻",
	":man_technologist:": "👨‍💻",
	":woman_technologist:": "👩‍💻",
	":singer:": "🧑‍🎤",
	":man_singer:": "👨‍🎤",
	":woman_singer:": "👩‍🎤",
	":artist:": "🧑‍🎨",
	":man_artist:": "👨‍🎨",
	":woman_artist:": "👩‍🎨",
	":pilot:": "🧑‍✈️",
	":man_pilot:": "👨‍✈️",
	":woman_pilot:": "👩‍✈️",
	":astronaut:": "🧑‍🚀",
	":man_astronaut:": "👨‍🚀",
	":woman_astronaut:": "👩‍🚀",
	":firefighter:": "🧑‍🚒",
	":man_firefighter:": "👨‍🚒",
	":woman_firefighter:": "👩‍🚒",
	":police_officer:": "👮",
	":man_police_officer:": "👮‍♂️",
	":woman_police_officer:": "👮‍♀️",
	":detective:": "🕵️",
	":man_detective:": "🕵️‍♂️",
	":woman_detective:": "🕵️‍♀️",
	":guard:": "💂",
	":man_guard:": "💂‍♂️",
	":woman_guard:": "💂‍♀️",
	":ninja:": "🥷",
	":construction_worker:": "👷",
	":man_construction_worker:": "👷‍♂️",
	":woman_construction_worker:": "👷‍♀️",
	":person_with_crown:": "🫅",
	":prince:": "🤴",
	":princess:": "👸",
	":person_wearing_turban:": "👳",
	":man_wearing_turban:": "👳‍♂️",
	":woman_wearing_turban:": "👳‍♀️",
	":person_with_skullcap:": "👲",
	":woman_with_headscarf:": "🧕",
	":person_in_tuxedo:": "🤵",
	":man_in_tuxedo:": "🤵‍♂️",
	":woman_in_tuxedo:": "🤵‍♀️",
	":person_with_veil:": "👰",
	":man_with_veil:": "👰‍♂️",
	":woman_with_veil:": "👰‍♀️",
	":pregnant_woman:": "🤰",
	":pregnant_man:": "🫃",
	":pregnant_person:": "🫄",
	":breast_feeding:": "🤱",
	":woman_feeding_baby:": "👩‍🍼",
	":man_feeding_baby:": "👨‍🍼",
	":person_feeding_baby:": "🧑‍🍼",
	":baby_angel:": "👼",
	":santa_claus:": "🎅",
	":mrs_claus:": "🤶",
	":mx_claus:": "🧑‍🎄",
	":superhero:": "🦸",
	":man_superhero:": "🦸‍♂️",
	":woman_superhero:": "🦸‍♀️",
	":supervillain:": "🦹",
	":man_supervillain:": "🦹‍♂️",
	":woman_supervillain:": "🦹‍♀️",
	":mage:": "🧙",
	":man_mage:": "🧙‍♂️",
	":woman_mage:": "🧙‍♀️",
	":fairy:": "🧚",
	":man_fairy:": "🧚‍♂️",
	":woman_fairy:": "🧚‍♀️",
	":vampire:": "🧛",
	":man_vampire:": "🧛‍♂️",
	":woman_vampire:": "🧛‍♀️",
	":merperson:": "🧜",
	":merman:": "🧜‍♂️",
	":mermaid:": "🧜‍♀️",
	":elf:": "🧝",
	":man_elf:": "🧝‍♂️",
	":woman_elf:": "🧝‍♀️",
	":genie:": "🧞",
	":man_genie:": "🧞‍♂️",
	":woman_genie:": "🧞‍♀️",
	":zombie:": "🧟",
	":man_zombie:": "🧟‍♂️",
	":woman_zombie:": "🧟‍♀️",
	":troll:": "🧌",
	":person_getting_massage:": "💆",
	":man_getting_massage:": "💆‍♂️",
	":woman_getting_massage:": "💆‍♀️",
	":person_getting_haircut:": "💇",
	":man_getting_haircut:": "💇‍♂️",
	":woman_getting_haircut:": "💇‍♀️",
	":person_walking:": "🚶",
	":man_walking:": "🚶‍♂️",
	":woman_walking:": "🚶‍♀️",
	":person_standing:": "🧍",
	":man_standing:": "🧍‍♂️",
	":woman_standing:": "🧍‍♀️",
	":person_kneeling:": "🧎",
	":man_kneeling:": "🧎‍♂️",
	":woman_kneeling:": "🧎‍♀️",
	":person_with_white_cane:": "🧑‍🦯",
	":man_with_white_cane:": "👨‍🦯",
	":woman_with_white_cane:": "👩‍🦯",
	":person_in_motorized_wheelchair:": "🧑‍🦼",
	":man_in_motorized_wheelchair:": "👨‍🦼",
	":woman_in_motorized_wheelchair:": "👩‍🦼",
	":person_in_manual_wheelchair:": "🧑‍🦽",
	":man_in_manual_wheelchair:": "👨‍🦽",
	":woman_in_manual_wheelchair:": "👩‍🦽",
	":person_running:": "🏃",
	":man_running:": "🏃‍♂️",
	":woman_running:": "🏃‍♀️",
	":woman_dancing:": "💃",
	":man_dancing:": "🕺",
	":person_in_suit_levitating:": "🕴️",
	":people_with_bunny_ears:": "👯",
	":men_with_bunny_ears:": "👯‍♂️",
	":women_with_bunny_ears:": "👯‍♀️",
	":person_in_steamy_room:": "🧖",
	":man_in_steamy_room:": "🧖‍♂️",
	":woman_in_steamy_room:": "🧖‍♀️",
	":person_climbing:": "🧗",
	":man_climbing:": "🧗‍♂️",
	":woman_climbing:": "🧗‍♀️",
	":person_fencing:": "🤺",
	":horse_racing:": "🏇",
	":skier:": "⛷️",
	":snowboarder:": "🏂",
	":person_golfing:": "🏌️",
	":man_golfing:": "🏌️‍♂️",
	":woman_golfing:": "🏌️‍♀️",
	":person_surfing:": "🏄",
	":man_surfing:": "🏄‍♂️",
	":woman_surfing:": "🏄‍♀️",
	":person_rowing_boat:": "🚣",
	":man_rowing_boat:": "🚣‍♂️",
	":woman_rowing_boat:": "🚣‍♀️",
	":person_swimming:": "🏊",
	":man_swimming:": "🏊‍♂️",
	":woman_swimming:": "🏊‍♀️",
	":person_bouncing_ball:": "⛹️",
	":man_bouncing_ball:": "⛹️‍♂️",
	":woman_bouncing_ball:": "⛹️‍♀️",
	":person_lifting_weights:": "🏋️",
	":man_lifting_weights:": "🏋️‍♂️",
	":woman_lifting_weights:": "🏋️‍♀️",
	":person_biking:": "🚴",
	":man_biking:": "🚴‍♂️",
	":woman_biking:": "🚴‍♀️",
	":person_mountain_biking:": "🚵",
	":man_mountain_biking:": "🚵‍♂️",
	":woman_mountain_biking:": "🚵‍♀️",
	":person_cartwheeling:": "🤸",
	":man_cartwheeling:": "🤸‍♂️",
	":woman_cartwheeling:": "🤸‍♀️",
	":people_wrestling:": "🤼",
	":men_wrestling:": "🤼‍♂️",
	":women_wrestling:": "🤼‍♀️",
	":person_playing_water_polo:": "🤽",
	":man_playing_water_polo:": "🤽‍♂️",
	":woman_playing_water_polo:": "🤽‍♀️",
	":person_playing_handball:": "🤾",
	":man_playing_handball:": "🤾‍♂️",
	":woman_playing_handball:": "🤾‍♀️",
	":person_juggling:": "🤹",
	":man_juggling:": "🤹‍♂️",
	":woman_juggling:": "🤹‍♀️",
	":person_in_lotus_position:": "🧘",
	":man_in_lotus_position:": "🧘‍♂️",
	":woman_in_lotus_position:": "🧘‍♀️",
	":person_taking_bath:": "🛀",
	":person_in_bed:": "🛌",
	":people_holding_hands:": "🧑‍🤝‍🧑",
	":women_holding_hands:": "👭",
	":woman_and_man_holding_hands:": "👫",
	":men_holding_hands:": "👬",
	":kiss:": "💏",
	":kiss_woman_man:": "👩‍❤️‍💋‍👨",
	":kiss_man_man:": "👨‍❤️‍💋‍👨",
	":kiss_woman_woman:": "👩‍❤️‍💋‍👩",
	":couple_with_heart:": "💑",
	":couple_with_heart_woman_man:": "👩‍❤️‍👨",
	":couple_with_heart_man_man:": "👨‍❤️‍👨",
	":couple_with_heart_woman_woman:": "👩‍❤️‍👩",
	":family:": "👪",
	":family_man_woman_boy:": "👨‍👩‍👦",
	":family_man_woman_girl:": "👨‍👩‍👧",
	":family_man_woman_girl_boy:": "👨‍👩‍👧‍👦",
	":family_man_woman_boy_boy:": "👨‍👩‍👦‍👦",
	":family_man_woman_girl_girl:": "👨‍👩‍👧‍👧",
	":family_man_man_boy:": "👨‍👨‍👦",
	":family_man_man_girl:": "👨‍👨‍👧",
	":family_man_man_girl_boy:": "👨‍👨‍👧‍👦",
	":family_man_man_boy_boy:": "👨‍👨‍👦‍👦",
	":family_man_man_girl_girl:": "👨‍👨‍👧‍👧",
	":family_woman_woman_boy:": "👩‍👩‍👦",
	":family_woman_woman_girl:": "👩‍👩‍👧",
	":family_woman_woman_girl_boy:": "👩‍👩‍👧‍👦",
	":family_woman_woman_boy_boy:": "👩‍👩‍👦‍👦",
	":family_woman_woman_girl_girl:": "👩‍👩‍👧‍👧",
	":family_man_boy:": "👨‍👦",
	":family_man_boy_boy:": "👨‍👦‍👦",
	":family_man_girl:": "👨‍👧",
	":family_man_girl_boy:": "👨‍👧‍👦",
	":family_man_girl_girl:": "👨‍👧‍👧",
	":family_woman_boy:": "👩‍👦",
	":family_woman_boy_boy:": "👩‍👦‍👦",
	":family_woman_girl:": "👩‍👧",
	":family_woman_girl_boy:": "👩‍👧‍👦",
	":family_woman_girl_girl:": "👩‍👧‍👧",
	":speaking_head:": "🗣️",
	":bust_in_silhouette:": "👤",
	":busts_in_silhouette:": "👥",
	":people_hugging:": "🫂",
	":footprints:": "👣",
	":monkey_face:": "🐵",
	":monkey:": "🐒",
	":gorilla:": "🦍",
	":orangutan:": "🦧",
	":dog_face:": "🐶",
	":dog:": "🐕",
	":guide_dog:": "🦮",
	":service_dog:": "🐕‍🦺",
	":poodle:": "🐩",
	":wolf:": "🐺",
	":fox:": "🦊",
	":raccoon:": "🦝",
	":cat_face:": "🐱",
	":cat:": "🐈",
	":black_cat:": "🐈‍⬛",
	":lion:": "🦁",
	":tiger_face:": "🐯",
	":tiger:": "🐅",
	":leopard:": "🐆",
	":horse_face:": "🐴",
	":moose:": "🫎",
	":donkey:": "🫏",
	":horse:": "🐎",
	":unicorn:": "🦄",
	":zebra:": "🦓",
	":deer:": "🦌",
	":bison:": "🦬",
	":cow_face:": "🐮",
	":ox:": "🐂",
	":water_buffalo:": "🐃",
	":cow:": "🐄",
	":pig_face:": "🐷",
	":pig:": "🐖",
	":boar:": "🐗",
	":pig_nose:": "🐽",
	":ram:": "🐏",
	":ewe:": "🐑",
	":goat:": "🐐",
	":camel:": "🐪",
	":two_hump_camel:": "🐫",
	":llama:": "🦙",
	":giraffe:": "🦒",
	":elephant:": "🐘",
	":mammoth:": "🦣",
	":rhinoceros:": "🦏",
	":hippopotamus:": "🦛",
	":mouse_face:": "🐭",
	":mouse:": "🐁",
	":rat:": "🐀",
	":hamster:": "🐹",
	":rabbit_face:": "🐰",
	":rabbit:": "🐇",
	":chipmunk:": "🐿️",
	":beaver:": "🦫",
	":hedgehog:": "🦔",
	":bat:": "🦇",
	":bear:": "🐻",
	":polar_bear:": "🐻‍❄️",
	":koala:": "🐨",
	":panda:": "🐼",
	":sloth:": "🦥",
	":otter:": "🦦",
	":skunk:": "🦨",
	":kangaroo:": "🦘",
	":badger:": "🦡",
	":paw_prints:": "🐾",
	":turkey:": "🦃",
	":chicken:": "🐔",
	":rooster:": "🐓",
	":hatching_chick:": "🐣",
	":baby_chick:": "🐤",
	":front_facing_baby_chick:": "🐥",
	":bird:": "🐦",
	":penguin:": "🐧",
	":dove:": "🕊️",
	":eagle:": "🦅",
	":duck:": "🦆",
	":swan:": "🦢",
	":owl:": "🦉",
	":dodo:": "🦤",
	":feather:": "🪶",
	":flamingo:": "🦩",
	":peacock:": "🦚",
	":parrot:": "🦜",
	":wing:": "🪽",
	":black_bird:": "🐦‍⬛",
	":goose:": "🪿",
	":frog:": "🐸",
	":crocodile:": "🐊",
	":turtle:": "🐢",
	":lizard:": "🦎",
	":snake:": "🐍",
	":dragon_face:": "🐲",
	":dragon:": "🐉",
	":sauropod:": "🦕",
	":t_rex:": "🦖",
	":spouting_whale:": "🐳",
	":whale:": "🐋",
	":dolphin:": "🐬",
	":seal:": "🦭",
	":fish:": "🐟",
	":tropical_fish:": "🐠",
	":blowfish:": "🐡",
	":shark:": "🦈",
	":octopus:": "🐙",
	":spiral_shell:": "🐚",
	":coral:": "🪸",
	":jellyfish:": "🪼",
	":snail:": "🐌",
	":butterfly:": "🦋",
	":bug:": "🐛",
	":ant:": "🐜",
	":honeybee:": "🐝",
	":beetle:": "🪲",
	":lady_beetle:": "🐞",
	":cricket:": "🦗",
	":cockroach:": "🪳",
	":spider:": "🕷️",
	":spider_web:": "🕸️",
	":scorpion:": "🦂",
	":mosquito:": "🦟",
	":fly:": "🪰",
	":worm:": "🪱",
	":microbe:": "🦠",
	":bouquet:": "💐",
	":cherry_blossom:": "🌸",
	":white_flower:": "💮",
	":lotus:": "🪷",
	":rosette:": "🏵️",
	":rose:": "🌹",
	":wilted_flower:": "🥀",
	":hibiscus:": "🌺",
	":sunflower:": "🌻",
	":blossom:": "🌼",
	":tulip:": "🌷",
	":hyacinth:": "🪻",
	":seedling:": "🌱",
	":potted_plant:": "🪴",
	":evergreen_tree:": "🌲",
	":deciduous_tree:": "🌳",
	":palm_tree:": "🌴",
	":cactus:": "🌵",
	":sheaf_of_rice:": "🌾",
	":herb:": "🌿",
	":shamrock:": "☘️",
	":four_leaf_clover:": "🍀",
	":maple_leaf:": "🍁",
	":fallen_leaf:": "🍂",
	":leaf_fluttering_in_wind:": "🍃",
	":empty_nest:": "🪹",
	":nest_with_eggs:": "🪺",
	":mushroom:": "🍄",
	":grapes:": "🍇",
	":melon:": "🍈",
	":watermelon:": "🍉",
	":tangerine:": "🍊",
	":lemon:": "🍋",
	":banana:": "🍌",
	":pineapple:": "🍍",
	":mango:": "🥭",
	":red_apple:": "🍎",
	":green_apple:": "🍏",
	":pear:": "🍐",
	":peach:": "🍑",
	":cherries:": "🍒",
	":strawberry:": "🍓",
	":blueberries:": "🫐",
	":kiwi_fruit:": "🥝",
	":tomato:": "🍅",
	":olive:": "🫒",
	":coconut:": "🥥",
	":avocado:": "🥑",
	":eggplant:": "🍆",
	":potato:": "🥔",
	":carrot:": "🥕",
	":ear_of_corn:": "🌽",
	":hot_pepper:": "🌶️",
	":bell_pepper:": "🫑",
	":cucumber:": "🥒",
	":leafy_green:": "🥬",
	":broccoli:": "🥦",
	":garlic:": "🧄",
	":onion:": "🧅",
	":peanuts:": "🥜",
	":beans:": "🫘",
	":chestnut:": "🌰",
	":ginger_root:": "🫚",
	":pea_pod:": "🫛",
	":bread:": "🍞",
	":croissant:": "🥐",
	":baguette_bread:": "🥖",
	":flatbread:": "🫓",
	":pretzel:": "🥨",
	":bagel:": "🥯",
	":pancakes:": "🥞",
	":waffle:": "🧇",
	":cheese_wedge:": "🧀",
	":meat_on_bone:": "🍖",
	":poultry_leg:": "🍗",
	":cut_of_meat:": "🥩",
	":bacon:": "🥓",
	":hamburger:": "🍔",
	":french_fries:": "🍟",
	":pizza:": "🍕",
	":hot_dog:": "🌭",
	":sandwich:": "🥪",
	":taco:": "🌮",
	":burrito:": "🌯",
	":tamale:": "🫔",
	":stuffed_flatbread:": "🥙",
	":falafel:": "🧆",
	":egg:": "🥚",
	":cooking:": "🍳",
	":shallow_pan_of_food:": "🥘",
	":pot_of_food:": "🍲",
	":fondue:": "🫕",
	":bowl_with_spoon:": "🥣",
	":green_salad:": "🥗",
	":popcorn:": "🍿",
	":butter:": "🧈",
	":salt:": "🧂",
	":canned_food:": "🥫",
	":bento_box:": "🍱",
	":rice_cracker:": "🍘",
	":rice_ball:": "🍙",
	":cooked_rice:": "🍚",
	":curry_rice:": "🍛",
	":steaming_bowl:": "🍜",
	":spaghetti:": "🍝",
	":roasted_sweet_potato:": "🍠",
	":oden:": "🍢",
	":sushi:": "🍣",
	":fried_shrimp:": "🍤",
	":fish_cake_with_swirl:": "🍥",
	":moon_cake:": "🥮",
	":dango:": "🍡",
	":dumpling:": "🥟",
	":fortune_cookie:": "🥠",
	":takeout_box:": "🥡",
	":crab:": "🦀",
	":lobster:": "🦞",
	":shrimp:": "🦐",
	":squid:": "🦑",
	":oyster:": "🦪",
	":soft_ice_cream:": "🍦",
	":shaved_ice:": "🍧",
	":ice_cream:": "🍨",
	":doughnut:": "🍩",
	":cookie:": "🍪",
	":birthday_cake:": "🎂",
	":shortcake:": "🍰",
	":cupcake:": "🧁",
	":pie:": "🥧",
	":chocolate_bar:": "🍫",
	":candy:": "🍬",
	":lollipop:": "🍭",
	":custard:": "🍮",
	":honey_pot:": "🍯",
	":baby_bottle:": "🍼",
	":glass_of_milk:": "🥛",
	":hot_beverage:": "☕",
	":teapot:": "🫖",
	":teacup_without_handle:": "🍵",
	":sake:": "🍶",
	":bottle_with_popping_cork:": "🍾",
	":wine_glass:": "🍷",
	":cocktail_glass:": "🍸",
	":tropical_drink:": "🍹",
	":beer_mug:": "🍺",
	":clinking_beer_mugs:": "🍻",
	":clinking_glasses:": "🥂",
	":tumbler_glass:": "🥃",
	":pouring_liquid:": "🫗",
	":cup_with_straw:": "🥤",
	":bubble_tea:": "🧋",
	":beverage_box:": "🧃",
	":mate:": "🧉",
	":ice:": "🧊",
	":chopsticks:": "🥢",
	":fork_and_knife_with_plate:": "🍽️",
	":fork_and_knife:": "🍴",
	":spoon:": "🥄",
	":kitchen_knife:": "🔪",
	":jar:": "🫙",
	":amphora:": "🏺",
	":globe_showing_europe_africa:": "🌍",
	":globe_showing_americas:": "🌎",
	":globe_showing_asia_australia:": "🌏",
	":globe_with_meridians:": "🌐",
	":world_map:": "🗺️",
	":map_of_japan:": "🗾",
	":compass:": "🧭",
	":snow_capped_mountain:": "🏔️",
	":mountain:": "⛰️",
	":volcano:": "🌋",
	":mount_fuji:": "🗻",
	":camping:": "🏕️",
	":beach_with_umbrella:": "🏖️",
	":desert:": "🏜️",
	":desert_island:": "🏝️",
	":national_park:": "🏞️",
	":stadium:": "🏟️",
	":classical_building:": "🏛️",
	":building_construction:": "🏗️",
	":brick:": "🧱",
	":rock:": "🪨",
	":wood:": "🪵",
	":hut:": "🛖",
	":houses:": "🏘️",
	":derelict_house:": "🏚️",
	":house:": "🏠",
	":house_with_garden:": "🏡",
	":office_building:": "🏢",
	":japanese_post_office:": "🏣",
	":post_office:": "🏤",
	":hospital:": "🏥",
	":bank:": "🏦",
	":hotel:": "🏨",
	":love_hotel:": "🏩",
	":convenience_store:": "🏪",
	":school:": "🏫",
	":department_store:": "🏬",
	":factory:": "🏭",
	":japanese_castle:": "🏯",
	":castle:": "🏰",
	":wedding:": "💒",
	":tokyo_tower:": "🗼",
	":statue_of_liberty:": "🗽",
	":church:": "⛪",
	":mosque:": "🕌",
	":hindu_temple:": "🛕",
	":synagogue:": "🕍",
	":shinto_shrine:": "⛩️",
	":kaaba:": "🕋",
	":fountain:": "⛲",
	":tent:": "⛺",
	":foggy:": "🌁",
	":night_with_stars:": "🌃",
	":cityscape:": "🏙️",
	":sunrise_over_mountains:": "🌄",
	":sunrise:": "🌅",
	":cityscape_at_dusk:": "🌆",
	":sunset:": "🌇",
	":bridge_at_night:": "🌉",
	":hot_springs:": "♨️",
	":carousel_horse:": "🎠",
	":playground_slide:": "🛝",
	":ferris_wheel:": "🎡",
	":roller_coaster:": "🎢",
	":barber_pole:": "💈",
	":circus_tent:": "🎪",
	":locomotive:": "🚂",
	":railway_car:": "🚃",
	":high_speed_train:": "🚄",
	":bullet_train:": "🚅",
	":train:": "🚆",
	":metro:": "🚇",
	":light_rail:": "🚈",
	":station:": "🚉",
	":tram:": "🚊",
	":monorail:": "🚝",
	":mountain_railway:": "🚞",
	":tram_car:": "🚋",
	":bus:": "🚌",
	":oncoming_bus:": "🚍",
	":trolleybus:": "🚎",
	":minibus:": "🚐",
	":ambulance:": "🚑",
	":fire_engine:": "🚒",
	":police_car:": "🚓",
	":oncoming_police_car:": "🚔",
	":taxi:": "🚕",
	":oncoming_taxi:": "🚖",
	":automobile:": "🚗",
	":oncoming_automobile:": "🚘",
	":sport_utility_vehicle:": "🚙",
	":pickup_truck:": "🛻",
	":delivery_truck:": "🚚",
	":articulated_lorry:": "🚛",
	":tractor:": "🚜",
	":racing_car:": "🏎️",
	":motorcycle:": "🏍️",
	":motor_scooter:": "🛵",
	":manual_wheelchair:": "🦽",
	":motorized_wheelchair:": "🦼",
	":auto_rickshaw:": "🛺",
	":bicycle:": "🚲",
	":kick_scooter:": "🛴",
	":skateboard:": "🛹",
	":roller_skate:": "🛼",
	":bus_stop:": "🚏",
	":motorway:": "🛣️",
	":railway_track:": "🛤️",
	":oil_drum:": "🛢️",
	":fuel_pump:": "⛽",
	":wheel:": "🛞",
	":police_car_light:": "🚨",
	":horizontal_traffic_light:": "🚥",
	":vertical_traffic_light:": "🚦",
	":stop_sign:": "🛑",
	":construction:": "🚧",
	":anchor:": "⚓",
	":ring_buoy:": "🛟",
	":sailboat:": "⛵",
	":canoe:": "🛶",
	":speedboat:": "🚤",
	":passenger_ship:": "🛳️",
	":ferry:": "⛴️",
	":motor_boat:": "🛥️",
	":ship:": "🚢",
	":airplane:": "✈️",
	":small_airplane:": "🛩️",
	":airplane_departure:": "🛫",
	":airplane_arrival:": "🛬",
	":parachute:": "🪂",
	":seat:": "💺",
	":helicopter:": "🚁",
	":suspension_railway:": "🚟",
	":mountain_cableway:": "🚠",
	":aerial_tramway:": "🚡",
	":satellite:": "🛰️",
	":rocket:": "🚀",
	":flying_saucer:": "🛸",
	":bellhop_bell:": "🛎️",
	":luggage:": "🧳",
	":hourglass_done:": "⌛",
	":hourglass_not_done:": "⏳",
	":watch:": "⌚",
	":alarm_clock:": "⏰",
	":stopwatch:": "⏱️",
	":timer_clock:": "⏲️",
	":mantelpiece_clock:": "🕰️",
	":twelve_o_clock:": "🕛",
	":twelve_thirty:": "🕧",
	":one_o_clock:": "🕐",
	":one_thirty:": "🕜",
	":two_o_clock:": "🕑",
	":two_thirty:": "🕝",
	":three_o_clock:": "🕒",
	":three_thirty:": "🕞",
	":four_o_clock:": "🕓",
	":four_thirty:": "🕟",
	":five_o_clock:": "🕔",
	":five_thirty:": "🕠",
	":six_o_clock:": "🕕",
	":six_thirty:": "🕡",
	":seven_o_clock:": "🕖",
	":seven_thirty:": "🕢",
	":eight_o_clock:": "🕗",
	":eight_thirty:": "🕣",
	":nine_o_clock:": "🕘",
	":nine_thirty:": "🕤",
	":ten_o_clock:": "🕙",
	":ten_thirty:": "🕥",
	":eleven_o_clock:": "🕚",
	":eleven_thirty:": "🕦",
	":new_moon:": "🌑",
	":waxing_crescent_moon:": "🌒",
	":first_quarter_moon:": "🌓",
	":waxing_gibbous_moon:": "🌔",
	":full_moon:": "🌕",
	":waning_gibbous_moon:": "🌖",
	":last_quarter_moon:": "🌗",
	":waning_crescent_moon:": "🌘",
	":crescent_moon:": "🌙",
	":new_moon_face:": "🌚",
	":first_quarter_moon_face:": "🌛",
	":last_quarter_moon_face:": "🌜",
	":thermometer:": "🌡️",
	":sun:": "☀️",
	":full_moon_face:": "🌝",
	":sun_with_face:": "🌞",
	":ringed_planet:": "🪐",
	":star:": "⭐",
	":glowing_star:": "🌟",
	":shooting_star:": "🌠",
	":milky_way:": "🌌",
	":cloud:": "☁️",
	":sun_behind_cloud:": "⛅",
	":cloud_with_lightning_and_rain:": "⛈️",
	":sun_behind_small_cloud:": "🌤️",
	":sun_behind_large_cloud:": "🌥️",
	":sun_behind_rain_cloud:": "🌦️",
	":cloud_with_rain:": "🌧️",
	":cloud_with_snow:": "🌨️",
	":cloud_with_lightning:": "🌩️",
	":tornado:": "🌪️",
	":fog:": "🌫️",
	":wind_face:": "🌬️",
	":cyclone:": "🌀",
	":rainbow:": "🌈",
	":closed_umbrella:": "🌂",
	":umbrella:": "☂️",
	":umbrella_with_rain_drops:": "☔",
	":umbrella_on_ground:": "⛱️",
	":high_voltage:": "⚡",
	":snowflake:": "❄️",
	":snowman:": "☃️",
	":snowman_without_snow:": "⛄",
	":comet:": "☄️",
	":fire:": "🔥",
	":droplet:": "💧",
	":water_wave:": "🌊",
	":jack_o_lantern:": "🎃",
	":christmas_tree:": "🎄",
	":fireworks:": "🎆",
	":sparkler:": "🎇",
	":firecracker:": "🧨",
	":sparkles:": "✨",
	":balloon:": "🎈",
	":party_popper:": "🎉",
	":confetti_ball:": "🎊",
	":tanabata_tree:": "🎋",
	":pine_decoration:": "🎍",
	":japanese_dolls:": "🎎",
	":carp_streamer:": "🎏",
	":wind_chime:": "🎐",
	":moon_viewing_ceremony:": "🎑",
	":red_envelope:": "🧧",
	":ribbon:": "🎀",
	":wrapped_gift:": "🎁",
	":reminder_ribbon:": "🎗️",
	":admission_tickets:": "🎟️",
	":ticket:": "🎫",
	":military_medal:": "🎖️",
	":trophy:": "🏆",
	":sports_medal:": "🏅",
	":1st_place_medal:": "🥇",
	":2nd_place_medal:": "🥈",
	":3rd_place_medal:": "🥉",
	":soccer_ball:": "⚽",
	":baseball:": "⚾",
	":softball:": "🥎",
	":basketball:": "🏀",
	":volleyball:": "🏐",
	":american_football:": "🏈",
	":rugby_football:": "🏉",
	":tennis:": "🎾",
	":flying_disc:": "🥏",
	":bowling:": "🎳",
	":cricket_game:": "🏏",
	":field_hockey:": "🏑",
	":ice_hockey:": "🏒",
	":lacrosse:": "🥍",
	":ping_pong:": "🏓",
	":badminton:": "🏸",
	":boxing_glove:": "🥊",
	":martial_arts_uniform:": "🥋",
	":goal_net:": "🥅",
	":flag_in_hole:": "⛳",
	":ice_skate:": "⛸️",
	":fishing_pole:": "🎣",
	":diving_mask:": "🤿",
	":running_shirt:": "🎽",
	":skis:": "🎿",
	":sled:": "🛷",
	":curling_stone:": "🥌",
	":bullseye:": "🎯",
	":yo_yo:": "🪀",
	":kite:": "🪁",
	":water_pistol:": "🔫",
	":pool_8_ball:": "🎱",
	":crystal_ball:": "🔮",
	":magic_wand:": "🪄",
	":video_game:": "🎮",
	":joystick:": "🕹️",
	":slot_machine:": "🎰",
	":game_die:": "🎲",
	":puzzle_piece:": "🧩",
	":teddy_bear:": "🧸",
	":pinata:": "🪅",
	":mirror_ball:": "🪩",
	":nesting_dolls:": "🪆",
	":spade_suit:": "♠️",
	":heart_suit:": "♥️",
	":diamond_suit:": "♦️",
	":club_suit:": "♣️",
	":chess_pawn:": "♟️",
	":joker:": "🃏",
	":mahjong_red_dragon:": "🀄",
	":flower_playing_cards:": "🎴",
	":performing_arts:": "🎭",
	":framed_picture:": "🖼️",
	":artist_palette:": "🎨",
	":thread:": "🧵",
	":sewing_needle:": "🪡",
	":yarn:": "🧶",
	":knot:": "🪢",
	":glasses:": "👓",
	":sunglasses:": "🕶️",
	":goggles:": "🥽",
	":lab_coat:": "🥼",
	":safety_vest:": "🦺",
	":necktie:": "👔",
	":t_shirt:": "👕",
	":jeans:": "👖",
	":scarf:": "🧣",
	":gloves:": "🧤",
	":coat:": "🧥",
	":socks:": "🧦",
	":dress:": "👗",
	":kimono:": "👘",
	":sari:": "🥻",
	":one_piece_swimsuit:": "🩱",
	":briefs:": "🩲",
	":shorts:": "🩳",
	":bikini:": "👙",
	":woman_s_clothes:": "👚",
	":folding_hand_fan:": "🪭",
	":purse:": "👛",
	":handbag:": "👜",
	":clutch_bag:": "👝",
	":shopping_bags:": "🛍️",
	":backpack:": "🎒",
	":thong_sandal:": "🩴",
	":man_s_shoe:": "👞",
	":running_shoe:": "👟",
	":hiking_boot:": "🥾",
	":flat_shoe:": "🥿",
	":high_heeled_shoe:": "👠",
	":woman_s_sandal:": "👡",
	":ballet_shoes:": "🩰",
	":woman_s_boot:": "👢",
	":hair_pick:": "🪮",
	":crown:": "👑",
	":woman_s_hat:": "👒",
	":top_hat:": "🎩",
	":graduation_cap:": "🎓",
	":billed_cap:": "🧢",
	":military_helmet:": "🪖",
	":rescue_worker_s_helmet:": "⛑️",
	":prayer_beads:": "📿",
	":lipstick:": "💄",
	":ring:": "💍",
	":gem_stone:": "💎",
	":muted_speaker:": "🔇",
	":speaker_low_volume:": "🔈",
	":speaker_medium_volume:": "🔉",
	":speaker_high_volume:": "🔊",
	":loudspeaker:": "📢",
	":megaphone:": "📣",
	":postal_horn:": "📯",
	":bell:": "🔔",
	":bell_with_slash:": "🔕",
	":musical_score:": "🎼",
	":musical_note:": "🎵",
	":musical_notes:": "🎶",
	":studio_microphone:": "🎙️",
	":level_slider:": "🎚️",
	":control_knobs:": "🎛️",
	":microphone:": "🎤",
	":headphone:": "🎧",
	":radio:": "📻",
	":saxophone:": "🎷",
	":accordion:": "🪗",
	":guitar:": "🎸",
	":musical_keyboard:": "🎹",
	":trumpet:": "🎺",
	":violin:": "🎻",
	":banjo:": "🪕",
	":drum:": "🥁",
	":long_drum:": "🪘",
	":maracas:": "🪇",
	":flute:": "🪈",
	":mobile_phone:": "📱",
	":mobile_phone_with_arrow:": "📲",
	":telephone:": "☎️",
	":telephone_receiver:": "📞",
	":pager:": "📟",
	":fax_machine:": "📠",
	":battery:": "🔋",
	":low_battery:": "🪫",
	":electric_plug:": "🔌",
	":laptop:": "💻",
	":desktop_computer:": "🖥️",
	":printer:": "🖨️",
	":keyboard:": "⌨️",
	":computer_mouse:": "🖱️",
	":trackball:": "🖲️",
	":computer_disk:": "💽",
	":floppy_disk:": "💾",
	":optical_disk:": "💿",
	":dvd:": "📀",
	":abacus:": "🧮",
	":movie_camera:": "🎥",
	":film_frames:": "🎞️",
	":film_projector:": "📽️",
	":clapper_board:": "🎬",
	":television:": "📺",
	":camera:": "📷",
	":camera_with_flash:": "📸",
	":video_camera:": "📹",
	":videocassette:": "📼",
	":magnifying_glass_tilted_left:": "🔍",
	":magnifying_glass_tilted_right:": "🔎",
	":candle:": "🕯️",
	":light_bulb:": "💡",
	":flashlight:": "🔦",
	":red_paper_lantern:": "🏮",
	":diya_lamp:": "🪔",
	":notebook_with_decorative_cover:": "📔",
	":closed_book:": "📕",
	":open_book:": "📖",
	":green_book:": "📗",
	":blue_book:": "📘",
	":orange_book:": "📙",
	":books:": "📚",
	":notebook:": "📓",
	":ledger:": "📒",
	":page_with_curl:": "📃",
	":scroll:": "📜",
	":page_facing_up:": "📄",
	":newspaper:": "📰",
	":rolled_up_newspaper:": "🗞️",
	":bookmark_tabs:": "📑",
	":bookmark:": "🔖",
	":label:": "🏷️",
	":money_bag:": "💰",
	":coin:": "🪙",
	":yen_banknote:": "💴",
	":dollar_banknote:": "💵",
	":euro_banknote:": "💶",
	":pound_banknote:": "💷",
	":money_with_wings:": "💸",
	":credit_card:": "💳",
	":receipt:": "🧾",
	":chart_increasing_with_yen:": "💹",
	":envelope:": "✉️",
	":e_mail:": "📧",
	":incoming_envelope:": "📨",
	":envelope_with_arrow:": "📩",
	":outbox_tray:": "📤",
	":inbox_tray:": "📥",
	":package:": "📦",
	":closed_mailbox_with_raised_flag:": "📫",
	":closed_mailbox_with_lowered_flag:": "📪",
	":open_mailbox_with_raised_flag:": "📬",
	":open_mailbox_with_lowered_flag:": "📭",
	":postbox:": "📮",
	":ballot_box_with_ballot:": "🗳️",
	":pencil:": "✏️",
	":black_nib:": "✒️",
	":fountain_pen:": "🖋️",
	":pen:": "🖊️",
	":paintbrush:": "🖌️",
	":crayon:": "🖍️",
	":memo:": "📝",
	":briefcase:": "💼",
	":file_folder:": "📁",
	":open_file_folder:": "📂",
	":card_index_dividers:": "🗂️",
	":calendar:": "📅",
	":tear_off_calendar:": "📆",
	":spiral_notepad:": "🗒️",
	":spiral_calendar:": "🗓️",
	":card_index:": "📇",
	":chart_increasing:": "📈",
	":chart_decreasing:": "📉",
	":bar_chart:": "📊",
	":clipboard:": "📋",
	":pushpin:": "📌",
	":round_pushpin:": "📍",
	":paperclip:": "📎",
	":linked_paperclips:": "🖇️",
	":straight_ruler:": "📏",
	":triangular_ruler:": "📐",
	":scissors:": "✂️",
	":card_file_box:": "🗃️",
	":file_cabinet:": "🗄️",
	":wastebasket:": "🗑️",
	":locked:": "🔒",
	":unlocked:": "🔓",
	":locked_with_pen:": "🔏",
	":locked_with_key:": "🔐",
	":key:": "🔑",
	":old_key:": "🗝️",
	":hammer:": "🔨",
	":axe:": "🪓",
	":pick:": "⛏️",
	":hammer_and_pick:": "⚒️",
	":hammer_and_wrench:": "🛠️",
	":dagger:": "🗡️",
	":crossed_swords:": "⚔️",
	":bomb:": "💣",
	":boomerang:": "🪃",
	":bow_and_arrow:": "🏹",
	":shield:": "🛡️",
	":carpentry_saw:": "🪚",
	":wrench:": "🔧",
	":screwdriver:": "🪛",
	":nut_and_bolt:": "🔩",
	":gear:": "⚙️",
	":clamp:": "🗜️",
	":balance_scale:": "⚖️",
	":white_cane:": "🦯",
	":link:": "🔗",
	":chains:": "⛓️",
	":hook:": "🪝",
	":toolbox:": "🧰",
	":magnet:": "🧲",
	":ladder:": "🪜",
	":alembic:": "⚗️",
	":test_tube:": "🧪",
	":petri_dish:": "🧫",
	":dna:": "🧬",
	":microscope:": "🔬",
	":telescope:": "🔭",
	":satellite_antenna:": "📡",
	":syringe:": "💉",
	":drop_of_blood:": "🩸",
	":pill:": "💊",
	":adhesive_bandage:": "🩹",
	":crutch:": "🩼",
	":stethoscope:": "🩺",
	":x_ray:": "🩻",
	":door:": "🚪",
	":elevator:": "🛗",
	":mirror:": "🪞",
	":window:": "🪟",
	":bed:": "🛏️",
	":couch_and_lamp:": "🛋️",
	":chair:": "🪑",
	":toilet:": "🚽",
	":plunger:": "🪠",
	":shower:": "🚿",
	":bathtub:": "🛁",
	":mouse_trap:": "🪤",
	":razor:": "🪒",
	":lotion_bottle:": "🧴",
	":safety_pin:": "🧷",
	":broom:": "🧹",
	":basket:": "🧺",
	":roll_of_paper:": "🧻",
	":bucket:": "🪣",
	":soap:": "🧼",
	":bubbles:": "🫧",
	":toothbrush:": "🪥",
	":sponge:": "🧽",
	":fire_extinguisher:": "🧯",
	":shopping_cart:": "🛒",
	":cigarette:": "🚬",
	":coffin:": "⚰️",
	":headstone:": "🪦",
	":funeral_urn:": "⚱️",
	":nazar_amulet:": "🧿",
	":hamsa:": "🪬",
	":moai:": "🗿",
	":placard:": "🪧",
	":identification_card:": "🪪",
	":atm_sign:": "🏧",
	":litter_in_bin_sign:": "🚮",
	":potable_water:": "🚰",
	":wheelchair_symbol:": "♿",
	":men_s_room:": "🚹",
	":women_s_room:": "🚺",
	":restroom:": "🚻",
	":baby_symbol:": "🚼",
	":water_closet:": "🚾",
	":passport_control:": "🛂",
	":customs:": "🛃",
	":baggage_claim:": "🛄",
	":left_luggage:": "🛅",
	":warning:": "⚠️",
	":children_crossing:": "🚸",
	":no_entry:": "⛔",
	":prohibited:": "🚫",
	":no_bicycles:": "🚳",
	":no_smoking:": "🚭",
	":no_littering:": "🚯",
	":non_potable_water:": "🚱",
	":no_pedestrians:": "🚷",
	":no_mobile_phones:": "📵",
	":no_one_under_eighteen:": "🔞",
	":radioactive:": "☢️",
	":biohazard:": "☣️",
	":up_arrow:": "⬆️",
	":up_right_arrow:": "↗️",
	":right_arrow:": "➡️",
	":down_right_arrow:": "↘️",
	":down_arrow:": "⬇️",
	":down_left_arrow:": "↙️",
	":left_arrow:": "⬅️",
	":up_left_arrow:": "↖️",
	":up_down_arrow:": "↕️",
	":left_right_arrow:": "↔️",
	":right_arrow_curving_left:": "↩️",
	":left_arrow_curving_right:": "↪️",
	":right_arrow_curving_up:": "⤴️",
	":right_arrow_curving_down:": "⤵️",
	":clockwise_vertical_arrows:": "🔃",
	":counterclockwise_arrows_button:": "🔄",
	":back_arrow:": "🔙",
	":end_arrow:": "🔚",
	":on_arrow:": "🔛",
	":soon_arrow:": "🔜",
	":top_arrow:": "🔝",
	":place_of_worship:": "🛐",
	":atom_symbol:": "⚛️",
	":om:": "🕉️",
	":star_of_david:": "✡️",
	":wheel_of_dharma:": "☸️",
	":yin_yang:": "☯️",
	":latin_cross:": "✝️",
	":orthodox_cross:": "☦️",
	":star_and_crescent:": "☪️",
	":peace_symbol:": "☮️",
	":menorah:": "🕎",
	":dotted_six_pointed_star:": "🔯",
	":khanda:": "🪯",
	":aries:": "♈",
	":taurus:": "♉",
	":gemini:": "♊",
	":cancer:": "♋",
	":leo:": "♌",
	":virgo:": "♍",
	":libra:": "♎",
	":scorpio:": "♏",
	":sagittarius:": "♐",
	":capricorn:": "♑",
	":aquarius:": "♒",
	":pisces:": "♓",
	":ophiuchus:": "⛎",
	":shuffle_tracks_button:": "🔀",
	":repeat_button:": "🔁",
	":repeat_single_button:": "🔂",
	":play_button:": "▶️",
	":fast_forward_button:": "⏩",
	":next_track_button:": "⏭️",
	":play_or_pause_button:": "⏯️",
	":reverse_button:": "◀️",
	":fast_reverse_button:": "⏪",
	":last_track_button:": "⏮️",
	":upwards_button:": "🔼",
	":fast_up_button:": "⏫",
	":downwards_button:": "🔽",
	":fast_down_button:": "⏬",
	":pause_button:": "⏸️",
	":stop_button:": "⏹️",
	":record_button:": "⏺️",
	":eject_button:": "⏏️",
	":cinema:": "🎦",
	":dim_button:": "🔅",
	":bright_button:": "🔆",
	":antenna_bars:": "📶",
	":wireless:": "🛜",
	":vibration_mode:": "📳",
	":mobile_phone_off:": "📴",
	":female_sign:": "♀️",
	":male_sign:": "♂️",
	":transgender_symbol:": "⚧️",
	":multiply:": "✖️",
	":plus:": "➕",
	":minus:": "➖",
	":divide:": "➗",
	":heavy_equals_sign:": "🟰",
	":infinity:": "♾️",
	":double_exclamation_mark:": "‼️",
	":exclamation_question_mark:": "⁉️",
	":red_question_mark:": "❓",
	":white_question_mark:": "❔",
	":white_exclamation_mark:": "❕",
	":red_exclamation_mark:": "❗",
	":wavy_dash:": "〰️",
	":currency_exchange:": "💱",
	":heavy_dollar_sign:": "💲",
	":medical_symbol:": "⚕️",
	":recycling_symbol:": "♻️",
	":fleur_de_lis:": "⚜️",
	":trident_emblem:": "🔱",
	":name_badge:": "📛",
	":japanese_symbol_for_beginner:": "🔰",
	":hollow_red_circle:": "⭕",
	":check_mark_button:": "✅",
	":check_box_with_check:": "☑️",
	":check_mark:": "✔️",
	":cross_mark:": "❌",
	":cross_mark_button:": "❎",
	":curly_loop:": "➰",
	":double_curly_loop:": "➿",
	":part_alternation_mark:": "〽️",
	":eight_spoked_asterisk:": "✳️",
	":eight_pointed_star:": "✴️",
	":sparkle:": "❇️",
	":copyright:": "©️",
	":registered:": "®️",
	":trade_mark:": "™️",
	":keycap_number_sign:": "#️⃣",
	":keycap_asterisk:": "*️⃣",
	":keycap_0:": "0️⃣",
	":keycap_1:": "1️⃣",
	":keycap_2:": "2️⃣",
	":keycap_3:": "3️⃣",
	":keycap_4:": "4️⃣",
	":keycap_5:": "5️⃣",
	":keycap_6:": "6️⃣",
	":keycap_7:": "7️⃣",
	":keycap_8:": "8️⃣",
	":keycap_9:": "9️⃣",
	":keycap_10:": "🔟",
	":input_latin_uppercase:": "🔠",
	":input_latin_lowercase:": "🔡",
	":input_numbers:": "🔢",
	":input_symbols:": "🔣",
	":input_latin_letters:": "🔤",
	":a_button:": "🅰️",
	":ab_button:": "🆎",
	":b_button:": "🅱️",
	":cl_button:": "🆑",
	":cool_button:": "🆒",
	":free_button:": "🆓",
	":information:": "ℹ️",
	":id_button:": "🆔",
	":circled_m:": "Ⓜ️",
	":new_button:": "🆕",
	":ng_button:": "🆖",
	":o_button:": "🅾️",
	":ok_button:": "🆗",
	":p_button:": "🅿️",
	":sos_button:": "🆘",
	":up_button:": "🆙",
	":vs_button:": "🆚",
	":japanese_here_button:": "🈁",
	":japanese_service_charge_button:": "🈂️",
	":japanese_monthly_amount_button:": "🈷️",
	":japanese_not_free_of_charge_button:": "🈶",
	":japanese_reserved_button:": "🈯",
	":japanese_bargain_button:": "🉐",
	":japanese_discount_button:": "🈹",
	":japanese_free_of_charge_button:": "🈚",
	":japanese_prohibited_button:": "🈲",
	":japanese_acceptable_button:": "🉑",
	":japanese_application_button:": "🈸",
	":japanese_passing_grade_button:": "🈴",
	":japanese_vacancy_button:": "🈳",
	":japanese_congratulations_button:": "㊗️",
	":japanese_secret_button:": "㊙️",
	":japanese_open_for_business_button:": "🈺",
	":japanese_no_vacancy_button:": "🈵",
	":red_circle:": "🔴",
	":orange_circle:": "🟠",
	":yellow_circle:": "🟡",
	":green_circle:": "🟢",
	":blue_circle:": "🔵",
	":purple_circle:": "🟣",
	":brown_circle:": "🟤",
	":black_circle:": "⚫",
	":white_circle:": "⚪",
	":red_square:": "🟥",
	":orange_square:": "🟧",
	":yellow_square:": "🟨",
	":green_square:": "🟩",
	":blue_square:": "🟦",
	":purple_square:": "🟪",
	":brown_square:": "🟫",
	":black_large_square:": "⬛",
	":white_large_square:": "⬜",
	":black_medium_square:": "◼️",
	":white_medium_square:": "◻️",
	":black_medium_small_square:": "◾",
	":white_medium_small_square:": "◽",
	":black_small_square:": "▪️",
	":white_small_square:": "▫️",
	":large_orange_diamond:": "🔶",
	":large_blue_diamond:": "🔷",
	":small_orange_diamond:": "🔸",
	":small_blue_diamond:": "🔹",
	":red_triangle_pointed_up:": "🔺",
	":red_triangle_pointed_down:": "🔻",
	":diamond_with_a_dot:": "💠",
	":radio_button:": "🔘",
	":white_square_button:": "🔳",
	":black_square_button:": "🔲",
	":chequered_flag:": "🏁",
	":triangular_flag:": "🚩",
	":crossed_flags:": "🎌",
	":black_flag:": "🏴",
	":white_flag:": "🏳️",
	":rainbow_flag:": "🏳️‍🌈",
	":transgender_flag:": "🏳️‍⚧️",
	":pirate_flag:": "🏴‍☠️",
	":flag_ascension_island:": "🇦🇨",
	":flag_andorra:": "🇦🇩",
	":flag_united_arab_emirates:": "🇦🇪",
	":flag_afghanistan:": "🇦🇫",
	":flag_antigua_barbuda:": "🇦🇬",
	":flag_anguilla:": "🇦🇮",
	":flag_albania:": "🇦🇱",
	":flag_armenia:": "🇦🇲",
	":flag_angola:": "🇦🇴",
	":flag_antarctica:": "🇦🇶",
	":flag_argentina:": "🇦🇷",
	":flag_american_samoa:": "🇦🇸",
	":flag_austria:": "🇦🇹",
	":flag_australia:": "🇦🇺",
	":flag_aruba:": "🇦🇼",
	":flag_aland_islands:": "🇦🇽",
	":flag_azerbaijan:": "🇦🇿",
	":flag_bosnia_herzegovina:": "🇧🇦",
	":flag_barbados:": "🇧🇧",
	":flag_bangladesh:": "🇧🇩",
	":flag_belgium:": "🇧🇪",
	":flag_burkina_faso:": "🇧🇫",
	":flag_bulgaria:": "🇧🇬",
	":flag_bahrain:": "🇧🇭",
	":flag_burundi:": "🇧🇮",
	":flag_benin:": "🇧🇯",
	":flag_st_barthelemy:": "🇧🇱",
	":flag_bermuda:": "🇧🇲",
	":flag_brunei:": "🇧🇳",
	":flag_bolivia:": "🇧🇴",
	":flag_caribbean_netherlands:": "🇧🇶",
	":flag_brazil:": "🇧🇷",
	":flag_bahamas:": "🇧🇸",
	":flag_bhutan:": "🇧🇹",
	":flag_bouvet_island:": "🇧🇻",
	":flag_botswana:": "🇧🇼",
	":flag_belarus:": "🇧🇾",
	":flag_belize:": "🇧🇿",
	":flag_canada:": "🇨🇦",
	":flag_cocos_islands:": "🇨🇨",
	":flag_congo_kinshasa:": "🇨🇩",
	":flag_central_african_republic:": "🇨🇫",
	":flag_congo_brazzaville:": "🇨🇬",
	":flag_switzerland:": "🇨🇭",
	":flag_cote_d_ivoire:": "🇨🇮",
	":flag_cook_islands:": "🇨🇰",
	":flag_chile:": "🇨🇱",
	":flag_cameroon:": "🇨🇲",
	":flag_china:": "🇨🇳",
	":flag_colombia:": "🇨🇴",
	":flag_clipperton_island:": "🇨🇵",
	":flag_costa_rica:": "🇨🇷",
	":flag_cuba:": "🇨🇺",
	":flag_cape_verde:": "🇨🇻",
	":flag_curacao:": "🇨🇼",
	":flag_christmas_island:": "🇨🇽",
	":flag_cyprus:": "🇨🇾",
	":flag_czechia:": "🇨🇿",
	":flag_germany:": "🇩🇪",
	":flag_diego_garcia:": "🇩🇬",
	":flag_djibouti:": "🇩🇯",
	":flag_denmark:": "🇩🇰",
	":flag_dominica:": "🇩🇲",
	":flag_dominican_republic:": "🇩🇴",
	":flag_algeria:": "🇩🇿",
	":flag_ceuta_melilla:": "🇪🇦",
	":flag_ecuador:": "🇪🇨",
	":flag_estonia:": "🇪🇪",
	":flag_egypt:": "🇪🇬",
	":flag_western_sahara:": "🇪🇭",
	":flag_eritrea:": "🇪🇷",
	":flag_spain:": "🇪🇸",
	":flag_ethiopia:": "🇪🇹",
	":flag_european_union:": "🇪🇺",
	":flag_finland:": "🇫🇮",
	":flag_fiji:": "🇫🇯",
	":flag_falkland_islands:": "🇫🇰",
	":flag_micronesia:": "🇫🇲",
	":flag_faroe_islands:": "🇫🇴",
	":flag_france:": "🇫🇷",
	":flag_gabon:": "🇬🇦",
	":flag_united_kingdom:": "🇬🇧",
	":flag_grenada:": "🇬🇩",
	":flag_georgia:": "🇬🇪",
	":flag_french_guiana:": "🇬🇫",
	":flag_guernsey:": "🇬🇬",
	":flag_ghana:": "🇬🇭",
	":flag_gibraltar:": "🇬🇮",
	":flag_greenland:": "🇬🇱",
	":flag_gambia:": "🇬🇲",
	":flag_guinea:": "🇬🇳",
	":flag_guadeloupe:": "🇬🇵",
	":flag_equatorial_guinea:": "🇬🇶",
	":flag_greece:": "🇬🇷",
	":flag_south_georgia_south_sandwich_islands:": "🇬🇸",
	":flag_guatemala:": "🇬🇹",
	":flag_guam:": "🇬🇺",
	":flag_guinea_bissau:": "🇬🇼",
	":flag_guyana:": "🇬🇾",
	":flag_hong_kong_sar_china:": "🇭🇰",
	":flag_heard_mcdonald_islands:": "🇭🇲",
	":flag_honduras:": "🇭🇳",
	":flag_croatia:": "🇭🇷",
	":flag_haiti:": "🇭🇹",
	":flag_hungary:": "🇭🇺",
	":flag_canary_islands:": "🇮🇨",
	":flag_indonesia:": "🇮🇩",
	":flag_ireland:": "🇮🇪",
	":flag_israel:": "🇮🇱",
	":flag_isle_of_man:": "🇮🇲",
	":flag_india:": "🇮🇳",
	":flag_british_indian_ocean_territory:": "🇮🇴",
	":flag_iraq:": "🇮🇶",
	":flag_iran:": "🇮🇷",
	":flag_iceland:": "🇮🇸",
	":flag_italy:": "🇮🇹",
	":flag_jersey:": "🇯🇪",
	":flag_jamaica:": "🇯🇲",
	":flag_jordan:": "🇯🇴",
	":flag_japan:": "🇯🇵",
	":flag_kenya:": "🇰🇪",
	":flag_kyrgyzstan:": "🇰🇬",
	":flag_cambodia:": "🇰🇭",
	":flag_kiribati:": "🇰🇮",
	":flag_comoros:": "🇰🇲",
	":flag_st_kitts_nevis:": "🇰🇳",
	":flag_north_korea:": "🇰🇵",
	":flag_south_korea:": "🇰🇷",
	":flag_kuwait:": "🇰🇼",
	":flag_cayman_islands:": "🇰🇾",
	":flag_kazakhstan:": "🇰🇿",
	":flag_laos:": "🇱🇦",
	":flag_lebanon:": "🇱🇧",
	":flag_st_lucia:": "🇱🇨",
	":flag_liechtenstein:": "🇱🇮",
	":flag_sri_lanka:": "🇱🇰",
	":flag_liberia:": "🇱🇷",
	":flag_lesotho:": "🇱🇸",
	":flag_lithuania:": "🇱🇹",
	":flag_luxembourg:": "🇱🇺",
	":flag_latvia:": "🇱🇻",
	":flag_libya:": "🇱🇾",
	":flag_morocco:": "🇲🇦",
	":flag_monaco:": "🇲🇨",
	":flag_moldova:": "🇲🇩",
	":flag_montenegro:": "🇲🇪",
	":flag_st_martin:": "🇲🇫",
	":flag_madagascar:": "🇲🇬",
	":flag_marshall_islands:": "🇲🇭",
	":flag_north_macedonia:": "🇲🇰",
	":flag_mali:": "🇲🇱",
	":flag_myanmar:": "🇲🇲",
	":flag_mongolia:": "🇲🇳",
	":flag_macao_sar_china:": "🇲🇴",
	":flag_northern_mariana_islands:": "🇲🇵",
	":flag_martinique:": "🇲🇶",
	":flag_mauritania:": "🇲🇷",
	":flag_montserrat:": "🇲🇸",
	":flag_malta:": "🇲🇹",
	":flag_mauritius:": "🇲🇺",
	":flag_maldives:": "🇲🇻",
	":flag_malawi:": "🇲🇼",
	":flag_mexico:": "🇲🇽",
	":flag_malaysia:": "🇲🇾",
	":flag_mozambique:": "🇲🇿",
	":flag_namibia:": "🇳🇦",
	":flag_new_caledonia:": "🇳🇨",
	":flag_niger:": "🇳🇪",
	":flag_norfolk_island:": "🇳🇫",
	":flag_nigeria:": "🇳🇬",
	":flag_nicaragua:": "🇳🇮",
	":flag_netherlands:": "🇳🇱",
	":flag_norway:": "🇳🇴",
	":flag_nepal:": "🇳🇵",
	":flag_nauru:": "🇳🇷",
	":flag_niue:": "🇳🇺",
	":flag_new_zealand:": "🇳🇿",
	":flag_oman:": "🇴🇲",
	":flag_panama:": "🇵🇦",
	":flag_peru:": "🇵🇪",
	":flag_french_polynesia:": "🇵🇫",
	":flag_papua_new_guinea:": "🇵🇬",
	":flag_philippines:": "🇵🇭",
	":flag_pakistan:": "🇵🇰",
	":flag_poland:": "🇵🇱",
	":flag_st_pierre_miquelon:": "🇵🇲",
	":flag_pitcairn_islands:": "🇵🇳",
	":flag_puerto_rico:": "🇵🇷",
	":flag_palestinian_territories:": "🇵🇸",
	":flag_portugal:": "🇵🇹",
	":flag_palau:": "🇵🇼",
	":flag_paraguay:": "🇵🇾",
	":flag_qatar:": "🇶🇦",
	":flag_reunion:": "🇷🇪",
	":flag_romania:": "🇷🇴",
	":flag_serbia:": "🇷🇸",
	":flag_russia:": "🇷🇺",
	":flag_rwanda:": "🇷🇼",
	":flag_saudi_arabia:": "🇸🇦",
	":flag_solomon_islands:": "🇸🇧",
	":flag_seychelles:": "🇸🇨",
	":flag_sudan:": "🇸🇩",
	":flag_sweden:": "🇸🇪",
	":flag_singapore:": "🇸🇬",
	":flag_st_helena:": "🇸🇭",
	":flag_slovenia:": "🇸🇮",
	":flag_svalbard_jan_mayen:": "🇸🇯",
	":flag_slovakia:": "🇸🇰",
	":flag_sierra_leone:": "🇸🇱",
	":flag_san_marino:": "🇸🇲",
	":flag_senegal:": "🇸🇳",
	":flag_somalia:": "🇸🇴",
	":flag_suriname:": "🇸🇷",
	":flag_south_sudan:": "🇸🇸",
	":flag_sao_tome_principe:": "🇸🇹",
	":flag_el_salvador:": "🇸🇻",
	":flag_sint_maarten:": "🇸🇽",
	":flag_syria:": "🇸🇾",
	":flag_eswatini:": "🇸🇿",
	":flag_tristan_da_cunha:": "🇹🇦",
	":flag_turks_caicos_islands:": "🇹🇨",
	":flag_chad:": "🇹🇩",
	":flag_french_southern_territories:": "🇹🇫",
	":flag_togo:": "🇹🇬",
	":flag_thailand:": "🇹🇭",
	":flag_tajikistan:": "🇹🇯",
	":flag_tokelau:": "🇹🇰",
	":flag_timor_leste:": "🇹🇱",
	":flag_turkmenistan:": "🇹🇲",
	":flag_tunisia:": "🇹🇳",
	":flag_tonga:": "🇹🇴",
	":flag_turkey:": "🇹🇷",
	":flag_trinidad_tobago:": "🇹🇹",
	":flag_tuvalu:": "🇹🇻",
	":flag_taiwan:": "🇹🇼",
	":flag_tanzania:": "🇹🇿",
	":flag_ukraine:": "🇺🇦",
	":flag_uganda:": "🇺🇬",
	":flag_u_s_outlying_islands:": "🇺🇲",
	":flag_united_nations:": "🇺🇳",
	":flag_united_states:": "🇺🇸",
	":flag_uruguay:": "🇺🇾",
	":flag_uzbekistan:": "🇺🇿",
	":flag_vatican_city:": "🇻🇦",
	":flag_st_vincent_grenadines:": "🇻🇨",
	":flag_venezuela:": "🇻🇪",
	":flag_british_virgin_islands:": "🇻🇬",
	":flag_u_s_virgin_islands:": "🇻🇮",
	":flag_vietnam:": "🇻🇳",
	":flag_vanuatu:": "🇻🇺",
	":flag_wallis_futuna:": "🇼🇫",
	":flag_samoa:": "🇼🇸",
	":flag_kosovo:": "🇽🇰",
	":flag_yemen:": "🇾🇪",
	":flag_mayotte:": "🇾🇹",
	":flag_south_africa:": "🇿🇦",
	":flag_zambia:": "🇿🇲",
	":flag_zimbabwe:": "🇿🇼",
	":flag_england:": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
	":flag_scotland:": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
	":flag_wales:": "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
]
