query GroupMergeRequests($fullPath: ID!, $state: MergeRequestState, $search: String, $draft: Boolean, $subscribed: SubscriptionStatus) {
  group(fullPath: $fullPath) {
    mergeRequests(
      state: $state
      search: $search
      draft: $draft
      subscribed: $subscribed
    ) {
      nodes {
        iid
        title
        reference(full: true)
        state
        upvotes
        downvotes
        userNotesCount
        author {
          avatarUrl
          name
          username
        }
        createdAt
        webUrl
      }
    }
  }
}
