query UserReviewRequestedMergeRequests($state: MergeRequestState, $search: String, $draft: Boolean, $subscribed: SubscriptionStatus) {
  currentUser {
    reviewRequestedMergeRequests(
      state: $state
      search: $search
      draft: $draft
      subscribed: $subscribed
    ) {
      count
      nodes {
        project {
          fullPath
        }
        iid
        title
        reference(full: true)
        state
        upvotes
        downvotes
        userNotesCount
        author {
          avatarUrl
          name
          username
        }
        createdAt
        webUrl
      }
    }
  }
}
