// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public extension Objects {
  /// Autogenerated return type of StarProject.
  static let StarProjectPayload = ApolloAPI.Object(
    typename: "StarProjectPayload",
    implementedInterfaces: [],
    keyFields: nil
  )
}