query MergeRequest($fullPath: ID!, $iid: String!) {
  project(fullPath: $fullPath) {
  id
  avatarUrl

    mergeRequest(iid: $iid) {
      iid
      title
      description
      reference(full: true)
      state
      sourceBranch
      targetBranch
      sourceProject {
        fullPath
      }
      diffStatsSummary {
        additions
        deletions
        fileCount
      }
      upvotes
      downvotes
      userNotesCount
      author {
        avatarUrl
        name
        username
      }
      userPermissions {
        canApprove
        canMerge
        updateMergeRequest
        createNote
      }
      createdAt
      webUrl

      approved
      mergeStatusEnum
      conflicts
      detailedMergeStatus

      assignees {
        nodes {
          avatarUrl
          username
        }
      }

      reviewers {
        nodes {
          avatarUrl
          username
        }
      }

      labels {
        nodes {
          title
          color
          textColor
        }
      }

      milestone {
        iid
        title
      }

      humanTimeEstimate
      humanTotalTimeSpent

      notes {
        nodes {
          id
          author {
            avatarUrl
            name
            username
          }
          maxAccessLevelOfAuthor
          body
          system
          systemNoteIconName
          createdAt
          updatedAt
        }
      }
    }
  }
}
