query Project($fullPath: ID!) {
  project(fullPath: $fullPath) {
    id
    avatarUrl
    name
    visibility
    description
    topics
    starCount
    forksCount
    issuesEnabled
    openIssuesCount
    mergeRequestsEnabled
    jobsEnabled
    openMergeRequestsCount
    webUrl
    httpUrlToRepo
    sshUrlToRepo
    createdAt
    namespace {
      id
      name
      fullPath
    }
    repository {
      rootRef
      blobs(paths: ["README", "README.txt", "README.md"]) {
        nodes {
          rawTextBlob
        }
      }
      tree {
        lastCommit {
          title
          shortId
          authorName
          authoredDate
		  webUrl
          signature {
            verificationStatus
          }
          pipelines {
            nodes {
              status
            }
          }
        }
      }
    }
    languages {
      name
      share
      color
    }
    userPermissions {
      createIssue
      pushCode
      forkProject
      requestAccess
    }
  }
}
